<?php /** @var $this Dlayer_View_Codehinting */ ?>

<script type="text/javascript">
	$(document).ready(function() 
	{
		dlayer.tools.template.fn.horizontalSplit();
	});
</script>

<div class="col-xs-12">
	<h3>Rows <small>Create two custom sized rows</small></h3>
	
	<p>Move the mouse to where you would like to split the content block and 
		then click the left mouse button. Don't worry too much if you are off 
		a little when you click, you can come back and move the split if you 
		need to.</p>
		
	<p class="advanced-info">The block will be split into 
		<strong>two</strong> rows, the top row will be 
		<strong class="one">xx</strong> pixels high and the bottom 
		row will be <strong class="two">xx</strong> pixels high.</p>
</div>