<?php /** @var $this Dlayer_View_Codehinting */ ?>

<script type="text/javascript">
	$(document).ready(function() 
	{
		dlayer.tools.template.fn.horizontalSplit();
	});
</script>

<div class="col-xs-12">
	<h3>Horizontal split <small>Custom dimensions</small></h3>
	
	<p>Move the mouse to where you would like to split the block and then 
		click the left mouse button. Don't worry too much if you are off a 
		little when you click, you can come back and move the split if you 
		need to.</p>
		
	<p class="advanced-info">The block will be split into 
		<span class="info">2</span> sections, the top block will be 
		<span class="info one"></span> pixels high and the bottom block 
		will be <span class="info two"></span> pixels high.</p>
</div>