<?php /** @var $this Dlayer_View_Codehinting */ ?>

<script type="text/javascript">
	$(document).ready(function() 
	{
		dlayer.tools.template.fn.splitReset();
	});
</script>

<div class="col-xs-12">
	<h3>Help <small>Split the content block horizontally into multiple 
		rows</small></h3>
	
	<p>This tool allows you to split the selected content block into two or 
		more rows, you can do this by either choosing where to split the 
		content block or by using one of the preset split options, the preset 
		options will create equivalent sized rows. In both cases you can 
		modify the size of the new rows at a later date.</p>
		
	<p>In the Template design the rows have a fixed height, this is only so 
		that yoiu can easily work on them, by default rows will have a 
		dynamic height unless you choose a fixed height.</p>
</div>