<?php /** @var $this Dlayer_View_Codehinting */ ?>

<script type="text/javascript">
	$(document).ready(function() 
	{
		dlayer.tools.template.fn.splitReset();
	});
</script>

<div class="col-xs-12">		
	<h3>Help <small>Split the content block into multiple rows</small></h3>
	
	<p>This tool allows you to split the selected content item into two or 
		more separate rows, you can do this be either choosing the quick 
		options or by choosing specifically where to split the content block. 
		In both cases you can modify the size of each of the rows 
		independently at a later date.</p>
		
	<p class="dev-note bg-info">In the Template designer generated rows have 
		a fixed height, this is only so that they are selectable, by default 
		rows have a dynamic height and will resize based on their content 
		although you have the flexibility to define a fixed height if that is 
		what you need.</p>
</div>