<?php /** @var Dlayer_View_Codehinting */ $this ?>

<script type="text/javascript">
$(document).ready(function() 
{
	dlayer.tools.template.fn.splitReset();
});
</script>

<div class="col-xs-12">
	<h3>Rows <small>Create equivalent sized rows</small></h3>

	<div class="row">
		<div class="col-xs-3">
			<img src="/images/ribbon/template/horizontal-splits-2.png" 
			width="60" height="40" class="img-rounded" />
		</div>
		<div class="col-xs-7">
			<h4>Two rows <small>Split the selected content area into 
			<strong>two</strong> equivalent rows.</small></h4>
		</div>
		<div class="col-xs-2">
			<form action="/template/process/auto-tool" method="post" class="form">
				<input type="hidden" name="id" value="<?php echo $this->escape($this->div_id); ?>" />
				<input type="hidden" name="params[sections]" value="2" />
				<input type="hidden" name="tool" value="split-horizontal" />
				<input type="hidden" name="params[multi_use]" value="<?php echo $this->escape($this->multi_use); ?>" />
				<div class="form-group">
					<input type="submit" class="btn btn-primary btn-xs" name="submit" value="Go" />
				</div>
			</form>
		</div>
	</div>
	
	<div class="row">
		<div class="col-xs-3">
			<img src="/images/ribbon/template/horizontal-splits-3.png" 
			width="60" height="40" class="img-rounded" />
		</div>
		<div class="col-xs-7">
			<h4>Three rows <small>Split the selected content area into 
			<strong>three</strong> equivalent rows.</small></h4>
		</div>
		<div class="col-xs-2">
			<form action="/template/process/auto-tool" method="post" class="form">
				<input type="hidden" name="id" value="<?php echo $this->escape($this->div_id); ?>" />
				<input type="hidden" name="params[sections]" value="3" />
				<input type="hidden" name="tool" value="split-horizontal" />
				<input type="hidden" name="params[multi_use]" value="<?php echo $this->escape($this->multi_use); ?>" />
				<div class="form-group">
					<input type="submit" class="btn btn-primary btn-xs" name="submit" value="Go" />
				</div>
			</form>
		</div>
	</div>
	
	<div class="row">
		<div class="col-xs-3">
			<img src="/images/ribbon/template/horizontal-splits-4.png" 
			width="60" height="40" class="img-rounded" />
		</div>
		<div class="col-xs-7">
			<h4>Four rows <small>Split the selected content area into 
			<strong>four</strong> equivalent rows.</small></h4>
		</div>
		<div class="col-xs-2">
			<form action="/template/process/auto-tool" method="post" class="form">
				<input type="hidden" name="id" value="<?php echo $this->escape($this->div_id); ?>" />
				<input type="hidden" name="params[sections]" value="4" />
				<input type="hidden" name="tool" value="split-horizontal" />
				<input type="hidden" name="params[multi_use]" value="<?php echo $this->escape($this->multi_use); ?>" />
				<div class="form-group">
					<input type="submit" class="btn btn-primary btn-xs" name="submit" value="Go" />
				</div>
			</form>
		</div>
	</div>
	
	<div class="row">
		<div class="col-xs-3">
			<img src="/images/ribbon/template/horizontal-splits-5.png" 
			width="60" height="40" class="img-rounded" />
		</div>
		<div class="col-xs-7">
			<h4>Five rows <small>Split the selected content area into 
			<strong>five</strong> equivalent rows.</small></h4>
		</div>
		<div class="col-xs-2">
			<form action="/template/process/auto-tool" method="post" class="form">
				<input type="hidden" name="id" value="<?php echo $this->escape($this->div_id); ?>" />
				<input type="hidden" name="params[sections]" value="5" />
				<input type="hidden" name="tool" value="split-horizontal" />
				<input type="hidden" name="params[multi_use]" value="<?php echo $this->escape($this->multi_use); ?>" />
				<div class="form-group">
					<input type="submit" class="btn btn-primary btn-xs" name="submit" value="Go" />
				</div>
			</form>
		</div>
	</div>
</div>