<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div id="content">
    <h1>Library development</h1>
    
    <h2>Image library resizer</h2>
        
    <p>Call the process to method to generate the resized image, any errors will 
    be shown, if no errors return and then click the view button to see the 
    newly generated thumbnail.</p>
    
    <p>This <a href="/images/testing/resizer/test.jpg">test image</a> will be 
    used by the resizer.</p>
    
    <ul>
        <li><a href="/dev/resizer/process">Process</a> - 
        Call the resizer.</li>
        <?php if(file_exists('images/testing/resizer/test-resized.jpg') == TRUE) { ?>
        <li><a href="/images/testing/resizer/test-resized.jpg">View</a> - View generated image</li>
        <li><a href="/dev/resizer/delete">Delete</a> - Delete the generated image.</li>
        <?php } ?>
    </ul>
</div>