<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div id="content">
    <h1>Library development</h1>
    
    <h2>Image library resizer - process</h2>
    
    <p>This action will have attempted to generate a image from the test 
    image, below will either be a success message or the generated errors.</p>
    
    <p>Return to the <a href="/dev/resizer/index">image library resizer.</a> 
    to see and delete the generated image.</p>
    
    <p><strong>Errors:</strong> <?php echo $this->escape($this->error); ?></p>
</div>