<?php /** @var Dlayer_View_Codehinting */ $this ?>

<div class="col-md-12 col-sm-12">
	<h3>Content row selected</h3>
			
	<h5><span class="glyphicon glyphicon-play" aria-hidden="true"></span>
	Add a new content item</h5>

	<h5><span class="glyphicon glyphicon-play" aria-hidden="true"></span>
	Edit an existing content item</h5>
	
	<h5><span class="glyphicon glyphicon-play" aria-hidden="true"></span>
	Edit the content row</h5>
	
	<p>If a content item is selectable it will highlight when you hover 
		the mouse over it, to select the content item simply click the 
		left mouse button.</p>
	
	<p>To add a brand new content item simply select the tool that 
		corresponds to the content item you want to create, for example 
		the form tool to import a form from the Form builder.</p>
	
	<p>To edit an existing content item simply select it.</p>
	
	<p>To edit the content row select a tab from above.</p>
</div>
