<?php /** @var Dlayer_View_Codehinting */ $this ?>

<div class="col-md-12 col-sm-12">
	<h3>Row selected</h3>

	<h5><span class="glyphicon glyphicon-play" aria-hidden="true"></span>
	Add a new column</h5>

	<h5><span class="glyphicon glyphicon-play" aria-hidden="true"></span>
	Select a column</h5>
			
	<h5><span class="glyphicon glyphicon-play" aria-hidden="true"></span>
	Add a content item</h5>

	<h5><span class="glyphicon glyphicon-play" aria-hidden="true"></span>
	Edit an existing content item</h5>

	<h5><span class="glyphicon glyphicon-play" aria-hidden="true"></span>
	Edit the content row</h5>

	<p>To add a new column please select the 'add column' tool.</p>

	<p>If a column is selectable it will highlight when you hover your cursor over it, to select the column, click.</p>

	<p>To add a new content item select the tool that corresponds to the content item you want to create.</p>
	
	<p>If a content item is selectable it will highlight when you hover your cursor over it, to select the content
		item, click.</p>

	<p>To edit the properties for the row select a tab above.</p>
</div>
