<?php /** @var Dlayer_View_Codehinting */ $this ?>

<script type="text/javascript">
$(document).ready(function() 
{
    dlayer.tools.template.fn.splitReset();
});
</script>

<h2>Split block vertically</h2>

<p>This tool allows you to split the selected template block up into two or 
more columns, you can do this by choosing where to split the block or by 
using one of the 'Quick' options which splits the block into equivalent 
sized columns.</p>

<p>In both cases you can modify the sizes of the new columns after you have 
split the template block.</p>