<?php /** @var Dlayer_View_Codehinting */ $this ?>

<script type="text/javascript">
$(document).ready(function() 
{
    dlayer.tools.template.fn.splitReset();
});
</script>

<div class="block">
    <div class="image"><img src="/images/ribbon/template/vertical-splits-2.png" width="60" height="40" /></div>
    <div class="content">
        <div class="title">Two sections</div>
        <div class="text">Split the selected block into <strong>2</strong> 
        equal sections.</div>
    </div>
    <form action="/template/process/auto-tool" method="post">
        <input type="hidden" name="id" value="<?php echo $this->escape($this->div_id); ?>" />
        <input type="hidden" name="params[sections]" value="2" />
        <input type="hidden" name="tool" value="split-vertical" />
        <input type="hidden" name="params[multi_use]" value="<?php echo $this->escape($this->multi_use); ?>" />
        <input type="submit" class="submit no_fields" name="submit" value="Go" />
    </form>
</div>

<div class="block">
    <div class="image"><img src="/images/ribbon/template/vertical-splits-3.png" width="60" height="40" /></div>
    <div class="content">
        <div class="title">Three sections</div>
        <div class="text">Split the selected block into <strong>3</strong> 
        equal sections.</div>
    </div>
    <form action="/template/process/auto-tool" method="post">
        <input type="hidden" name="id" value="<?php echo $this->escape($this->div_id); ?>" />
        <input type="hidden" name="params[sections]" value="3" />
        <input type="hidden" name="tool" value="split-vertical" />
        <input type="hidden" name="params[multi_use]" value="<?php echo $this->escape($this->multi_use); ?>" />
        <input type="submit" class="submit no_fields" name="submit" value="Go" />
    </form>
</div>

<div class="block">
    <div class="image"><img src="/images/ribbon/template/vertical-splits-4.png" width="60" height="40" /></div>
    <div class="content">
        <div class="title">Four sections</div>
        <div class="text">Split the selected block into <strong>4</strong> 
        equal sections.</div>
    </div>
    <form action="/template/process/auto-tool" method="post">
        <input type="hidden" name="id" value="<?php echo $this->escape($this->div_id); ?>" />
        <input type="hidden" name="params[sections]" value="4" />
        <input type="hidden" name="tool" value="split-vertical" />
        <input type="hidden" name="params[multi_use]" value="<?php echo $this->escape($this->multi_use); ?>" />
        <input type="submit" class="submit no_fields" name="submit" value="Go" />
    </form>
</div>

<div class="block">
    <div class="image"><img src="/images/ribbon/template/vertical-splits-5.png" width="60" height="40" /></div>
    <div class="content">
        <div class="title">Five sections</div>
        <div class="text">Split the selected block into <strong>5</strong> 
        equal sections.</div>
    </div>
    <form action="/template/process/auto-tool" method="post">
        <input type="hidden" name="id" value="<?php echo $this->escape($this->div_id); ?>" />
        <input type="hidden" name="params[sections]" value="5" />
        <input type="hidden" name="tool" value="split-vertical" />
        <input type="hidden" name="params[multi_use]" value="<?php echo $this->escape($this->multi_use); ?>" />
        <input type="submit" class="submit no_fields" name="submit" value="Go" />
    </form>
</div>