<?php /** @var $this Dlayer_View_Codehinting */ ?>

<?php if($this->edit_mode == TRUE) { ?>
<script>
dlayer.preview.content.fn.headingText(
	<?php echo $this->data['preview']['heading']; ?>, '#params-heading');
dlayer.preview.content.fn.elementTextNoBr(
	<?php echo $this->data['preview']['sub_heading']; ?>, 
	'#params-sub_heading', true);
</script>
<?php } ?>

<div class="col-xs-12">
	<p class="dev-note bg-danger unsaved">Data has been modified!</p>
</div>

<div class="col-xs-12 small">
	<?php 
	if($this->data != FALSE) {
		echo $this->data['form'];
	}
	?>
</div>