<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div class="col-xs-12">
	<h3>Help <small>Add a heading content item to the content page</small></h3>	
	
	<p>This tool allows you to add a heading content item to the content page, 
		to add a heading content item you need to define the heading, an 
		optional sub heading, select the heading type to use and also a name 
		by which to identify it later, the name will only be visible to 
		you.</p>
	
	<p>A heading content item will be set to automatically span the entire 
		width of the content row. At any time, the width and position of the 
		heading content item can be managed via the size and position tab 
		when the tool is in edit mode, in edit mode you will also get access 
		to all the other sub tools.</p>
	
	<p>The styling options for the page heading and five content headings 
		are defined in the Content manager 
		<a href="/content/settings/headings">settings section</a>, although you 
		will be able override any of the styling options on a case by case 
		basis it makes sense where possible to make you changes within the 
		settings section so that your heading remain consistent across 
		your web site.</p>
</div>