<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div class="col-xs-12">
	<h3>Help <small>Create a new heading content item</small></h3>	
	
	<p>This tool allows you to add or edit a heading content item, to add a 
		heading content item you need to define the heading text, an internal 
		name to identity the text by, the heading type and optionally some sub 
		heading text. If defined the sub heading text will display after the 
		heading text in a smaller and lighter style.</p>
		
	<p>A heading content item will initially span the entire width of a 
		content row, the position and width of a heading can be modified 
		using the size and position sub tool when in edit mode.</p>
		
	<p class="dev-note bg-info">The styling for the heading types is defined 
		within the Content manager settings, although you can override the 
		styling on a per heading basis it makes much more sense to update the 
		base settings, this will ensure all your headings are consistent. 
		(Sub tools still in development)</p>
</div>