<?php /** @var $this Dlayer_View_Codehinting */ ?>

<?php if($this->edit_mode == TRUE) { ?>
<script>
dlayer.preview.content.fn.elementBackgroundColor(
	'<?php echo $this->data['preview']['container']; ?>', 
	'#params-container_background_color');
dlayer.preview.content.fn.elementBackgroundColor(
	'<?php echo $this->data['preview']['element']; ?>', 
	'#params-item_background_color');
</script>
<?php } ?>

<div class="col-xs-12">
	<p class="dev-note bg-danger unsaved">Data has been modified!</p>
</div>

<div class="col-xs-12 small">
<?php echo $this->colorPicker()->picker($this->color_picker_data['palettes'], 
	$this->color_picker_data['history'], TRUE, TRUE); ?>
</div>

<div class="col-xs-12 small">
<?php 
if($this->data != FALSE) {
	echo $this->data['form'];
}
?>
</div>

<?php echo $this->colorPicker()->javascript(); ?>