<?php /** @var Dlayer_View_Codehinting */ $this ?>

<div class="col-md-12 col-sm-12">
	<h3>Help <small>Move a content row to another content area</small></h3>
	
	<p>This tool allows you to move a content row from one area to another, 
		to move the content row simply select a content area from this list, 
		as you do the relevant area will highlight in the designer. Once you 
		have selected the area you want to move the row to click move.</p>
	
	<p>To move a content row within an area simple use the visual tools in 
		the designer when a content area has been selected.</p>
</div>

<div class="col-md-12 col-sm-12 further-reading">
	<?php echo $this->furtherReading('/#content-manager'); ?>
</div>
