<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div class="row">
	<div class="col-md-12 col-xs-12">
		<h1>Widget designer <small>Widget management</small></h1>

		<h3>Welcome to the Widget designer</h3>
		
		<p>Widgets are reusable content items or collections of reusable content items, some examples of widgets could be the header and menu for a web site, a twitter feed widget, an image gallery, a small call to action or even an entire blog system. </p>
		
		<p>A widget can be assigned to a template, content page, form or even another widget, there are no limits to the number of times a widget can be assigned to an item, be it a content page or a widget.</p>
		
		<p>There are two sections to the Widget designer, the designer and the library, the designer allows you to create or modify a widget, the library allows you to manager your entire library of widgets, you can organise your widgets, categorise them, copy them to create brand new widgets or delete them.</p>
			
		<h2>Actions <small>Widget designer actions</small></h2>
		
		<p><a href="#" class="btn btn-primary" disabled="disabled">Create widget</a></p>
		<p><a href="#" class="btn btn-primary" disabled="disabled">Go to widget library</a></p>
		
		<?php echo $this->furtherReading('the-designers/widget-designer/'); ?>
	</div>
</div>