<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div id="content">
    <h1>Widget designer</h1>
    
    <h2>Web site: <?php echo $this->escape($this->site['name']); ?></h2>
    
    <p>The widget designer allow you to create reusable blocks which are 
    called widgets.</p>
    
    <p>Widgets can be added to templates, content pages and even other widgets, 
    pretty much anything goes.</p>
    
    <p>The Widget designer is the most complex module within Dlayer, think of 
    it as a combination of the template designer and content manager.</p>
    
    <p>A widget can be anything you want, the header for your web site, the 
    footer, a menu, a widget is typically anything that you want to use in 
    more than one place.</p>    
</div>