<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div class="col-xs-12">
	<h3>Help <small>Create a new jumbotron item using existing 
		content</small></h3>
	
	<p>This tool allows you to create a new jumbotron content item using 
		existing content from an earlier jumbotron content item. Simply 
		select the content to import, a preview will be shown to allow you 
		to confirm that you are selecting the correct content.</p>
	
	<p>A jumbotron content item will initially span the entire width of a 
		content row, the position and width of a jumbotron can be modified 
		using the Size and Position sub tool when in edit mode.</p>
</div>