<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div class="col-xs-12">
	<h3>Help <small>Add a new category</small></h3>
	
	<p>This tool allows you to add a new category to the Image library or 
		edit the details for an existing category.</p>
		
	<p>Categories are used to assist with organising your images, you can 
		have as many categories as you like but there must be at least one 
		category in the Image library.</p>
</div>