<?php /** @var Dlayer_View_Codehinting */ $this ?>

<div class="col-xs-12">
	<h3>Help <small>Move selected page within site struture</small></h3>
	
	<p>Select the new parent for the page, once the page has been moved to 
		the new parent you can use the shift left and right controls to 
		change the order within the group.</p>
</div>

<div class="col-xs-12 further-reading">
	<?php echo $this->furtherReading('/#web-site-manager'); ?>
</div>
