<?php /** @var $this Dlayer_View_Codehinting */ ?>

<p>Select the new parent for the page from the list below.<p>

<p>The page will appear at the end of the grouping, you can then use the 
shift left and right controls to set the order within the page group.</p>

<ul>
	<li>Home page
		<ul>
			<li>Our projects</li>
			<li>Our development blog</li>
			<li>Site news</li>
			<li>Our products
				<ul>
					<li>Product 1</li>
					<li>Product 2</li>
					<li>Product 3</li>
				</ul>
			</li>
		</ul>
	</li>
</ul>