<?php /** @var Dlayer_View_Codehinting */ $this ?>

<div class="row">
	<div class="col-md-12 col-xs-12">
		<h1>Data manager <small>Define your datasets and data</small></h1>

		<h3>Welcome to the Data manager</h3>
		
		<p>Data is a set of values, a dataset is a collection of related 
			data.</p>
			
		<p>There are two sections to the Data manager, one which allows you 
			to define a dataset and one which allows you to create your data 
			using your dataset, the two pictures below show two datasets and 
			their possible data, view the Dataset designer and Data manager 
			previews to get a better understanding of how this section will 
			work.</p>
			
	</div>
	
	<div class="col-md-6 col-xs-12">
		<img class="img-responsive img-rounded" 
			src="/images/dlayer/dataset-1.JPG" width="253" height="135" 
			alt="Dataset 1">
		<p class="text-muted">A very simple dataset</p>
	</div>
	<div class="col-md-6 col-xs-12">
		<img class="img-responsive img-rounded" 
			src="/images/dlayer/dataset-2.JPG" width="686" height="208" 
			alt="Dataset 2">
		<p class="text-muted">A slight more complex dataset</p>
	</div>
			
	<div class="col-md-12 col-xs-12">
			
		<p class="dev-note bg-info">The Data manager preview is in development, 
			I'm currently working on getting the Dataset designer preview 
			working.</p>
			
	</div>
			
	<div class="col-md-12 col-xs-12">
			
		<h2>Datasets <small>All your data</small></h2>
		
		<p>Select a dataset from the list below, once selected you will be 
			able to either manage the data in the Data manager or edit the 
			dataset using the Dataset designer.</p>
			
		<p>
			<button disabled="disabled" type="button" class="btn btn-default btn-xs">Web pages</button>
			<a href="#" disabled="disabled" class="btn btn-default btn-xs">Dataset designer</a> 
			<a href="#" disabled="disabled" class="btn btn-default btn-xs">Data manager</a> 
			<span class="label label-success">Selected</span>
		</p>
		
		<p>
			<a href="#" disabled="disabled" class="btn btn-default btn-xs">Salutations</a> 
		</p>		
		
		<p><a href="" disabled="disabled" class="btn btn-primary">New dataset</a></p>
		
		<?php echo $this->furtherReading('the-designers/data-manager/'); ?>
	</div>
</div>