language: php
php:
  - '5.6'

notifications:
  email:
    recipients:
      - dean@g3d-development.com
    on_success: never # default: change
    on_failure: always # default: always

script: phpunit --bootstrap tests/Bootstrap.php tests
