<?php /** @var Dlayer_View_Codehinting */ $this ?>

<script language="javascript">
    <?php foreach($this->font_families as $k=>$values) { ?>
        <?php echo 'dlayer.settings.form.font_families' . 
        '[' . $k . '] = ' . '\'' . $values['css'] . '\'' . PHP_EOL; ?>
    <?php } ?>
   
    $(document).ready(function() 
    {
        dlayer.settings.form.fn.preview_font_families(
        <?php echo $this->escape($this->base_font_family['id']); ?>);
        
        $('.font_families').change(function() 
        {
            dlayer.settings.form.fn.preview_font_families(this.value);
        });
    });        
</script>

<div class="row">
	<div class="col-md-9 col-xs-12">
		<h1>Settings <small>Form builder <span class="label label-default">Site: <?php echo $this->escape($this->site['name']); ?></span></small></h1>
		
		<h2>Base font family <small>Default font for all text</small></h2>
		
		<p>Ideally the content on a web site will be consistently styled, 
			select a base font family using the select menu below, the 
			selected font will be used for all text within the Form builder 
			unless overridden by other settings.</p>
			
		<?php echo $this->form; ?>
		
		<h3>Font previews</h3>
			
			<p>The sentances below show what every letter of the alphabet 
				looks like in both upper and lower case for the font family you 
				have selected above.</p>
				
			<div class="font_preview">	        
		        <p class="switch dev-note bg-warning">
		        The quick brown fox jumps over the lazy dog. THE 
		        QUICK BROWN FOX JUMPS OVER THE LAZY DOG. The quick brown fox jumps 
		        over the lazy dog. THE QUICK BROWN FOX JUMPS OVER THE LAZY DOG. The 
		        quick brown fox jumps over the lazy dog. THE QUICK BROWN FOX JUMPS 
		        OVER THE LAZY DOG.</p>
		        
		        <p class="switch dev-note bg-warning">
		        The five boxing wizards jump quickly. THE FIVE 
		        BOXING WIZARDS JUMP QUICKLY. The five boxing wizards jump quickly. 
		        THE FIVE BOXING WIZARDS JUMP QUICKLY. The five boxing wizards jump 
		        quickly. THE FIVE BOXING WIZARDS JUMP QUICKLY.</p>
		        
		        <p class="switch dev-note bg-warning">
		        Fix problem quickly with galvanized jets. FIX PROBLEM 
		        QUICKLY WITH GALVANIZED JETS. Fix problem quickly with galvanized 
		        jets. FIX PROBLEM QUICKLY WITH GALVANIZED JETS. Fix problem quickly 
		        with galvanized jets. FIX PROBLEM QUICKLY WITH GALVANIZED JETS.</p>	        
	        </div>

	</div>
	<div class="col-md-3 col-xs-12">
		<ul class="list-unstyled settings-menu">
			<li>Dlayer
				<ul>
					<li><a href="/dlayer/settings/index">Overview</a></li>
					<li><a href="/dlayer/settings/palettes">Color palettes</a></li>
				</ul>
			</li>
			<li><strong>Content manager</strong>
				<ul>
					<li><a href="/content/settings/index">Overview</a></li>
					<li><a href="/content/settings/base-font-family">Base font family</a></li>
					<li><a href="/content/settings/headings">Headings</a></li>
				</ul>
			</li>
			<li>Form builder
				<ul>
					<li><a href="/form/settings/index">Overview</a></li>
					<li><a href="/form/settings/base-font-family" class="active">Base font family</a></li>
				</ul>
			</li>
		</ul>	
	</div>
</div>
<div class="row">
	<div class="col-md-12 col-xs-12 further-reading">
		<!--Need to upload content for settings-->
		<?php echo $this->furtherReading('/#settings', TRUE); ?>
	</div>
</div>
