<?php /** @var Dlayer_View_Codehinting */ $this ?>

<div class="row">
	<div class="col-md-9 col-xs-12">
		<h1>Settings <small>Form builder <span class="label label-default">Site: <?php echo $this->escape($this->site['name']); ?></span></small></h1>
				
		<h2>Overview</h2>
	    
	    <p>This section of the settings lets you modify all the settings 
	    	that relate to the Form builder.</p>
	    	
	    <ul>
	    	<li><a href="/form/settings/base-font-family">Base font family</a>: 
	    		Font style to use for content created in the Form builder.</li>
	    </ul>
	</div>
	<div class="col-md-3 col-xs-12">
		<ul class="list-unstyled settings-menu">
			<li>Dlayer
				<ul>
					<li><a href="/dlayer/settings/index">Overview</a></li>
					<li><a href="/dlayer/settings/palettes">Color palettes</a></li>
				</ul>
			</li>
			<li>Content manager
				<ul>
					<li><a href="/content/settings/index">Overview</a></li>
					<li><a href="/content/settings/base-font-family">Base font family</a></li>
					<li><a href="/content/settings/headings">Headings</a></li>
				</ul>
			</li>
			<li><strong>Form builder</strong>
				<ul>
					<li><a href="/form/settings/index" class="active">Overview</a></li>
					<li><a href="/form/settings/base-font-family">Base font family</a></li>
				</ul>
			</li>
		</ul>	
	</div>
</div>
<div class="row">
	<div class="col-md-12 col-xs-12 further-reading">
		<!--Need to upload content for settings-->
		<?php echo $this->furtherReading('/#settings', TRUE); ?>
	</div>
</div>
