<?php /** @var $this Dlayer_View_Codehinting */?>

<div class="row">
    <div class="col-md-12 col-xs-12">
        <h1>Content Manager <small>Content management</small></h1>

        <h2><span class="label label-default">Website: <?php echo $this->escape($this->site['name']); ?></span></small></h2>

        <h3>Quick introduction</h3>

        <p>Use the form below to create a new content page, you need to set a name which is visible within Dlayer and
            then define the page title and description which will be added to the HTML head.</p>
    </div>
</div>

<div class="row">
    <div class="admin-form col-md-6 col-sm-8 col-xs-12">
        <?php echo $this->form; ?>
    </div>
</div>

<div class="row">
    <div class="col-md-12 col-xs-12 further-reading">
        <?php echo $this->furtherReading(null, true); ?>
    </div>
</div>
