<?php /** @var $this Dlayer_View_Codehinting */?>

<?php echo $this->doctype(Zend_View_Helper_Doctype::HTML5) . PHP_EOL; ?>

<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title><?php echo $this->escape($this->layout()->title); ?></title>
		<meta name="application-name" content="Dlayer.com"/>
		<meta name="msapplication-TileColor" content="#FFFFFF"/>
		<meta name="msapplication-starturl" content="http://www.dlayer.com"/>
		<meta name="msapplication-tooltip" content="Dlayer.com: Web development simplified"/>
		<link rel="shortcut icon" href="<?php echo $this->baseUrl('images/favicon.ico'); ?>" />
		<link rel="icon" type="image/x-icon" href="<?php echo $this->baseUrl('images/favicon.ico'); ?>" />
		<link rel="icon" sizes="192x192" href="<?php echo $this->baseUrl('images/favicon-192x192.png'); ?>" />
		<script type="text/javascript" src="<?php echo $this->baseUrl('bower_components/jquery/dist/jquery.min.js'); ?>"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl('bower_components/jqueryui/jquery-ui.min.js'); ?>"></script>
		<link href="<?php echo $this->baseUrl('bower_components/jqueryui/themes/ui-lightness/jquery-ui.min.css'); ?>" rel="stylesheet" media="screen" type="text/css" />
		<link href="<?php echo $this->baseUrl('bower_components/bootstrap/dist/css/bootstrap.min.css'); ?>" rel="stylesheet">
		<script type="text/javascript" src="<?php echo $this->baseUrl('bower_components/bootstrap/dist/js/bootstrap.min.js'); ?>"></script>
		<script>
		var debug = <?php echo $this->layout()->debug; ?>;
		</script>
		<?php foreach($this->layout()->js_include as $include) { ?>
		<script type="text/javascript" src="<?php echo $this->baseUrl($include); ?>"></script>
		<?php } ?>
		<?php foreach($this->layout()->css_include as $include) { ?>
		<link href="<?php echo $this->baseUrl($include); ?>" rel="stylesheet" media="screen" type="text/css" />
		<?php } ?>
		<script>
		  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
              m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
          })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

          ga('create', 'UA-64736-8', 'auto');
          ga('send', 'pageview');

        </script>
	</head>
	<body>
		<?php echo $this->bootstrap3NavbarDlayer(
			'<img src="/images/dlayer/brand.jpg" width="25" height="25" alt="Brand" />',
            'http://www.dlayer.com', $this->layout()->nav['items'], 
			$this->layout()->nav['active_uri'], $this->layout()->preview_uri)->inverted()->containerClass('container-1170'); ?>
		<div class="container container-1170">
			<?php echo $this->layout()->content; ?>
		</div>
        <nav class="navbar navbar-default navbar-fixed-bottom">
            <div class="container container-1170">
                <?php if (count($this->layout()->control_bar) > 0) { ?>
                    <?php foreach($this->layout()->control_bar as $button) { ?>
                        <a href="<?php echo $this->escape($button['uri']); ?>" class="navbar-btn btn <?php echo $this->escape($button['class']); ?>"><?php echo $this->escape($button['name']); ?></a>
                    <?php } ?>
                <?php } ?>
                <?php if (count($this->layout()->control_bar_siblings) > 0) { ?>
                <div class="btn-group dropup">
                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Select sibling content items <span class="caret"></span></button>
                    <ul class="dropdown-menu">
                        <?php foreach($this->layout()->control_bar_siblings as $button) { ?>
                            <li><a href="<?php echo $this->escape($button['uri']); ?>"><?php echo $this->escape($button['name']); ?></a></li>
                        <?php } ?>
                    </ul>
                </div>
                <?php } ?>
                <?php foreach(array('layout', 'create', 'import') as $group) { ?>
                    <?php if (count($this->layout()->control_bar_tools[$group]) > 0) { ?>
                        <div class="btn-group dropup">
                            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <?php echo ucfirst($group); ?> tools <span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                <?php foreach($this->layout()->control_bar_tools[$group] as $button) { ?>
                                    <li><a href="<?php echo $this->escape($button['uri']); ?>"><?php echo $this->escape($button['name']); ?></a></li>
                                <?php } ?>
                            </ul>
                        </div>
                    <?php } ?>
                <?php } ?>
                <a href="#" class="pull-right visible-lg expand-ribbon navbar-btn btn btn-info"><span class="glyphicon glyphicon-indent-right" aria-hidden="true"></span>  Toggle ribbon</a>
            </div>
        </nav>
	</body>
</html>
