<?php /** @var $this Dlayer_View_Codehinting */ ?>

<?php echo $this->doctype(Zend_View_Helper_Doctype::HTML5) . PHP_EOL; ?>

<html lang="en">
	<head>
		<title><?php echo $this->escape($this->layout()->title); ?></title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<meta name="application-name" content="Dlayer.com"/>
		<meta name="msapplication-TileColor" content="#FFFFFF"/>
		<meta name="msapplication-starturl" content="http://www.dlayer.com"/>
		<meta name="msapplication-tooltip" content="Dlayer.com: Web development simplified"/>
		<link rel="shortcut icon" href="<?php echo $this->baseUrl('images/favicon.ico'); ?>" />
		<link rel="icon" type="image/x-icon" href="<?php echo $this->baseUrl('images/favicon.ico'); ?>" />
		<link rel="icon" sizes="192x192" href="<?php echo $this->baseUrl('images/favicon-192x192.png'); ?>" />
		<script type="text/javascript" src="<?php echo $this->baseUrl('plugins/jquery/jquery-1.10.2.min.js'); ?>"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl('plugins/jquery/ui-1.10.4/js/jquery-ui-1.10.4.custom.min.js'); ?>"></script>
		<link href="<?php echo $this->baseUrl('plugins/jquery/ui-1.10.4/css/ui-lightness/jquery-ui-1.10.4.custom.min.css'); ?>" rel="stylesheet" media="screen" type="text/css" />
		<link href="<?php echo $this->baseUrl('plugins/bootstrap-3.3.1/css/bootstrap.min.css'); ?>" rel="stylesheet">
		<script type="text/javascript" src="<?php echo $this->baseUrl('plugins/bootstrap-3.3.1/js/bootstrap.min.js'); ?>"></script>
		<script type="text/javascript">
		var debug = <?php echo $this->layout()->debug; ?>;
		</script>
		<?php foreach($this->layout()->js_include as $include) { ?>
		<script type="text/javascript" src="<?php echo $this->baseUrl($include); ?>"></script>
		<?php } ?>
		<?php foreach($this->layout()->css_include as $include) { ?>
		<link href="<?php echo $this->baseUrl($include); ?>" rel="stylesheet" media="screen" type="text/css" />
		<?php } ?>
		<script>
		  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

		  ga('create', 'UA-64736-3', 'dlayer.com');
		  ga('send', 'pageview');

		</script>
	</head>
	<body>
		<div id="fb-root"></div>
		<script>(function(d, s, id) {
		  var js, fjs = d.getElementsByTagName(s)[0];
		  if (d.getElementById(id)) return;
		  js = d.createElement(s); js.id = id;
		  js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.3";
		  fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));</script>
		<?php echo $this->bootstrapNavbarPreview('<img src="/images/dlayer/brand.jpg" width="25" height="25" alt="Brand" />', 
			$this->layout()->nav['items'],  
			$this->layout()->nav['active_url'], 
			$this->layout()->preview_url)->inverted(); ?>
		
		<div class="container-fixed">
			<?php echo $this->layout()->content; ?>
			
			<div class="row footer">
				<div class="col-md-12 col-xs-12">
					<p class="text-center"><small>Version 0.77.1 - Copyright &copy; 
					G3D Development Limited 2010-<?php echo date('Y'); ?> - 
					Dlayer 2008-<?php echo date('Y'); ?></small></p>
				</div>
				
				<div class="col-md-12 col-xs-12">
					<p class="text-center">
						<small>
						<a href="http://www.g3d-development.com/blog" 
							title="The G3D Development Limited blog">G3D Development Blog</a> - 
						<a href="http://www.deanblackborough.com/" 
							title="Dean Blackborough: My thoughts on anything and everything with a bias towards development">My blog</a> - 
						<a href="/dlayer/index/svn-release-policy" 
							title="Dlayer.com: Git development and release policy">Versioning & release policy</a> - 
						<a href="/dlayer/index/development-plan" 
							title="Dlayer.com: Development plan">Dev plan</a> - 
						<a href="/dlayer/index/development-log" 
							title="Dlayer.com: Development log">Dev log</a> - 
						<a href="/dlayer/index/bugs" 
							title="Dlayer.com: Bugs, past and present">Bugs</a> - 
						<a href="https://specification.dlayer.com">Current Specifcation <span class="glyphicon glyphicon-new-window" aria-hidden="true"></span></a>
						</small>
					</p>
				</div>
				<div class="col-md-6 col-xs-12 text-left">
					<a href="https://twitter.com/Dlayer_app" class="twitter-follow-button" data-show-count="false" data-show-screen-name="false">Follow @Dlayer_app</a> <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script> 
				</div>
				<div class="col-md-6 col-xs-12 text-right">
					<div class="fb-like" data-href="https://developers.facebook.com/docs/plugins/" data-layout="button" data-action="like" data-show-faces="false" data-share="false"></div>
				</div>
			</div>
		</div>
	</body>
</html>