<?php /** @var $this Dlayer_View_Codehinting */ ?>

<?php echo $this->doctype(Zend_View_Helper_Doctype::HTML5) . PHP_EOL; ?>

<html lang="en">
    <head>
        <title>Dlayer.com: Development</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <script type="text/javascript" src="<?php echo $this->baseUrl('plugins/jquery/jquery-1.10.2.min.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('plugins/jquery/ui-1.10.4/js/jquery-ui-1.10.4.custom.min.js'); ?>"></script>
        <link href="<?php echo $this->baseUrl('plugins/jquery/ui-1.10.4/css/ui-lightness/jquery-ui-1.10.4.custom.min.css'); ?>" rel="stylesheet" media="screen" type="text/css" />
        <link href="<?php echo $this->baseUrl('styles/app.css'); ?>" rel="stylesheet" media="screen" type="text/css" />        
    </head>
    <body>
        <div id="container">
            <div id="content">
                <?php echo $this->layout()->content; ?>
                
                <div><p><a href="/dev">Return to library development.</a></p></div>
            </div>
    </body>
</html>