<?php /** @var Dlayer_View_Codehinting */ $this ?>

<?php echo $this->doctype(Zend_View_Helper_Doctype::HTML5) . PHP_EOL; ?>

<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Dlayer.com: Error</title>
		<meta name="application-name" content="Dlayer.com: Error"/>
		<link rel="shortcut icon" href="<?php echo $this->baseUrl('images/favicon.ico'); ?>" />
		<link rel="icon" type="image/x-icon" href="<?php echo $this->baseUrl('images/favicon.ico'); ?>" />
		<link rel="icon" sizes="192x192" href="<?php echo $this->baseUrl('images/favicon-192x192.png'); ?>" />
		<script type="text/javascript" src="<?php echo $this->baseUrl('bower_components/jquery/dist/jquery.min.js'); ?>"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl('bower_components/jqueryui/jquery-ui.min.js'); ?>"></script>
		<link href="<?php echo $this->baseUrl('bower_components/jqueryui/themes/ui-lightness/jquery-ui.min.css'); ?>" rel="stylesheet" media="screen" type="text/css" />
		<link href="<?php echo $this->baseUrl('bower_components/bootstrap/dist/css/bootstrap.min.css'); ?>" rel="stylesheet">
		<script type="text/javascript" src="<?php echo $this->baseUrl('bower_components/bootstrap/dist/js/bootstrap.min.js'); ?>"></script>
		<link href="<?php echo $this->baseUrl('/css/dlayer.css'); ?>" rel="stylesheet">
		<script>
		  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
              m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
          })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

          ga('create', 'UA-64736-8', 'auto');
          ga('send', 'pageview');

        </script>
	</head>
	<body>
		<?php echo $this->bootstrap3Navbar(
            '<img src="/images/dlayer/brand.jpg" width="25" height="25" alt="Brand" />',
            'http://www.dlayer.com', $this->layout()->nav['items'], 
            $this->layout()->nav['active_uri'])->inverted()->containerClass('container-970'); ?>
		<div class="container-970">
			<div class="row">
				<div class="col-md-12 col-xs-12">
				    <h1>Oops!</h1>
					
                    <p>It appears as though you found an error, please 
						let me know at 
						<a href="https://github.com/Dlayer/dlayer/issues">GitHub</a> 
						by raising an issue, in the mean time why not 
						read the <a href="http://www.dlayer.com/docs">docs</a>.</p>
                        
                    <hr />

					<div class="panel panel-default">
						<div class="panel-heading">Error details</div>
							<div class="panel-body">
								<?php echo $this->layout()->content; ?>
							</div>
						</div>
					<div>
				</div>
			</div>
		</div>
	</body>
</html>
