<?php /** @var $this Dlayer_View_Codehinting */ ?>
<?php echo $this->doctype(Zend_View_Helper_Doctype::XHTML1_STRICT) . PHP_EOL; ?>

<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>Dlayer.com - Oops, an error occured!</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <script type="text/javascript" src="<?php echo $this->baseUrl('plugins/jquery/jquery-1.10.2.min.js'); ?>"></script>
        <link href="<?php echo $this->baseUrl('styles/app.css'); ?>" rel="stylesheet" media="" type="text/css" />
        <?php foreach($this->layout()->js_include as $include) { ?>
        <script type="text/javascript" src="<?php echo $this->baseUrl($include); ?>"></script>
        <?php } ?>
        <?php foreach($this->layout()->css_include as $include) { ?>
        <link href="<?php echo $this->baseUrl($include); ?>" rel="stylesheet" media="" type="text/css" />
        <?php } ?>
        <script>
		  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

		  ga('create', 'UA-64736-3', 'dlayer.com');
		  ga('send', 'pageview');

		</script>
		
		<style>
		header > h1 {
		    font-size: 7em;
		    text-align: center;
		    margin: 1em 0 1em 0;
		}
		</style>
    </head>
    <body>
        <div id="container">
        
        	<header>
        	<div class="top_nav">
        	<a href="/dlayer/index/index">Dlayer</a>
        	<a href="/dlayer/index/dlayer">What is Dlayer?</a>
        	<a href="/dlayer/index/dlayer-history">History of Dlayer</a>
        	<a href="/dlayer/index/development-plan">Devevelopment plan</a>
        	<a href="/dlayer/index/development-log">Devevelopment log</a>
        	<a href="/dlayer/index/bugs">Bugs</a>
        	</div>        
        
        	<h1>Dlayer.com</h1>
        	
        	</header>
        	
        	<?php echo $this->layout()->content; ?>
        
	        <div id="footer">
	        	<p>Copyright &copy; G3D Development Limited <?php echo date('Y'); ?></p>
	        
        		<p><a href="http://www.g3d-development.com/blog">G3D Development Blog</a> - 
        		<a href="/dlayer/index/development-plan">Development plan</a> - 
        		<a href="/dlayer/index/development-log">Development log</a> - 
        		<a href="/dlayer/index/svn-release-policy">SVN & release policy</a>
        		</p>
	        </div>
        </div>
    </body>
</html>