<?php /** @var $this Dlayer_View_Codehinting */ ?>

<?php echo $this->doctype(Zend_View_Helper_Doctype::HTML5) . PHP_EOL; ?>

<html lang="en">
	<head>
		<title>Dlayer.com: Error</title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<meta name="application-name" content="Dlayer.com: Error"/>
		<link rel="shortcut icon" href="<?php echo $this->baseUrl('images/favicon.ico'); ?>" />
		<link rel="icon" type="image/x-icon" href="<?php echo $this->baseUrl('images/favicon.ico'); ?>" />
		<link rel="icon" sizes="192x192" href="<?php echo $this->baseUrl('images/favicon-192x192.png'); ?>" />
		<script type="text/javascript" src="<?php echo $this->baseUrl('plugins/jquery/jquery-1.10.2.min.js'); ?>"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl('plugins/jquery/ui-1.10.4/js/jquery-ui-1.10.4.custom.min.js'); ?>"></script>
		<link href="<?php echo $this->baseUrl('plugins/jquery/ui-1.10.4/css/ui-lightness/jquery-ui-1.10.4.custom.min.css'); ?>" rel="stylesheet" media="screen" type="text/css" />
		<link href="<?php echo $this->baseUrl('plugins/bootstrap-3.3.1/css/bootstrap.min.css'); ?>" rel="stylesheet">
		<script type="text/javascript" src="<?php echo $this->baseUrl('plugins/bootstrap-3.3.1/js/bootstrap.min.js'); ?>"></script>
		<link href="<?php echo $this->baseUrl('/css/dlayer.css'); ?>" rel="stylesheet">
		<script>
		  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

		  ga('create', 'UA-64736-3', 'dlayer.com');
		  ga('send', 'pageview');

		</script>
	</head>
	<body>
		<nav class="navbar navbar-inverse" role="navigation">
			<div class="container">
			<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-navbar-collapse-1">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="/">Dlayer.com</a>
			</div>
			<div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
			<ul class="nav navbar-nav">
			<li class="active"><a href="/dlayer/index/index" title="Dlayer.com: Web development simplified">Dlayer <span class="sr-only">(current)</span></a></li>
			<li><a href="/dlayer/index/dlayer" title="What is Dlayer">What is Dlayer?</a></li>
			<li><a href="/dlayer/index/dlayer-history" title="How Dlayer came to be">History of Dlayer</a></li>
			<li><a href="/dlayer/index/development-plan" title="Dlayer development plan">Development plan</a></li>
			<li><a href="/dlayer/index/development-log" title="Dlayer development log">Development log</a></li>
			<li><a href="/dlayer/index/bugs" title="Dlayer known bugs">Bugs</a></li>
			</ul>
			</div><!-- /.navbar-collapse -->
			</div><!-- /.container-fluid -->
			</nav>
		<div class="container">
		
			<div class="row">
				<div class="col-xs-12">
				
					<div class="jumbotron">
						<h1>Sorry <small>something bad happened</small></h1>
						<p>There appears to have been an error processing 
							your request, please try again. If that doesn't 
							work the event has been logged and I will try to 
							fix the issue as soon as possible.</p>
							
						<p>In the mean time why not read the specification 
							for Dlayer on 
							<a href="http://www.g3d-development.com">G3D Development.com</a>.</p>
							
						 <p><a class="btn btn-primary" 
							href="http://www.g3d-development.com/blog/specification/" 
							role="button">Specification</a></p>
					</div>
					
					<div class="panel panel-default">
						<div class="panel-heading">Error details</div>
							<div class="panel-body">
								<?php echo $this->layout()->content; ?>
							</div>
						</div>
					<div>
				</div>
			</div>			
			
			<div class="row footer">
				<div class="col-md-12 col-xs-12">
					<p class="text-center"><small>Version 0.67 - Copyright &copy; 
					G3D Development Limited 2010-<?php echo date('Y'); ?> - 
					Dlayer 2010-<?php echo date('Y'); ?></small></p>
				</div>
				
				<div class="col-md-12 col-xs-12">
					<p class="text-center">
						<small>
						<a href="http://www.g3d-development.com/blog" 
							title="The G3D Development Limited blog">G3D Development Blog</a> - 
						<a href="/dlayer/index/development-plan" 
							title="Dlayer.com: Development plan">Dev plan</a> - 
						<a href="/dlayer/index/development-log" 
							title="Dlayer.com: Development log">Dev log</a> - 
						<a href="/dlayer/index/bugs" 
							title="Dlayer.com: Bugs, past and present">Bugs</a> - 
						<a href="/dlayer/index/svn-release-policy" 
							title="Dlayer.com: Git development and release policy">Versioning & release policy</a>
						</small>
					</p>
				</div>
			</div>
		</div>
	</body>
</html>