<?php /** @var $this Dlayer_View_Codehinting */ ?>

<?php echo $this->doctype(Zend_View_Helper_Doctype::HTML5) . PHP_EOL; ?>

<html lang="en">
	<head>
		<title><?php echo $this->escape($this->layout()->title); ?></title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<script type="text/javascript" src="<?php echo $this->baseUrl('plugins/jquery/jquery-1.10.2.min.js'); ?>"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl('plugins/jquery/ui-1.10.4/js/jquery-ui-1.10.4.custom.min.js'); ?>"></script>
		<link href="<?php echo $this->baseUrl('plugins/jquery/ui-1.10.4/css/ui-lightness/jquery-ui-1.10.4.custom.min.css'); ?>" rel="stylesheet" media="screen" type="text/css" />
		<link href="<?php echo $this->baseUrl('plugins/bootstrap-3.3.1/css/bootstrap.min.css'); ?>" rel="stylesheet">
		<script type="text/javascript" src="<?php echo $this->baseUrl('plugins/bootstrap-3.3.1/js/bootstrap.min.js'); ?>"></script>
		<script type="text/javascript">
		var debug = <?php echo $this->layout()->debug; ?>;
		</script>
		<?php foreach($this->layout()->js_include as $include) { ?>
		<script type="text/javascript" src="<?php echo $this->baseUrl($include); ?>"></script>
		<?php } ?>
		<?php foreach($this->layout()->css_include as $include) { ?>
		<link href="<?php echo $this->baseUrl($include); ?>" rel="stylesheet" media="screen" type="text/css" />
		<?php } ?>
		<script>
		  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

		  ga('create', 'UA-64736-3', 'dlayer.com');
		  ga('send', 'pageview');

		</script>
	</head>
	<body>
		<?php echo $this->bootstrapNavbar('Dlayer.com', 
			$this->layout()->nav['items'],  
			$this->layout()->nav['active_url'])->inverted(); ?>
		<div class="container-fixed">
			<?php echo $this->layout()->content; ?>
			
			<div class="row footer">
				<div class="col-md-12 col-xs-12">
					<p class="text-center"><small>Version 0.59.1 - Copyright &copy; 
					G3D Development Limited 2010-<?php echo date('Y'); ?> - 
					Dlayer 2010-<?php echo date('Y'); ?></small></p>
				</div>
				
				<div class="col-md-12 col-xs-12">
					<p class="text-center">
						<small>
						<a href="http://www.g3d-development.com/blog">G3D Development Blog</a> - 
						<a href="/dlayer/index/development-plan">Development plan</a> - 
						<a href="/dlayer/index/development-log">Development log</a> - 
						<a href="/dlayer/index/svn-release-policy">SVN & release policy</a>
						</small>
					</p>
				</div>
			</div>
		</div>
	</body>
</html>