<?php /** @var $this Dlayer_View_Codehinting */ ?>

<?php echo $this->doctype(Zend_View_Helper_Doctype::HTML5) . PHP_EOL; ?>

<html lang="en">
    <head>
        <title><?php echo $this->escape($this->layout()->title); ?></title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <script type="text/javascript" src="<?php echo $this->baseUrl('plugins/jquery/jquery-1.10.2.min.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('plugins/jquery/ui-1.10.4/js/jquery-ui-1.10.4.custom.min.js'); ?>"></script>
        <link href="<?php echo $this->baseUrl('plugins/jquery/ui-1.10.4/css/ui-lightness/jquery-ui-1.10.4.custom.min.css'); ?>" rel="stylesheet" media="screen" type="text/css" />
        <link href="<?php echo $this->baseUrl('styles/app.css'); ?>" rel="stylesheet" media="screen" type="text/css" />
        <script type="text/javascript">
        var debug = <?php echo $this->layout()->debug; ?>;
        </script>
        <?php foreach($this->layout()->js_include as $include) { ?>
        <script type="text/javascript" src="<?php echo $this->baseUrl($include); ?>"></script>
        <?php } ?>
        <?php foreach($this->layout()->css_include as $include) { ?>
        <link href="<?php echo $this->baseUrl($include); ?>" rel="stylesheet" media="screen" type="text/css" />
        <?php } ?>
        <script>
		  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

		  ga('create', 'UA-64736-3', 'dlayer.com');
		  ga('send', 'pageview');

		</script>
    </head>
    <body>
        <div id="container">
        <?php echo $this->navigation($this->layout()->nav['class'], 
        $this->layout()->nav['items'], $this->layout()->nav['active_url']); ?>
        <?php echo $this->layout()->content; ?>
        
	        <div id="footer">
	        	<p>Version 0.36 - Copyright &copy; G3D Development Limited <?php echo date('Y'); ?></p>
	        
        		<p><a href="http://www.g3d-development.com/blog">G3D Development Blog</a> - 
        		<a href="/dlayer/index/development-plan">Development plan</a> - 
        		<a href="/dlayer/index/development-log">Development log</a> - 
        		<a href="/dlayer/index/svn-release-policy">SVN & release policy</a>
        		</p>
	        </div>
        </div>
    </body>
</html>