<script>
</script>

<div class="form-group ip-category">
	<label for="ip-category" class="required">Category</label>
	<select name="ip-category" id="ip-category" class="form-control input-sm">
		<option value="null">Select category</option>
		<option value="1">Category 1</option>
		<option value="2">Category 2</option>
	</select>
	<p class="help-block">Select a category from your Image 
		library to show sub categories.</p>
</div>