<script>
dlayerDesigner.imagePicker.setSelectedCategory();
</script>

<div class="form-group">
	<label for="category-selector" class="required">Category</label>
	<select name="category-selector" class="form-control input-sm category-selector">
		<?php foreach($this->categories as $id=>$label) { ?>
		<option value="<?php echo $this->escape($id); ?>"><?php echo $this->escape($label); ?></option>
		<?php } ?>
	</select>
	<p class="help-block">Select a category from your Image library to show sub categories.</p>
</div>
