<script>
dlayerDesigner.imagePicker.clearSelectedSubCategory();
</script>

<h4>Sub category: <small title="<?php echo $this->escape($this->sub_category['number_of_images']); ?> images in sub category/categories"><?php echo $this->escape($this->sub_category['name']); ?> <span class="badge"><?php echo $this->escape($this->sub_category['number_of_images']); ?></span></small> 
<span class="glyphicon glyphicon-remove clear-selected-sub-category pull-right" title="Clear sub category" aria-hidden="true"></span></h4>
	
<hr />
