<script>
</script>

<div class="image-list">
	<h4>Images <small>Images for the selected category and 
		sub category</small></h4>
	
	<div class="row" style="padding-bottom: 10px;">
		<div class="col-xs-12">
			<div class="btn-toolbar">
				<div class="btn-group btn-group-xs" role="group" aria-label="...">
					<a title="Sorted by name" href="#" class="btn btn-primary">Name</a>
					<a title="Sort by size" href="#" class="btn btn-default">Size</a>
					<a title="Sort by date uploaded to library" href="#" class="btn btn-default">Uploaded</a>
				</div>
				<div class="btn-group btn-group-xs" role="group" aria-label="...">
					<a title="Display in ascending order" href="#" class="btn btn-default">Asc.</a>
					<a title="Displayed in descending order" href="#" class="btn btn-primary">Desc.</a>
				</div>
			</div>
		</div>
	</div>

	<div class="row" style="padding-bottom: 10px;">
		<div class="col-xs-4">
		<img src="/images/library/1/1.jpg" title="Autumn path" alt="Image library image" width="160" height="120" class="img-thumbnail">
		</div>
		<div class="col-xs-8">
			<p>
				<strong>Name:</strong> Autumn path<br />
				<strong>Dimenisons:</strong> 615 X 453 pixels<br />
				<strong>Size:</strong> 169.4 kb
			</p>
		</div>
		<div class="col-xs-12 text-right">
			<div class="btn-group btn-group-xs" role="group" aria-label="...">
				<button type="button" class="btn btn-primary">Select</button>
				<button type="button" class="btn btn-default">View versions</button>
			</div>
		</div>
	</div>
	
	<div class="row" style="padding-bottom: 10px;">
		<div class="col-xs-4">
		<img src="/images/library/7/23.jpg" title="Spring coffee" alt="Image library image" width="160" height="120" class="img-thumbnail">
		</div>
		<div class="col-xs-8">
			<p>
				<strong>Name:</strong> Spring coffee<br />
				<strong>Dimenisons:</strong> 561 X 367 pixels<br />
				<strong>Size:</strong> 41.6 kb
			</p>
			</div>
		<div class="col-xs-12 text-right">
			<div class="btn-group btn-group-xs" role="group" aria-label="...">
				<button type="button" class="btn btn-primary">Select</button>
				<button type="button" class="btn btn-default" disabled="disabled">View versions</button>
			</div>
		</div>
	</div>
	
	<div class="row" style="padding-bottom: 10px;">
		<div class="col-xs-4">
		<img src="/images/library/5/5.jpg" title="Spring coffee" alt="Image library image" width="160" height="120" class="img-thumbnail">
		</div>
		<div class="col-xs-8">
			<p>
				<strong>Name:</strong> Robin<br />
				<strong>Dimenisons:</strong> 615 X 407 pixels<br />
				<strong>Size:</strong> 32.0 kb
			</p>
		</div>
		<div class="col-xs-12 text-right">
			<div class="btn-group btn-group-xs" role="group" aria-label="...">
				<button type="button" class="btn btn-primary">Select</button>
				<button type="button" class="btn btn-default" disabled="disabled">View versions</button>
			</div>
		</div>
	</div>
</div>