<script>
</script>

<div class="form-group ip-sub-category">
	<label for="ip-sub-category" class="required">Sub category</label>
	<select name="ip-sub-category" id="ip-sub-category" class="form-control input-sm">
		<option value="null">Select sub category</option>
		<option value="1">Sub category 1</option>
		<option value="2">Sub category 2</option>
		<option value="0">All</option>
	</select>
	<p class="help-block">Select a sub category to list the images 
		defined in the selected category and sub category.</p>
</div>