<script>
dlayer.designers.imagePickerClearImage();
</script>

<h4>Image: <small title="<?php echo $this->escape($this->image['number_of_versions']); ?> image versions">
	<?php echo $this->escape($this->image['name']); ?> 
	<span class="badge"><?php echo $this->escape($this->image['number_of_versions']); ?></span></small> 
	<span class="glyphicon glyphicon-remove clear-image-picker-value clear-image-picker-image" 
	title="Clear image" aria-hidden="true"></span></h4>
	
<hr />

<div class="version-list">
	<h4>Versions <small>Select a version of this image from the list 
		below</small></h4>

	<div class="row" style="padding-bottom: 10px;">
		<div class="col-xs-4">
		<img src="/images/library/1/1.jpg" title="Autumn path" alt="Image library image" width="160" height="120" class="img-thumbnail">
		</div>
		<div class="col-xs-8">
			<p>
				<strong>Name:</strong> Autumn path<br />
				<strong>Dimenisons:</strong> 615 X 453 pixels<br />
				<strong>Size:</strong> 169.4 kb
			</p>
		</div>
		<div class="col-xs-12 text-right">
			<div class="btn-group btn-group-xs" role="group" aria-label="...">
				<button type="button" class="btn btn-primary">Select</button>
			</div>
		</div>
	</div>
	
	<div class="row" style="padding-bottom: 10px;">
		<div class="col-xs-4">
		<img src="/images/library/7/23.jpg" title="Spring coffee" alt="Image library image" width="160" height="120" class="img-thumbnail">
		</div>
		<div class="col-xs-8">
			<p>
				<strong>Name:</strong> Spring coffee<br />
				<strong>Dimenisons:</strong> 561 X 367 pixels<br />
				<strong>Size:</strong> 41.6 kb
			</p>
			</div>
		<div class="col-xs-12 text-right">
			<div class="btn-group btn-group-xs" role="group" aria-label="...">
				<button type="button" class="btn btn-primary">Select</button>
			</div>
		</div>
	</div>
</div>