<?php /** @var Dlayer_View_Codehinting */ $this ?>

<div class="col-xs-12">
	<h3>Help <small>Options</small></h3>
	
	<p>This tool allows you to set the options for your form, these options 
		control how the form will function.</p>
		
	<h4>Options:</h4>
	
	<ul>
		<li><strong>HTTP method:</strong> The HTTP method to use for form 
            submission, either POST or GET.</li>
		<li><strong>Custom URL:</strong> A custom URL to submit the form 
			to, if blank Dlayer will handle the submissions.</li>
		<li><strong>Lock:</strong> If a form is locked it can only be modified 
            by the owner.</li>
	</ul>
</div>

<div class="col-xs-12 further-reading">
    <?php echo $this->furtherReading('/#form-builder'); ?>
</div>
