<?php /** @var $this Dlayer_View_Codehinting */ ?>

<h2>Set form settings</h2>

<p>This tool allows you to define some base settings for the form, these 
settings affect the form as a whole, where relevant these settings can be 
overridden at the form field level.</p>

<p>You can define the minimum display width for a form, the rest of the app
 will respect this value, it will be impossible to import a form into a 
 container that is smaller than the minimum width.</p>
 
 <p>You can define the text for the field set legend.</p>
 
 <p>You can define the text to use for the forms submit button.</p>