<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div class="col-xs-12">
	<h3>Settings <small>Set options for the form</small></h3>
	
	<p>This tool allows you to define some base settings for the form, these 
		settings affect the form as a whole, where relevant these settings 
		can be overridden at the form field level.</p>

	<p>You can define the minimum display width for a form, the rest of the 
		app will respect this value, it will be impossible to import a form 
		into a container that is smaller than the minimum width.</p>
		
	<p class="dev-note bg-danger">The form width setting doesn't currently 
		have any impact on the form display or ability to import, this will be 
		update as development continues, it was part of the pre-Bootstrap 
		app.</p>

	<p>You can define the text for the fieldset legend.</p>

	<p>You can define the text to use for the forms submit button.</p>
</div>