<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div class="row">
	<div class="col-md-12 col-xs-12">
		<h1>Web site manager <small>Relationship and Data management</small></h1>
	</div>

	<div class="col-md-12 col-xs-12">
		<h2>Web site 
		<small><?php echo $this->escape($this->site['name']); ?></small></h2>
	</div>

	<div class="col-md-12 col-xs-12">
		<p>The Web site manager is where you define the relationships between 
			all your content pages to create the structure of your web 
			site.</p>
			
		<p>When a new content page is created, either in the Content manager 
			or here in the Widget designer it will initially be placed in an 
			un-assigned pages bucket, from there you can assign its parent 
			and relationship to its siblings.</p>
			
		<p>There are no real restrictions on how your web site structure 
			needs to be defined other than there must be one page that acts as 
			the homepage and a page can have either one or no parents.</p>
		
		<p>Changes to content pages need to be made within the Content 
			manager, you can however at any point jump to the Content manager 
			to make changes and then return easily to the Web site manager 
			where your current state will have been maintained.</p>
			
		<p class="dev-note bg-info">The Web site manager is currently just a 
			preview, I'm still working on the design and functionality, I 
			need complete more of the Template designer, Content manager 
			and Widget designer before I can commit to adding functionality 
			to the Web site manager. The preview is here to give you an idea 
			of how I intend it to work.</p>
			
		<h2>Options <small>Web site management options</small></h2>
		
		<p>
			<a href="/website/design/index/" class="btn btn-primary">
				Go to page management</a>
		</p>
	</div>
</div>