<?php /** @var Dlayer_View_Codehinting */ $this ?>

<div class="col-xs-12">		
	<h3>Help <small>Move a content item to another content row</small></h3>
	
	<p>This tool allows you to move a content item from one row to another, 
		to move the content item simply select a content row from this list, 
		as you do the relevant row will highlight in the designer. Once you 
		have selected the row you want to move the item to click move.</p>
	
	<p>To move a content item within an row simple use the visual tools in 
		the designer when a content row has been selected.</p>
</div>