<?php /** @var $this Dlayer_View_Codehinting */ ?>

<h2>Create a name form field</h2>

<p>This tool allows you to quickly add a name field to your form, the name 
field is just a single line field with the values preset, in addition to 
setting the initial values this tool also sets validation settings.</p>

<p>To add the name field to your form simply click save, if required you can 
change the preset values.</p>

<p>The name field can be edited as per a standard single line text field.</p>