<?php /** @var Dlayer_View_Codehinting */ $this ?>

<div id="content">
    <h1>Library development</h1>
    
    <h2>Advanced thumbnail generator</h2>
    
    <p>Generates a thumbnail for the supplied image, thumbnail options are all 
    configurable, in this instance we are maintaining the aspect ratio, using a 
    blue canvas color, setting the quality of the saved image to 100, saving 
    the image in the same directory as the source image with a suffix of 
    -thumb and creating a thumbnail which is 200 * 120 pixels</p>
    
    <p>Call the process to method to generate the thumbnail, any errors will 
    be shown, if no errors return and then click the view button to see the 
    newly generated thumbnail.</p>
    
    <p>This <a href="/images/testing/thumbnail-advanced/test.jpg">test image</a> will be 
    used by the resizer.</p>
    
    <ul>
        <li><a href="/dev/thumbnail-advanced/process">Process</a> - 
        Call the thumbnail generator.</li>
        <?php if(file_exists('images/testing/thumbnail-advanced/test-thumb.jpg') == TRUE) { ?>
        <li><a href="/images/testing/thumbnail-advanced/test-thumb.jpg">View</a> - View generated image</li>
        <li><a href="/dev/thumbnail-advanced/delete">Delete</a> - Delete the generated thumbnail.</li>
        <?php } ?>
    </ul>
</div>