<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div class="col-xs-12">
	<h3>Help <small>Add a new image to the library</small></h3>
	
	<p>This tool allows you to add a new image to the Image library for the 
		currently selected web site, once in the Image library the image can 
		be used by any tool that uses an image.</p>
	
	<p>Within the Image library you can make many modifications to the image 
		including cropping and creating a copy.</p>
</div>