<?php /** @var Dlayer_View_Codehinting */ $this ?>

<div class="col-md-12 col-sm-12">
	<h3>Page selected</h3>
			
	<h5><span class="glyphicon glyphicon-play" aria-hidden="true"></span>
	Add a new row</h5>

	<h5><span class="glyphicon glyphicon-play" aria-hidden="true"></span>
	Select a row</h5>
	
	<h5><span class="glyphicon glyphicon-play" aria-hidden="true"></span>
	Edit the page</h5>

	<p>To add a new row please selected the row tool.</p>

	<p>If a row is selectable it will highlight when you hover over it it, to select the row click the
		left mouse button.</p>

	<p>To edit the page select a tab from above.</p>
</div>
