<?php /** @var Dlayer_View_Codehinting */ $this ?>

<div class="col-md-12 col-sm-12">
	<h3>Page selected</h3>
			
	<h5><span class="glyphicon glyphicon-play" aria-hidden="true"></span>
	Add a row</h5>

	<h5><span class="glyphicon glyphicon-play" aria-hidden="true"></span>
	Select a row</h5>
	
	<h5><span class="glyphicon glyphicon-play" aria-hidden="true"></span>
	Edit the page</h5>

	<p>To add a new row please select the 'add row' tool.</p>

	<p>If a row is selectable it will highlight when you hover your cursor over it, to select the row, click.</p>

	<p>To edit the properties for the page select a tab above.</p>
</div>
