<?php /** @var $this Dlayer_View_Codehinting */ ?>

<?php echo $this->colorPicker()->picker($this->color_picker_data['palettes'], 
$this->color_picker_data['history']); ?>

<div class="block">
    <div class="content">
        <div class="text">Set the background colour of the block to your 
        selected colour</div>
    </div>
    
    <?php 
    if($this->data['color_hex'] == FALSE) {
		$color = NULL;
    } else {
		$color = $this->data['color_hex'];
    }
    ?>
    
    <form action="/template/process/auto-tool" method="post">
        <input type="hidden" name="id" 
        value="<?php echo $this->escape($this->div_id); ?>" />
        <input type="hidden" id="color_hex" name="params[color_hex]" 
        size="7" maxlength="7" value="<?php echo $this->escape($color); ?>" />
        <input type="hidden" name="params[multi_use]" 
        value="<?php echo $this->escape($this->multi_use); ?>" />
        <div class="color_picker" id="picker_color_hex" 
        style="background-color:<?php echo $this->escape($color); ?>;">&nbsp;</div>
        <input type="hidden" name="tool" value="background-color" />
        <input type="submit" class="submit no_fields" name="submit" value="Go" />
    </form>
</div>

<?php echo $this->colorPicker()->javascript(); ?>