<?php /** @var $this Dlayer_View_Codehinting */ ?>

<?php if($this->data != FALSE) { ?>
    <?php foreach($this->data as $color) { ?>
<div class="block">
    <div class="image" style="background-color:<?php echo $this->escape($color['color_hex']); ?>;">&nbsp;</div>
    <div class="content">
        <div class="title"><?php echo $this->escape($color['type']); ?> colour</div>
        <div class="text">Set the background colour of the block to '<?php echo $this->escape($color['name']); ?>'.</div>
    </div>
    <form action="/template/process/auto-tool" method="post">
        <input type="hidden" name="id" value="<?php echo $this->escape($this->div_id); ?>" />
        <input type="hidden" name="params[color_hex]" value="<?php echo $this->escape($color['color_hex']); ?>" />
        <input type="hidden" name="params[multi_use]" value="<?php echo $this->escape($this->multi_use); ?>" />
        <input type="hidden" name="tool" value="background-color" />
        <input type="submit" class="submit no_fields" name="submit" value="Go" />
    </form>
</div>
    <?php } ?>
<div class="block">
    <div class="image">&nbsp;</div>
    <div class="content">
        <div class="title">None</div>
        <div class="text">Clear the currently set background colour.</div>
    </div>
    <form action="/template/process/auto-tool" method="post">
        <input type="hidden" name="id" value="<?php echo $this->escape($this->div_id); ?>" />
        <input type="hidden" name="params[color_hex]" value="none" />
        <input type="hidden" name="tool" value="background-color" />
        <input type="submit" class="submit no_fields" name="submit" value="Go" />
    </form>
</div>
<?php } else { ?>
<h2>Error</h2>

<p>There was an error pulling the colours that you assigned for your palette, 
please go back to the settings and check that you assigned three colours to the 
palette.</p>
<?php } ?>