<?php /** @var $this Dlayer_View_Codehinting */ ?>
<style>
#design > div.builder-form * {
	font-family: <?php echo $this->base_font_family; ?>;
}

<?php foreach ($this->field_styles as $field_id => $styles) {
	if(count($styles) > 0) {
		echo '#design .row_' . $field_id . " {\r\n";
		foreach($styles as $style) {
			echo $style . "\r\n";
		}
	echo "}\r\n";
	}
} 
?>
</style>

<div class="row">
	<div class="col-md-8">
		<p class="dev-note bg-info"><strong>Note:</strong> Your form will not 
			be this size when imported into the Content manager or Widget 
			designer, it will automatically size itself to fill the container 
			it is placed into, use the buttons to the right to see how your 
			form displays at different sizes</p>
	</div>
	
	<script>
	$('.set-form-display-size a').on('click', function() {
		
	});
	</script>
	
	<div class="col-md-4">
		<p><strong>Test widths</strong></p>
		<div class="btn-group set-form-display-size">
			<a title="" href="#" id="size-12" class="btn btn-primary btn-sm">Full width</a>
			<a title="" href="#" id="size-6" class="btn btn-default btn-sm">Half width</a>
			<a title="" href="#" id="size-3" class="btn btn-default btn-sm">Quarter width</a>
		</div>	
	</div>
</div>

<div class="builder-form">
	<?php echo $this->form; ?>
</div>