<?php /** @var $this Dlayer_View_Codehinting */ ?>
<style>
div.builder-form * {
	font-family: <?php echo $this->base_font_family; ?>;
}

<?php foreach ($this->field_styles as $field_id => $styles) {
	if(count($styles) > 0) {
		echo 'div.builder-form .row_' . $field_id . " {\r\n";
		foreach($styles as $style) {
			echo $style . "\r\n";
		}
	echo "}\r\n";
	}
} 
?>
</style>

<div class="builder-form">
	<h3>
	<?php 
		echo $this->escape($this->titles['title']);
		if(strlen($this->titles['sub_title']) > 0) {
			echo ' <small>' . $this->escape($this->titles['sub_title']) . 
				'</small>';
		}
	
	?>
	</h3>
	<?php echo $this->form; ?>
</div>