<?php /** @var $this Dlayer_View_Codehinting */?>

<style>
	<?php
	foreach ($this->row_styling as $group => $styling) {
		foreach ($styling as $field_id => $style) {
			echo 'div.row_' . $field_id . ' {' . PHP_EOL;
			echo $group . ': ' . $style . ';' . PHP_EOL;
			echo '}' . PHP_EOL;
		}
	}
	?>
</style>

<div class="form-builder">
    <h2><?php echo $this->escape($this->layout_options['title']); ?>
    <?php if (strlen($this->layout_options['subtitle']) > 0) { echo ' <small>' . $this->escape($this->layout_options['subtitle'])  . '</small>'; } ?></h2>
    <?php echo $this->form; ?>
</div>
