<?php /** @var $this Dlayer_View_Codehinting */?>

<div id="designer">
    <div class="row">
        <div class="col-lg-9 design designer-left">
            <?php echo $this->design_html; ?>
        </div>
        <div class="col-lg-3 designer-right">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 ribbon">
                    <?php if(strlen($this->ribbon) > 0)
                    {
                        echo $this->ribbon;
                    }
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function()
    {
        formBuilder.fieldSelector();
        formBuilder.fieldMover();
        formBuilder.setPreviewAtWidth();
        dlayerDesigner.expandRibbon();
    });
</script>
