<?php /** @var Dlayer_View_Codehinting */ $this ?>

<script type="text/javascript">
$(document).ready(function() 
	{
		<?php if($this->field_id == NULL && $this->tool == NULL) { ?>			
			dlayer.movers.formFields();
		<?php } ?>
		
		dlayer.selectors.form();
			
		// Toggles for tools section
		$('div.tools h5').click(
			function() 
			{
				var selector = this.className;
				$('div.' + selector).toggle();
				
				if($('h5.' + selector + ' > span').hasClass('glyphicon-minus')) {
					$('h5.' + selector + ' > span').removeClass('glyphicon-minus');
					$('h5.' + selector + ' > span').addClass('glyphicon-plus');
				} else {
					$('h5.' + selector + ' > span').removeClass('glyphicon-plus');
					$('h5.' + selector + ' > span').addClass('glyphicon-minus');
				}
			}
		)
		
		<?php if($this->tool == FALSE) { ?>
		$('div.tools h4.tool-row-4').trigger('click');
		<?php } else { ?>
		<?php if(in_array($this->tool, array('text', 'password', 'textarea', 'email')) == FALSE) { ?>
		$('div.tools h4.tool-row-4').trigger('click');
		<?php } ?>
		<?php } ?>
});
</script>

<div id="designer">	
    <div class="row">
    	<div class="col-lg-9 col-md-12 col-sm-12 col-xs-12 design">
    		<?php echo $this->dlayer_form; ?>
    	</div>
    	<div class="col-lg-3 col-md-12">
    		<div class="row">
    			<div class="col-lg-12 col-md-8 col-sm-8 col-xs-12 ribbon">
    				<?php echo $this->dlayer_ribbon; ?>
    			</div>
    			
    			<div class="col-lg-12 col-md-4 col-sm-4 col-xs-12 tools">
    				<div class="well well-sm">    			
    					<?php echo $this->dlayer_toolbar; ?>
    				</div>
    			</div>
    		</div>    		
    	</div>
    </div>
</div>