<?php /** @var $this Dlayer_View_Codehinting */?>

<style>
	<?php
	foreach ($this->row_styling as $group => $styling) {
		foreach ($styling as $field_id => $style) {
			echo 'div.row_' . $field_id . ' {' . PHP_EOL;
			echo $group . ': ' . $style . ';' . PHP_EOL;
			echo '}' . PHP_EOL;
		}
	}
	?>
</style>

<div class="container">
    <div class="row">
        <div class="col-md-12 preview-form">
            <?php echo $this->html; ?>
        </div>
    </div>
</div>

<script>
    $(document).ready(function()
    {
        formBuilder.setPreviewAtWidth();
    });
</script>
