<?php /** @var $this Dlayer_View_Codehinting */ ?>

<?php 
foreach($this->tools as $group) {
    
    $html = '';
    
    foreach($group as $tool) {
        
        $show = FALSE;
        $selected = FALSE;
        
        if($this->tool != FALSE) {
            $show = TRUE;
        } else {
            if($tool['tool'] != 'cancel') {
                $show = TRUE;
            } 
        }
        
        if($this->tool['tool'] == $tool['tool']) {
            $selected = TRUE;
        }
        
        if($show == TRUE) {
            if($this->field_id == NULL) {
                $reset = NULL;
            } else {
                $reset = '/reset/1';
            }
            
            if($selected == FALSE) {
                $html .= '<div class="tool">';
            } else {
                $html .= '<div class="tool selected">';
            }
            
            $html .= '<a href="/form/design/set-tool/tool/' . 
            $tool['tool'] . $reset . '">' . $tool['name'] . '</a></div>' . 
            PHP_EOL;
        }
    }
    
    if(strlen($html) > 0) {
        echo '<div class="group">' . PHP_EOL;
        echo $html;
        echo '</div>' . PHP_EOL;
    }
}  
?>