<?php /** @var $this Dlayer_View_Codehinting */ ?>

<?php 
foreach($this->tools as $group) {
    
    $html = '';
    
    foreach($group as $tool) {
        
        $show = FALSE;
        $selected = FALSE;
        
        if($this->tool != FALSE) {
            $show = TRUE;
        } else {
            if($tool['tool'] != 'cancel') {
                $show = TRUE;
            } 
        }
        
        if($this->tool['tool'] == $tool['tool']) {
            $selected = TRUE;
        }
        
        if($show == TRUE) {
            if($this->field_id == NULL) {
                $reset = NULL;
            } else {
                $reset = '/reset/1';
            }
            
            $class = "btn btn-default btn-xs";
            
            if($selected == TRUE) {
                $class = "btn btn-primary btn-xs";
            }
            
            if($tool['tool'] == 'cancel') {
                $class = "btn btn-danger btn-xs";
            }
            
            $html .= '<a href="/form/design/set-tool/tool/' . 
            $tool['tool'] . $reset . '"class="' . $class . '">' . 
            $tool['name'] . '</a> ';
        }
    }
    
    if(strlen($html) > 0) {
        echo '<p>' . PHP_EOL;
        echo $html;
        echo '</p>' . PHP_EOL;
    }
}  
?>