<?php /** @var Dlayer_View_Codehinting */ $this ?>

<div class="col-xs-12">
	<h3>Help <small>Create an email form field</small></h3>

	<p>This tool allows you to quickly add an email field to your form, the 
		email field is a text field with the values and options preset.</p>

	<p>After addition all the values and options can be changed, the field 
		will behave as per a standard text field because that is actually 
		what it is after addition.</p>
</div>