<?php /** @var Dlayer_View_Codehinting */ $this ?>

<div id="designer">
    <section id="design">
        <?php echo $this->dlayer_website; ?>
    </section>
    <?php if(strlen($this->dlayer_toolbar) > 1) { ?>
    <section id="tools">
        <?php echo $this->dlayer_toolbar; ?>
    </section>
    <?php } ?>
    <section id="ribbon">
        <?php echo $this->dlayer_ribbon; ?>
    </section>
</div>