<?php /** @var Dlayer_View_Codehinting */ $this ?>

<?php

foreach($this->tools as $group_id => $group) {

	$html = '';

	foreach($group as $tool) {

		$show = FALSE;
		$selected = FALSE;

		switch($tool['group_id']) {
			case 1:
			case 2:
				$show = TRUE;
				break;

			default:
				break;
		}

		// Set selected status for tool
		if($this->tool !== FALSE && $this->tool['tool'] === $tool['model'])
		{
			$selected = TRUE;
		}

		$reset = NULL;

		if($show === TRUE)
		{
			$class = "btn btn-default btn-sm";

			if($selected === TRUE)
			{
				$class = "btn btn-primary btn-sm";
			}

			if($tool['model'] === 'Cancel')
			{
				$class = "btn btn-danger";
			}

			$html .= '<a href="/website/design/set-tool/tool/' .
				$tool['model'] . $reset . '"class="' . $class . '">' .
				$tool['name'] . '</a> ';
		}
	}

	if(strlen($html) > 0)
	{
		echo '<div class="row">';
		echo '<div class="col-xs-12">';
		echo '<div class="tool-row-' . $group_id . '">';
		echo $html;
		echo '</div>';
		echo '</div>';
		echo '</div>';
	}
}
?>
