<?php /** @var $this Dlayer_View_Codehinting */ ?>

<?php 
foreach($this->tools as $group) {
    
    $html = '';
    
    foreach($group as $tool) {
        
        $show = FALSE;
        $selected = FALSE;
        
        if($this->tool != FALSE) {
            $show = TRUE;
        } else {
            if($tool['tool'] != 'cancel') {
                $show = TRUE;
            } 
        }
        
        if($this->tool['tool'] == $tool['tool']) {
            $selected = TRUE;
        }
        
        if($show == TRUE) {
            $class = "btn btn-default";
            
            if($selected == TRUE) {
                $class = "btn btn-primary";
            }
            
            if($tool['tool'] == 'cancel') {
                $class = "btn btn-danger";
            }
            
            $html .= '<a href="/website/design/set-tool/tool/' . 
            $tool['tool'] . '"class="' . $class . '">' . 
            $tool['name'] . '</a> ';
        }
    }
    
    if(strlen($html) > 0) {
    	echo '<div class="row">' . PHP_EOL;
    	echo '<div class="col-xs-12">' . PHP_EOL;
        echo '<div class="btn-group btn-group-sm" role="group">' . PHP_EOL;
        echo $html;
        echo '</div>' . PHP_EOL;
        echo '</div>' . PHP_EOL;
        echo '</div>' . PHP_EOL;
    }
}  
?>