<?php /** @var Dlayer_View_Codehinting */ $this ?>

<script>
$(document).ready(function() 
{
	$('div.website-manager h3').click(
		function() {
			var selector = this.className;
			$('div.' + selector).toggle();
			
			if($('h3.' + selector + ' > span').hasClass('glyphicon-minus')) {
				$('h3.' + selector + ' > span').removeClass('glyphicon-minus');
				$('h3.' + selector + ' > span').addClass('glyphicon-plus');
			} else {
				$('h3.' + selector + ' > span').removeClass('glyphicon-plus');
				$('h3.' + selector + ' > span').addClass('glyphicon-minus');
			}
		}
	)
	
	$('div.website-manager h3.pages-un-assigneed').trigger('click');
	$('div.website-manager h3.pages-parent').trigger('click');
	$('div.website-manager h3.pages-child').trigger('click');
})
</script>

<div class="website-manager">
	<div class="row">
		<div class="col-md-12">
			<h3 class="pages-un-assigneed"><span class="glyphicon glyphicon-minus" aria-hidden="true"></span> Un-assigned pages <small>No home yet</small></h3>	
		</div>
		<div class="pages-un-assigneed">
		<?php $x = 1; ?>
		<?php foreach($this->unassigned_pages as $page) { ?>
		<div class="col-md-3 small">
			<div class="panel panel-default">
				<div class="panel-heading">
					<?php echo $x . ': ' . $this->escape($page['name']); ?>
				</div>
				<div class="panel-body">
					<?php echo $this->escape($page['description']); ?>
					<div class="btn-group btn-group-xs" role="group">
						<a href="#" class="btn btn-default">Move</a> 
						<a href="#" class="btn btn-default">Content manager</a> 
					</div>
				</div>				
			</div>
		</div>
		<?php $x++; ?>
		<?php } ?>
		</div>
	</div>
	
	<div class="row">
		<div class="col-md-12">
			<h3 class="pages-parent"><span class="glyphicon glyphicon-minus" aria-hidden="true"></span> Parent pages <small>Parent page and siblings</small></h3>
		</div>
		<div class="pages-parent">
		<?php $x = 1; ?>
		<?php foreach($this->parent_pages as $page) { ?>
		<div class="col-md-3 small">
			<div class="panel panel-default">
				<div class="panel-heading">
					<?php echo $x . ': ' . $this->escape($page['name']); ?>
				</div>
				<div class="panel-body">
					<?php echo $this->escape($page['description']); ?>
					<div class="btn-group btn-group-xs" role="group">
						<a href="#" class="btn btn-default"><span class="glyphicon glyphicon-arrow-up" aria-hidden="true" title="Select parent"></span></a> 
						<a href="#" class="btn btn-default"><span class="glyphicon glyphicon-arrow-down" aria-hidden="true" title="Select children"></span></a> 
						<a href="#" class="btn btn-default">Move</a> 
						<a href="#" class="btn btn-default">Content manager</a> 
					</div>
				</div>				
			</div>
		</div>
		<?php $x++; ?>
		<?php } ?>
		</div>
	</div>
	
	<div class="row">
		<div class="col-md-12">
			<h3 class="pages-selected"><span class="glyphicon glyphicon-minus" aria-hidden="true"></span> Selected page <small>Currently selected page and siblings</small></h3>
		</div>
		<div class="pages-selected">
		<div class="col-md-3 small">
			<div class="panel panel-primary">
				<div class="panel-heading">
					<?php echo '1: Projects' ; ?>
				</div>
				<div class="panel-body">
					<?php echo 'Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum...'; ?>
					<div class="btn-group btn-group-xs" role="group">
						<a href="#" class="btn btn-info"><span class="glyphicon glyphicon-arrow-up" aria-hidden="true" title="Select parent"></span></a> 
						<a href="#" class="btn btn-info"><span class="glyphicon glyphicon-arrow-down" aria-hidden="true" title="Select children"></span></a> 
						<a href="#" class="btn btn-info">Move</a> 
						<a href="#" class="btn btn-info">Content manager</a> 
					</div>
				</div>				
			</div>
		</div>
		<?php $x = 2; ?>
		<?php foreach($this->selected_pages as $page) { ?>
		<div class="col-md-3 small">
			<div class="panel panel-default">
				<div class="panel-heading">
					<?php echo $x . ': ' . $this->escape($page['name']); ?>
				</div>
				<div class="panel-body">
					<?php echo $this->escape($page['description']); ?>
					<div class="btn-group btn-group-xs" role="group">
						<a href="#" class="btn btn-default"><span class="glyphicon glyphicon-arrow-up" aria-hidden="true" title="Select parent"></span></a> 
						<a href="#" class="btn btn-default"><span class="glyphicon glyphicon-arrow-down" aria-hidden="true" title="Select children"></span></a> 
						<a href="#" class="btn btn-default">Move</a> 
						<a href="#" class="btn btn-default">Content manager</a> 
					</div>
				</div>				
			</div>
		</div>
		<?php $x++; ?>
		<?php } ?>
		</div>
	</div>
	
	<div class="row">
		<div class="col-md-12">
			<h3 class="pages-child"><span class="glyphicon glyphicon-minus" aria-hidden="true"></span> Child pages <small>Children of the selected page</small></h3>
		</div>
		<div class="pages-child">
		<?php $x = 1; ?>
		<?php foreach($this->child_pages as $page) { ?>
		<div class="col-md-3 small">
			<div class="panel panel-default">
				<div class="panel-heading">
					<?php echo $x . ': ' . $this->escape($page['name']); ?>
				</div>
				<div class="panel-body">
					<?php echo $this->escape($page['description']); ?>
					<div class="btn-group btn-group-xs" role="group">
						<a href="#" class="btn btn-default"><span class="glyphicon glyphicon-arrow-up" aria-hidden="true" title="Select parent"></span></a> 
						<a href="#" class="btn btn-default"><span class="glyphicon glyphicon-arrow-down" aria-hidden="true" title="Select children"></span></a>  
						<a href="#" class="btn btn-default">Move</a> 
						<a href="#" class="btn btn-default">Content manager</a> 
					</div>
				</div>				
			</div>
		</div>
		<?php $x++; ?>
		<?php } ?>
		</div>
	</div>
</div>