<?php /** @var $this Dlayer_View_Codehinting */ ?>

<?php //var_dump($this->unassigned_pages); ?>
<?php //var_dump($this->selected_pages); ?>
<?php //var_dump($this->parent_pages); ?>
<?php //var_dump($this->child_pages); ?>

<div class="col-md-12 website-manager">

	<div id="unassigned_pages" class="pages_container">
		
		<h2>Unassigned pages</h2>
		
		<div class="pages">

		<?php foreach($this->unassigned_pages as $page) { ?>
		<!--<div class="mover">Move left</div>-->
		<div class="page">
			<div class="control">&nbsp;</div>
			<div class="page_details" id="page_<?php echo $this->escape($page['id']); ?>">
				<div class="row"><strong>Name:</strong> <?php echo $this->escape($page['name']); ?></div>
				<div class="row"><strong>Title:</strong> <?php echo $this->escape($page['title']); ?></div>
				<div class="description"><?php echo $this->escape($page['description']); ?></div>
				<!--<div class="mover">Move right</div>-->
			</div>
			<div class="control">&nbsp;</div>
			<div class="control cm_control"><a href="">View in content manager</a></div>
		</div>
		<?php } ?>
		
		</div>
	</div>

	<div id="parent_pages" class="pages_container">
		
		<h2>Parent pages</h2>
		
		<div class="pages">

		<?php foreach($this->parent_pages as $page) { ?>
		<!--<div class="mover">Move left</div>-->
		<div class="page">
			<!--<div class="mover left"></div>-->
			<div class="control"><a href="#">&nbsp;</a></div>
			<div class="page_details" id="page_<?php echo $this->escape($page['id']); ?>">
				<div class="row"><strong>Name:</strong> <?php echo $this->escape($page['name']); ?></div>
				<div class="row"><strong>Title:</strong> <?php echo $this->escape($page['title']); ?></div>
				<div class="description"><?php echo $this->escape($page['description']); ?></div>			
			</div>
			<div class="control"><a href="#">View <?php echo $this->escape($page['children']); ?> child pages</a></div>
			<div class="control cm_control"><a href="">View in content manager</a></div>
			<!--<div class="mover right"></div>-->
		</div>
		<?php } ?>
		
		</div>
	</div>

	<!--Need to limit the visible text for a title, name and description to n 
	characters, the full text should be shown by title=" for name and title but 
	not for description-->

	<div id="selected_pages" class="pages_container">
		
		<h2>Selected page and siblings</h2>
		
		<div class="pages">
		
		<div class="page selected">
			<div class="control"><a href="#">Select parent page</a></div>
			<div class="page_details" id="page_0">
				<div class="row"><strong>Name:</strong> Projects</div>
				<div class="row"><strong>Title:</strong> Our projects</div>
				<div class="description">Lorem ipsum, Lorem ipsum ...</div>
				<!--<div class="mover">Move right</div>-->
			</div>
			<div class="control"><a href="#">View 3 child pages</a></div>
			<div class="control cm_control"><a href="">View in content manager</a></div>
		</div>

		<?php foreach($this->selected_pages as $page) { ?>
		<!--<div class="mover">Move left</div>-->
		<div class="page">
			<div class="control"><a href="#">Select parent page</a></div>
			<div class="page_details" id="page_<?php echo $this->escape($page['id']); ?>">
				<div class="row"><strong>Name:</strong> <?php echo $this->escape($page['name']); ?></div>
				<div class="row"><strong>Title:</strong> <?php echo $this->escape($page['title']); ?></div>
				<div class="description"><?php echo $this->escape($page['description']); ?></div>
				<!--<div class="mover">Move right</div>-->
			</div>
			<div class="control"><a href="#">View <?php echo $this->escape($page['children']); ?> child pages</a></div>
			<div class="control cm_control"><a href="">View in content manager</a></div>
		</div>
		<?php } ?>
		
		</div>
	</div>

	<div id="child_pages" class="pages_container">
		
		<h2>Child pages</h2>
		
		<div class="pages">

		<?php foreach($this->child_pages as $page) { ?>
		<!--<div class="mover">Move left</div>-->
		<div class="page">
			<div class="control"><a href="#">Select parent page</a></div>
			<div class="page_details" id="page_<?php echo $this->escape($page['id']); ?>">
				<div class="row"><strong>Name:</strong> <?php echo $this->escape($page['name']); ?></div>
				<div class="row"><strong>Title:</strong> <?php echo $this->escape($page['title']); ?></div>
				<div class="description"><?php echo $this->escape($page['description']); ?></div>
				<!--<div class="mover">Move right</div>-->
			</div>
			<div class="control"><a href="#">View <?php echo $this->escape($page['children']); ?> child pages</a></div>
			<div class="control cm_control"><a href="">View in content manager</a></div>
		</div>
		<?php } ?>
		
		</div>
	</div>
</div>