<div class="row">
	<div class="col-md-12 col-sm-12 col-xs-12">

		<h1>Dlayer <small>Open Source responsive web development tool</small></h1>

		<p class="lead">The installation process is a work in progress; Dlayer is rapidly improving, I wanted an
			installation process, but I wanted it to be simple enough so as not to slow me down as I add new
			features to Dlayer.</p>

		<p>I want to improve and simplify this installation process, it is not user-friendly, as soon as Dlayer is
			more mature I will revisit the system. Please keep an eye on the Dlayer development
			<a href="http://blog.dlayer.com/">blog</a> and of course if you are interested in improving the
			installation process please <a href="http://dlayer.com/coding-standards.html">get in touch</a> with me.</p>

		<h2>Installation</h2>

		<p>Please follow the steps below to setup the demo after following the app installation steps in the
			<a href="https://github.com/Dlayer/dlayer/blob/master/README.md">README on GitHub</a>.</p>

		<p>You can setup your app to mirror the <a href="https://demo.dlayer.com">Dlayer demo</a> or start with a
			clean database. If you start with a clean database, you will need to use the add user action to create
			at least one user.  When a new user log into the demo a sample site is created automatically,
			this showcases all the features available within Dlayer.</p>

        <p><a href="/setup/import/demo" class="btn btn-primary">1: Import demo database <small>(Recommended)</small></a></p>
        <p><a href="/setup/import/clean" class="btn btn-default">2: Import clean database</a></p>
        <p><a href="/setup/import/reset-demo" class="btn btn-default">3: Reset to demo state</a></p>
        <p><a href="/setup/import/reset-clean" class="btn btn-default">4: Reset to clean state</a></p>
        <p><a href="/setup/user/create" class="btn btn-default" disabled="disabled">5: Create user</a> - <em>Not yet developed</em></p>

	</div>
</div>
