<?php /** @var Dlayer_View_Codehinting */ $this ?>

<div class="row">
	<div class="col-xs-12">
		<h2>Image detail</h2>
		
		<p>Use the tools showe above to manage the selected image, each time 
			you update this image a new version will be created, unless stated 
			otherwise you will always be viewing the latest version of this 
			image.</p>
			
		<p>No change is destructive, you can always revert back to a previous 
			version of this or any image in your Image library using the 
			version history panel.</p>
	</div>
</div>