<?php /** @var $this Dlayer_View_Codehinting */ ?>

<h2>Sub category</h2>

<p>This tool allows you to add a new sub category to the Image library or 
edit the details for an existing sub category. </p>

<p>Sub categories sit below categories and they can be used to further assist 
with organising your images. </p>

<p>There needs to be at least one sub category per category, a sub category
 will automatically be created when a new category is added.</p>