<?php /** @var Dlayer_View_Codehinting */ $this ?>

<div class="col-xs-12">
	<h3>Help <small>Add a new sub category</small></h3>

	<p>This tool allows you to add a new sub category to the Image library or 
		edit the details for an existing sub category.</p>

	<p>Sub categories sit below categories and they can be used to further 
		assist with organising your images. </p>

	<p>There needs to be at least one sub category per category, a sub 
		category will automatically be created when a new category is 
		added.</p>
</div>