<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div class="row">
	<div class="col-xs-12">
		<h2>Welcome to the Content manager</h2>
		
		<h4><span class="glyphicon glyphicon-play" aria-hidden="true"></span> 
		Select a content area to begin</h4>
		
		<p>Content areas are used to block out sections of your pages.</p>
		
		<p>To begin you need to select a content area, hover over a section 
			of the page and click to select, once you have selected a content 
			area we can move on.</p>
	</div>
</div>