<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div class="row">
	<div class="col-xs-12">
		<h2>Welcome to the Dlayer Content manager</h2>
		
		<p>Select the content block that you would would like to add a 
			content item to or the content block containing the content 
			item you would like to edit. If a content block is selectable 
			it will highlight when you move the mouse cursor over it.</p>
			
		<p>Once you have selected a content block the tools section will 
			updated to show all the content tools, a content row will either 
			need to be selected or added before the tools become 
			selectable.</p>
	</div>
</div>