<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div class="row">
	<div class="col-xs-12">
		<h2>Welcome to the Content manager</h2>
		
		<h4><span class="glyphicon glyphicon-play" aria-hidden="true"></span> 
		Select a content area to begin</h4>
		
		<p>To use any of the tools or edit any of the existing content items 
			or content rows you first need to select a content area. If a 
			content area is selectable it will highlight when you hover the 
			mouse over it, to select the area simply click the left mouse 
			button.
		</p>
	</div>
</div>