<script type="text/javascript">
$(document).ready(function() 
{
	dlayerDesigner.tabs.start('<?php echo $this->escape($this->module); ?>', '<?php echo $this->escape($this->tool); ?>');
	dlayerDesigner.tabs.load('<?php echo $this->escape($this->module); ?>', '<?php echo $this->escape($this->tool); ?>', '<?php echo $this->escape($this->sub_tool); ?>', '<?php echo $this->escape($this->tab_script); ?>');
});
</script>

<div class="row">
	<div class="col-md-12 col-sm-12">
		<ul class="nav nav-tabs">
			<?php foreach($this->tabs as $tab)
			{ ?>
				<?php if($tab['view_script'] === $this->tab_script)
			{
				$class = 'active';
			}
			else
			{
				$class = NULL;
			} ?>

			<li data-tool="<?php echo $this->escape($tab['tool']); ?>" data-sub-tool="<?php echo $this->escape($tab['sub_tool']); ?>" data-tab-script="<?php echo $this->escape($tab['view_script']); ?>" role="presentation" class="<?php echo $class; ?>">
				<a href="#" title="<?php echo $this->escape($tab['tab_name']); ?>">
				<span class="glyphicon glyphicon-<?php echo $this->escape($tab['glyph']); ?>" aria-hidden="true"></span> <span class="visible-md-inline visible-sm-inline"> <?php echo $this->escape($tab['tab_name']); ?></span>
				</a>
			</li>
			<?php } ?>
		</ul>
	</div>
</div>

<?php foreach($this->tabs as $tab) { ?>
	<?php if($tab['view_script'] === $this->tab) { $class = ' open'; } else { $class = NULL; } ?>
	<div data-tab-content="<?php echo $this->escape($tab['view_script']); ?>" class="row content<?php echo $class; ?>"></div>
<?php } ?>

