<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div class="row">
	<div class="col-xs-12">
		<h2>Content area selected <small>Now select a content row or add a 
			new one</small></h2>
		
		<p>To edit a content item you first need to select its content row, 
			to add a new item to an existing content row, again please 
			select it and then the item.</p>
		
		<p>To add a brand new item to a new row, create the row and then 
			use any of the content item tools.</p>
	</div>
</div>