<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div class="row">
	<div class="col-xs-12">
		<h2>Content area selected</h2>
		
		<h4><span class="glyphicon glyphicon-play" aria-hidden="true"></span> 
		Add a new content row</h4>
		
		<h4><span class="glyphicon glyphicon-play" aria-hidden="true"></span> 
		Select an existing content row</h4>
		
		<h4><span class="glyphicon glyphicon-play" aria-hidden="true"></span> 
		Use the content area sub tools</h4>
		
		<p>Now that you have selected a content area we can move onto content 
			rows, content rows act as containers for content items.</p>
		
		<p>To add a new content row please select the tool, you will then be 
			able to create one or more content rows.</p>
		
		<p>To select a content row move your mouse over the marked content 
			area, the content rows will highlight as you move your mouse over 
			them, click to select one.</p>
		
		<p>You can use any of the content area sub tools by simply selecting 
			a tab above.</p>
	</div>
</div>