<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div class="row">
	<div class="col-xs-12">
		<h2>Content row selected</h2>
			
		<h4><span class="glyphicon glyphicon-play" aria-hidden="true"></span> 
		Add a new content item</h4>
		
		<h4><span class="glyphicon glyphicon-play" aria-hidden="true"></span> 
		Edit an existing content item</h4>
		
		<h4><span class="glyphicon glyphicon-play" aria-hidden="true"></span> 
		Use the content row sub tools</h4>
		
		<p>Now that you have selected a content row you can work with 
			content items.</p>
		
		<p>To add a new content item please select the relevant tool.</p>
		
		<p>If you want to edit a content item move your mouse over the marked 
			content row, the content items will highlight as you move your 
			mouse over them, click to select one.</p>
		
		<p>You can use any of the content row sub tools by simply selecting a 
			tab above.</p>
	</div>
</div>