<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div class="row">
	<div class="col-xs-12">
		<h2>Content block selected <small>Now select a content item to edit or 
			add a new one</small></h2>
		
		<p>To edit a content item select it, to add a new content item 
			you need to either select an existing content row in the content 
			block or create one, once you have selected or created a content 
			row you will be able to select a content tool.</p>
	</div>
</div>