<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div class="row">
	<div class="col-xs-12">
		<h2>Content area selected</h2>
		
		<h4><span class="glyphicon glyphicon-play" aria-hidden="true"></span> 
		Add a new content row</h4>
		
		<h4><span class="glyphicon glyphicon-play" aria-hidden="true"></span> 
		Select an existing content row</h4>
		
		<p>If a content row is selectable it will highlight when you hover the 
			mouse over it, to select the content row simply click the left 
			mouse button.</p>
			
		<p>To add a brand new content item you first need to select a content 
			row, you can select an existing content row or create a new one.</p>
			
		<p>To edit a content item you simply need to select the content row 
			it belongs to.</p>
	</div>
</div>