<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div id="tab_content_1" class="content open">
    <h2>Block selected.</h2>
    
    <p>Now that you have selected a block you have two choices, you can use 
    the tool bar to the right to add a new content block or you can use the 
    mouse to choose a content item to edit.</p>
    
    <p>When you choose a tool from the right tool bar this area will 
    updated with all the controls.</p>
</div>