<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div class="row">
	<div class="col-xs-12">
		<h2>Content row selected <small>Now select a content item to edit or 
			add a new one</small></h2>
		
		<p>To edit a content item please click to selected, the tool and ribbon 
			area will update to show the edit controls for the selected content 
			item.</p>
		
		<p>To add a brand new content item to the selected row click the tool 
			that corresponds to the content item you want to create.</p>
	</div>
</div>