<?php /** @var $this Dlayer_View_Codehinting */ ?>

<h2>Password field</h2>

<p>This tool allows you to add a password field to your form.</p>

<p>To add the password field to your form fill in all the details and then 
click save. Once the new password field has been added to the form you will 
be returned to the designer in edit mode, in edit mode you can define 
validation values along with several other properties.</p>

<p>To add a text area field you need to define the label, description, 
placeholder text, field size and max length.</p>