<?php /** @var Dlayer_View_Codehinting */ $this ?>

<div class="col-xs-12">
    <h3>Help <small>Password field</small></h3>

    <p>This tool allows you to add a password field to your form.</p>

    <p>To add the password field to your form set the options and then click 
        <mark>Add password field</mark>. Once the field has been added to your 
        form the Form builder will switch to edit mode, in edit mode you can 
        change the options and access any sub tools.</p>
</div>

<div class="col-xs-12 further-reading">
    <?php echo $this->furtherReading('/#form-builder'); ?>
</div>
