<?php /** @var Dlayer_View_Codehinting */ $this ?>

<div class="col-xs-12">
	<h3>Help <small>Create a password field</small></h3>
	
	<p>This tool allows you to add a password field to your form.</p>

	<p>To add the password field to your form fill in all the details and then 
		click <mark>add</mark>. Once the new password field has been added 
		to the form you will be returned to the designer in edit mode, in edit 
		mode you can define validation values along with several other 
		properties.</p>

	<p>To add a password field you need to define the label, description, 
		placeholder text, field size and max length.</p>
</div>