<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div class="col-xs-12">
<?php if($this->edit_mode == TRUE && $this->data['preview_data'] != FALSE) { ?>
	<script type="text/javascript">

		$(document).ready(function() 
		{
			dlayer.preview.form.fn.row_attribute(<?php echo $this->escape(
				$this->data['preview_data']['field']['id']); ?>, 'label', 'label', '<?php echo $this->escape(
				$this->data['preview_data']['field']['label']); ?>');
			dlayer.preview.form.fn.row_attribute(<?php echo $this->escape(
				$this->data['preview_data']['field']['id']); ?>, 'description', 'p.help-block', '<?php echo $this->escape(
				$this->data['preview_data']['field']['description']); ?>');
			<?php foreach($this->data['preview_data']['preview_js'] as $preview) { ?>
				dlayer.preview.form.fn.<?php echo $this->escape(
					$preview['method']); ?>(<?php echo $this->escape(
					$preview['field_id']); ?>, '<?php echo $this->escape(
						$preview['attribute']); ?>', '<?php echo $this->escape(
						$preview['attribute']); ?>', '<?php echo $this->escape(
						$preview['attribute_value']); ?>');
					<?php } ?>
		});
	</script>

	<p class="dev-note bg-danger unsaved">Data has been modified!</p>

<?php } ?>
</div>

<div class="col-xs-12 small">
<?php
if($this->data != FALSE) {
	echo $this->data['form'];
}
?>
</div>

