<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div class="col-xs-12">
<?php if($this->edit_mode == TRUE) { ?>
	<script type="text/javascript">
		dlayer.preview.form.fn.rowBackgroundColor(<?php echo $this->escape(
			$this->data['preview_data']['field_id']); ?>, '<?php echo $this->escape(
			$this->data['preview_data']['background_color']); ?>');
	</script>

	<p class="dev-note bg-danger unsaved">Data has been modified!</p>
<?php } ?>
</div>

<div class="col-xs-12 small">
<?php echo $this->colorPicker()->picker($this->color_picker_data['palettes'], 
	$this->color_picker_data['history'], TRUE, TRUE); ?>
</div>
	
<div class="col-xs-12 small">
<?php 
if($this->data != FALSE) {
	echo $this->data['form'];
}
?>
</div>

<?php echo $this->colorPicker()->javascript(); ?>