<?php /** @var Dlayer_View_Codehinting */ $this ?>

<div class="row">
	<div class="col-md-12 col-xs-12">
		<h1>Settings</h1>
		
		<h3>Selected Web site: <small><?php echo $this->escape($this->site['name']); ?></small></h3>
		    
	    <nav class="visible-md-block visible-lg-block">
	    <?php echo $this->bootstrapNav($this->setting_groups['items'], 
	    $this->setting_groups['active_url']); ?>
	    </nav>
	    
	    <nav class="visible-xs-block visible-sm-block">
	    <?php echo $this->bootstrapNav($this->setting_groups['items'], 
	    $this->setting_groups['active_url'], 'nav nav-pills nav-stacked'); ?>
	    </nav>
	    
	    <hr />
	    
	    <nav class="visible-md-block visible-lg-block">
	    <?php echo $this->bootstrapNav($this->settings['items'], 
	    $this->settings['active_url'], 'nav nav-pills'); ?>
	    </nav>
	    
	    <nav class="visible-xs-block visible-sm-block">
	    <?php echo $this->bootstrapNav($this->settings['items'], 
	    $this->settings['active_url'], 'nav nav-pills nav-stacked'); ?>
	    </nav>
	    
	    <h4>Dlayer <small>App level settings</small></h4>
	    
	    <p>This section allows you to manage the app level settings for Dlayer, 
	    	these settings affect the entire application.</p>
	    	
	    <ol>
	    	<li>Colour palettes</li>
	    </ol>
	</div>
	<div class="col-md-12 col-xs-12 further-reading">
		<!--Need to upload content for settings-->
		<?php echo $this->furtherReading('/#settings', TRUE); ?>
	</div>
</div>