<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div id="content">
    
    <h1>Dlayer settings</h1>

    <h2><?php echo $this->escape($this->setting['title']); ?></h2>
    
    <h3>Web site: <?php echo $this->escape($this->site['name']); ?></h3>
    
    <?php echo $this->ulNavigation($this->setting_groups['class'], 
    $this->setting_groups['items'], $this->setting_groups['active_url']); ?>
    
    <?php echo $this->ulNavigation($this->settings['class'], 
    $this->settings['items'], $this->settings['active_url']); ?>
    
    <h3>Scope: <?php echo $this->escape($this->setting['scope']); ?> - 
    <?php echo $this->escape($this->setting['scope_details']); ?></h3>
    
    <?php echo $this->setting['description']; ?>
    
    <p class="note">Not yet developed!</p>
</div>