<?php /** @var Dlayer_View_Codehinting */ $this ?>

<div class="col-md-12 col-sm-12">
<?php if($this->edit_mode === TRUE) { ?>
	<script type="text/javascript">
		/*Preview function for row background colour */
		previewFormBuilder.rowBackgroundColor(<?php echo $this->escape($this->data['preview_data']['field_id']); ?>, '<?php echo $this->escape($this->data['preview_data']['background_color']); ?>');
	</script>

	<p class="dev-note bg-danger unsaved">Data has been modified!</p>
<?php } ?>
</div>

<div class="col-md-12 col-sm-12">
<?php echo $this->colorPicker()->picker($this->color_picker_data['palettes'], 
	$this->color_picker_data['history'], TRUE, TRUE); ?>
</div>

<div class="col-md-12 col-sm-12">
<?php 
if($this->data !== FALSE) {
	echo $this->data['form'];
}
?>
</div>

<?php echo $this->colorPicker()->javascript(); ?>
