<?php /** @var Dlayer_View_Codehinting */ $this ?>

<script language="javascript">
	<?php foreach($this->heading_styles as $key => $styles) { ?>
		<?php foreach($styles as $k => $values) { ?>
			<?php echo 'dlayer.settings.content.' . $key . '[' . $k . '] = 
			' . '\'' . $values['css'] . '\'' . PHP_EOL; ?>
			<?php } ?>
		<?php } ?>

	// Add event handlers for the heading previews
	$(document).ready(function() 
		{
			<?php foreach($this->heading_settings as $heading) { ?>
				dlayer.settings.content.fn.preview_font_styles(
					<?php echo $heading['id']; ?>, <?php echo $heading['style_id']; ?>);
				dlayer.settings.content.fn.preview_font_weights(
					<?php echo $heading['id']; ?>, <?php echo $heading['weight_id']; ?>);
				dlayer.settings.content.fn.preview_font_decorations(
					<?php echo $heading['id']; ?>, 
				<?php echo $heading['decoration_id']; ?>);
				dlayer.settings.content.fn.preview_font_sizes(
					<?php echo $heading['id']; ?>, <?php echo $heading['size']; ?>);
				dlayer.settings.content.fn.preview_font_colors(
					<?php echo $heading['id']; ?>, '<?php echo $heading['color_hex']; ?>');
				<?php } ?>

			$('.font_styles').change(function() 
				{
					dlayer.settings.content.fn.preview_font_styles(
						this.id.replace('style_id_', ''), this.value);
			});

			$('.font_weights').change(function() 
				{
					dlayer.settings.content.fn.preview_font_weights(
						this.id.replace('weight_id_', ''), this.value);
			});

			$('.font_decorations').change(function() 
				{
					dlayer.settings.content.fn.preview_font_decorations(
						this.id.replace('decoration_id_', ''), this.value);
			});

			$('.font_sizes').change(function() 
				{
					dlayer.settings.content.fn.preview_font_sizes(
						this.id.replace('size_', ''), this.value + 'px');
			});

			$('.font_colors').change(function() 
				{
					dlayer.settings.content.fn.preview_font_colors(
						this.id.replace('color_hex_', ''), this.value);
			});
	});
</script>

<div class="row">
	<div class="col-md-9 col-xs-12">
		<h1>Settings <small>Content manager <span class="label label-default">Site: <?php echo $this->escape($this->site['name']); ?></span></small></h1>
		
		<h2>Headings <small>Styles for the six heading tags</small></h2>
		
		<p>There are six heading tags in HTML, H1 through to H6, using the 
			forms below you can style each of the headings.</p>
		
		<?php foreach($this->heading_forms as $id => $form) { ?>
		<div class="row heading-styles">
			<div class="col-md-8 col-xs-12">
				<div class="form" id="form_<?php echo $id; ?>">
					<?php echo $form; ?>
				</div>
			</div>
			<div class="col-md-4  col-xs-12 bg-warning text-center" id="preview_<?php echo $id; ?>">
				<h2 style="font-style: normal; font-weight: 700; text-decoration: none; font-size: 20px; color: #17365D;"><?php echo $this->heading_settings[$id]['name']; ?></h2>
			</div>
		</div>
		<?php } ?>
					
	</div>
	<div class="col-md-3 col-xs-12">
		<ul class="list-unstyled settings-menu">
			<li><strong>Dlayer</strong>
				<ul>
					<li><a href="/dlayer/settings/index">Overview</a></li>
					<li><a href="/dlayer/settings/palettes">Color palettes</a></li>
				</ul>
			</li>
			<li><strong>Content manager</strong>
				<ul>
					<li><a href="/content/settings/index">Overview</a></li>
					<li><a href="/content/settings/base-font-family">Base font family</a></li>
					<li><a href="/content/settings/headings" class="active">Headings</a></li>
				</ul>
			</li>
			<li><strong>Form builder</strong>
				<ul>
					<li><a href="/form/settings/index">Overview</a></li>
					<li><a href="/form/settings/base-font-family">Base font family</a></li>
				</ul>
			</li>
		</ul>	
	</div>
</div>
<div class="row">
	<div class="col-md-12 col-xs-12 further-reading">
		<!--Need to upload content for settings-->
		<?php echo $this->furtherReading('/#settings', TRUE); ?>
	</div>
</div>
