<?php /** @var $this Dlayer_View_Codehinting */ ?>

<script language="javascript">
    <?php foreach($this->heading_styles as $key => $styles) { ?>
        <?php foreach($styles as $k => $values) { ?>
            <?php echo 'dlayer.settings.content.' . $key . '[' . $k . '] = 
            ' . '\'' . $values['css'] . '\'' . PHP_EOL; ?>
        <?php } ?>
    <?php } ?>
    
    // Add event handlers for the heading previews
    $(document).ready(function() 
    {
        <?php foreach($this->heading_settings as $heading) { ?>
        dlayer.settings.content.fn.preview_font_styles(
        <?php echo $heading['id']; ?>, <?php echo $heading['style_id']; ?>);
        dlayer.settings.content.fn.preview_font_weights(
        <?php echo $heading['id']; ?>, <?php echo $heading['weight_id']; ?>);
        dlayer.settings.content.fn.preview_font_decorations(
        <?php echo $heading['id']; ?>, 
        <?php echo $heading['decoration_id']; ?>);
        dlayer.settings.content.fn.preview_font_sizes(
        <?php echo $heading['id']; ?>, <?php echo $heading['size']; ?>);
        dlayer.settings.content.fn.preview_font_colors(
        <?php echo $heading['id']; ?>, '<?php echo $heading['color_hex']; ?>');
        <?php } ?>
        
        $('.font_styles').change(function() 
        {
            dlayer.settings.content.fn.preview_font_styles(
            this.id.replace('style_id_', ''), this.value);
        });
        
        $('.font_weights').change(function() 
        {
            dlayer.settings.content.fn.preview_font_weights(
            this.id.replace('weight_id_', ''), this.value);
        });
        
        $('.font_decorations').change(function() 
        {
            dlayer.settings.content.fn.preview_font_decorations(
            this.id.replace('decoration_id_', ''), this.value);
        });
        
        $('.font_sizes').change(function() 
        {
            dlayer.settings.content.fn.preview_font_sizes(
            this.id.replace('size_', ''), this.value + 'px');
        });
        
        $('.font_colors').change(function() 
        {
            dlayer.settings.content.fn.preview_font_colors(
            this.id.replace('color_hex_', ''), this.value);
        });
    });
</script>

<div id="content">
    <h1><?php echo $this->escape($this->setting['title']); ?></h1>
    
    <h2>Web site: <?php echo $this->escape($this->site['name']); ?></h2>
    
    <?php echo $this->ulNavigation($this->setting_groups['class'], 
    $this->setting_groups['items'], $this->setting_groups['active_url']); ?>
    
    <?php echo $this->ulNavigation($this->settings['class'], 
    $this->settings['items'], $this->settings['active_url']); ?>
    
    <h2>Scope: <?php echo $this->escape($this->setting['scope']); ?> - 
    <?php echo $this->escape($this->setting['scope_details']); ?></h2>
    
    <?php echo $this->setting['description']; ?>
            
    <div class="headings">
        <?php foreach($this->heading_forms as $id => $form) { ?>
        <div class="heading">
            <div class="form" id="form_<?php echo $id; ?>">
            <?php echo $form; ?>
            </div>
            <div class="preview" id="preview_<?php echo $id; ?>">
                <h2 style="font-style: normal; font-weight: 700; text-decoration: none; font-size: 20px; color: #17365D;"><?php echo $this->heading_settings[$id]['name']; ?></h2>
            </div>
        </div>
        <?php } ?>
    </div>
</div>