<?php /** @var Dlayer_View_Codehinting */ $this ?>

<div class="col-xs-12">
	<h3>Help <small>Add name field</small></h3>

	<p>This tool allows you to quickly add a name field to your form, a 
		name field is simply a text field where the options are already 
		set.</p>
		
	<p>Once the name field has been added to your form you can edit it as you 
		would any text field, all the options are configurable.</p>
</div>

<div class="col-xs-12 further-reading">
	<?php echo $this->furtherReading('/#form-builder'); ?>
</div>
