<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div class="col-xs-12">
	<h3>Help <small>Add a text content item to the content page</small></h3>
	
	<p>This tool allows you to add a text content item to the content page, to 
		add a text content item you need to define the text and also a name by 
		which to identify it later, the name will only be visible to you 
		within Dlayer.</p>
	
	<p>The initial size of the newly inserted text content item depends upon 
		whether or not there are any other content items in the content row, 
		Dlayer will attempt to predict a sensible size for you based on the 
		size of any sibling content items and any remaining space, it will 
		attempt to size the text content item to fill all the remaining space. 
		If Dlayer deems that there is not enough remaining space in the content 
		row it will set a sensible default, for text content items the default 
		is 12, the text content item will automatically be sized to span the 
		entire width of the content row. If the text content item is the only 
		item in the content row the same rule will be applied.</p>
	
	<p>At any time, the width and position of the text content item can be 
		managed via the size and position tab when the tool is in edit mode, 
		in edit mode you will also get access to all the other sub tools.</p>
</div> 