<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div class="col-xs-12">
	<h3>Help <small>Create a new text content item</small></h3>
	
	<p>This tool allows you to add or edit a text content item, to add a 
		text content item you need to define the text and an internal name 
		to identity the text by.</p>
	
	<p>The initial size of a text content item depends on whether or not 
		there are other content items in the row, if the text item is the 
		only item the content will span the entire row, otherwise it will 
		span all the remaining space. If there is not enough space for the 
		text content item will will drop down below the other content items.</p>
	
	<p>The width and position of the text content item can be managed via 
		the size and position tab when you are in edit mode, in edit mode 
		you will have access to all the sub tools.</p>
</div> 