<?php /** @var $this Dlayer_View_Codehinting */ ?>

<p>This tool allows you to add or edit a text content item, when adding a new 
text item you define the text, size of the content container and also the 
padding around the text.</p>

<p>The size and padding values will be defaulted based upon the size of the 
page container, the values will also be validated when the tool is being 
processed, you cannot add a content container which is larger than the page 
container.</p>

<p>In edit mode you will be able to define the styling for the content 
container and also the formatting for the content which will override the 
values defined in the 
<a href="/content/settings/base-font-family">Content manager settings</a>.</p>
