<?php /** @var Dlayer_View_Codehinting */ $this ?>

<?php if($this->edit_mode == TRUE) { ?>
<script>
dlayer.preview.content.fn.containerWidth(
<?php echo $this->data['preview']['content_id']; ?>, '#params-size');
dlayer.preview.content.fn.containerOffset(
<?php echo $this->data['preview']['content_id']; ?>, '#params-offset');
</script>
<?php } ?>

<div class="col-md-12 col-sm-12">
	<p class="dev-note bg-danger unsaved">Data has been modified!</p>
</div>

<div class="col-md-12 col-sm-12 small">
<?php 
if($this->data != FALSE) {
	echo $this->data['form'];
}
?>
</div>