<?php /** @var Dlayer_View_Codehinting */ $this ?>

<?php if($this->edit_mode == TRUE) { ?>
<script>
dlayer.preview.content.fn.elementText(
	<?php echo $this->data['preview']; ?>, '#params-text');
</script>
<?php } ?>

<div class="col-xs-12">
	<p class="dev-note bg-danger unsaved">Data has been modified!</p>
</div>

<div class="col-xs-12 small">
	<?php 
	if($this->data != FALSE) {
		echo $this->data['form'];
	}
	?>
</div>