<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div class="col-xs-12">		
	<h3>Row <small>Add a new content row</small></h3>
	
	<p>Click <mark>add row</mark> below to add a new content row, it will be 
		placed after any existing content rows and you will immediately be 
		able to new content items to it.</p>
</div>

<div class="col-xs-12 small">
	<form action="/content/process/auto-tool" method="post" class="form">
		<fieldset>
			<div class="form-group">
				<input type="hidden" name="div_id" value="<?php echo $this->escape($this->div_id); ?>" />
			</div>
			<div class="form-group">
				<input type="hidden" name="page_id" value="<?php echo $this->escape($this->page_id); ?>" />
			</div>			
			<div class="form-group">
				<input type="hidden" name="tool" value="add-content-row" />
			</div>
			<div class="form-group">
				<input type="hidden" name="params[multi_use]" value="0" />
			</div>
			<div class="form-group">
				<input type="submit" class="btn btn-primary" name="submit" value="Add row" />
			</div>
		</fieldset>
	</form>
</div>