<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div class="row">
	<div class="col-md-12 col-xs-12">
		<h1>Image library <small>Image management</small></h1>
	</div>

	<div class="col-md-12 col-xs-12">
		<h2>Web site 
		<small><?php echo $this->escape($this->site['name']); ?></small></h2>
	</div>

	<div class="col-md-12 col-xs-12">
		<p>The Image library is the base for all image management and later 
			all media management (after a rename), the Image library is a 
			site wide feature that all the designers plug into.</p>
		
		<p>Image assets can be categorised using any number of custom 
			categories and sub categories, the only hard rules being that a 
			'Misc.' sub category will be automatically created when a new 
			category is added and 'Backgrounds' category will be 
			automatically created upon your first visit to the Image 
			library.</p>
		
		<p>When you manipulate an image using a tool a new version of the 
			selected image is created and the tool used to create the new 
			version is logged along with the request, older versions of 
			images are always accessible, recoverable and even usable by 
			any of the tools in the designers. For example the background 
			image tool can use a cropped version of an image without 
			affecting the original version.</p>
		
		<p>When an image is used by any of the tools in the designers Dlayer 
			automatically creates a new version of the selected image, the 
			original is always left as is, although it appears as though a 
			full new version has been created in reality a shallow version 
			has been created which links directly to the selected version.</p>
		
		<p>The Image library includes all the standard adjustment and 
			manipulation tools, for example cropping and resizing.</p>
		
		<p>When you need to choose an image you will be presented with an 
			Image picker which will allow you to filter down your selection 
			by category, subcategory, image and then version.</p>
		
		<p class="dev-note bg-info">Although basic tools have been added to 
			the Image library it should be considered a preview until this 
			message is removed.</p>
					
		<h2>Options <small>Image library management options</small></h2>
		
		<p>
			<a href="/image/design/index/" class="btn btn-primary">Go to Image library</a>
	    </p>
	</div>
</div>