<?php /** @var Dlayer_View_Codehinting */ $this; ?>

<div class="row">
	<div class="col-md-12 col-xs-12">
		<h1>Image library <small>Media management <span class="label label-default">Site: <?php echo $this->escape($this->site['name']); ?></span></small></h1>
		
		<h2>Overview</h2>
		
		<p>The Image library is where all media management is done, it is a site 
			wide feature that is exposed to the rest of the site via the 
			image picker.</p>
		
		<p>
			<a href="/image/design/index/" class="btn btn-primary">
				Go to Image library</a>
		</p>
	</div>
</div>

<div class="row">
	<div class="col-md-12 col-xs-12 further-reading">
		<?php echo $this->furtherReading('/#image-library', TRUE); ?>
	</div>
</div>
