<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div class="col-xs-12 small">
	<form enctype="application/x-www-form-urlencoded" 
	action="/website/design/index" method="post" class="form">
		<fieldset id="fieldset-heading_text">
			<legend>Add <small>Create a new web page</small></legend>
			<div class="form-group">
				<label for="params-name" class="required">Name</label>
				<input type="text" name="name" id="name" value="" 
					size="50" maxlength="255" placeholder="e.g., News page" 
					class="form-control input-sm" />
				<p class="help-block">Enter a name for the new page, this 
					will only display within Dlayer, not on your site.</p>
    		</div>
    		<div class="form-group">
    			<label for="params-template" class="required">Template</label>
    			<select name="template" id="template" 
    				class="form-control input-sm">
    				<option value="1">Sample template</option>
				</select>
				<p class="help-block">Choose the template to use to base the 
					new page upon.</p>
			</div>
			<div class="form-group">
				<label for="params-title" class="required">Title</label>
				<input type="text" name="title" id="name" value="" size="50" 
					maxlength="255" placeholder="e.g., News page" 
					class="form-control input-sm">
				<p class="hint">Enter the title for your page, this will be 
					shown in the title bar or the user's web browser.</p>
    		</div>
    		<div class="form-group">
    			<input type="submit" name="submit" id="submit" value="Save" 
    				class="btn btn-primary">
    		</div>
    	</fieldset>
    </form>
</div>