<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div class="col-xs-12">		
	<h3>Help <small>Delete selected content row</small></h3>
	
	<p>This tool will remove the row and all the child content items from the 
		page, you will not be able to undo this action once it has been 
		done.</p>
	
	<p>Although the content items will be removed from this page the base 
		data will still be accessible, if for instance you delete a 
		heading item, you will still be able to recreate the heading by 
		using the import heading tool and selected the text you desire.</p>
	
	<p class="dev-note bg-info">Eventually I will add a full undo stack to 
		allow changes to be undone.</p>
</div>