<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div class="col-xs-12">
	<h3>Help <small>Add an image to the content page</small></h3>
	
	<p>This tool allows you to add a text content item to the content page, 
		to add a text content item you need to define the text and also a 
		name by which to identify it later, the name will only be visible to 
		you.</p>
	
	<p>The initial size of the newly inserted text content item depends on 
		whether or not there are other content items in the content row, 
		Dlayer will attempt to predict a sensible size based on the size of 
		sibling content items. If Dlayer deems that there is enough space 
		left in the content row the text content item will automatically be 
		sized to fill the rest of the content row. If the text content item 
		is the only item in the content row or Dlayer thinks any remaining 
		space is too small the text content item will drop below the other 
		content items and the size will be set so that the text content item 
		fills the entire width of the content row.</p>
	
	<p>At any time, the width and position of the text content item can be 
		managed via the size and position tab when the tool is in edit mode, 
		in edit mode you will also get access to all the other sub tools.</p>
</div>