<?php /** @var Dlayer_View_Codehinting */ $this ?>

<div class="col-xs-12">
	<h3>Help <small>Add an image content item to the content page</small></h3>
	
	<p>This tool allows you to add an image content item to the content page, 
		to add an image content item you need to select an image from your 
		Image library, choose whether or not you want your users to be able 
		to expand the image and optionally define the caption that will appear 
		below the image.</p>
	
	<p>The initial size of the newly inserted image content item depends upon 
		whether or not there are any other content items in the content row, 
		Dlayer will attempt to predict a sensible size for you based on the 
		size of any sibling content items and any remaining space, it will 
		attempt to size the image content item to fill all the remaining 
		space. If Dlayer deems that there is not enough remaining space in 
		the content row it will set a sensible default, for image content 
		items the default is six, the image content item will automatically 
		be sized to span half the width of the content row. If the image 
		content item is the only item in the content row the same rule will 
		be applied.</p>
	
	<p>At any time, the size and position of the image content item can be 
		managed via the size and position tab when the tool is in edit mode, 
		in edit mode you will also get access to all the other sub tools.</p>
		
	<p class="dev-note bg-info">You can only test the expand setting when 
		viewing the design in the preview window, the expand controls can't 
		be added in the design window because they interfere with the selection 
		controls.</p>
		
	<?php echo $this->furtherReading(
		'the-designers/content-manager/create-tools/image/', 
		TRUE); ?>
</div>