<?php /** @var $this Dlayer_View_Codehinting */ ?>

<script>
</script>

<!--http://www.bootply.com/123443-->

<div class="col-xs-12">
	<div class="image-picker-tool panel panel-default">
		<div class="panel-heading">Image picker</div>
		<div class="panel-body">			
			<div class="form-group ip-category">
				<label for="ip-category" class="required">Category</label>
				<select name="ip-category" id="ip-category" class="form-control input-sm">
					<option value="0">Select category</option>
					<option value="1">Category 1</option>
					<option value="2">Category 2</option>
				</select>
				<p class="help-block">Select a category from your Image 
					library to show sub categories.</p>
			</div>
			
			<div class="form-group ip-sub-category">
				<label for="ip-sub-category" class="required">Sub category</label>
				<select name="ip-sub-category" id="ip-sub-category" class="form-control input-sm">
					<option value="0">Select sub category</option>
					<option value="1">Sub category 1</option>
					<option value="2">Sub category 2</option>
					<option value="3">All</option>
				</select>
				<p class="help-block">Select a sub category to list the images 
					defined in the selected category and sub category.</p>
			</div>
			
			<div class="form-group form-group-submit">
				<input type="submit" name="submit" id="submit" value="Select" class="btn btn-primary">
			</div>
				
			<button type="button" class="close" title="Close" aria-label="Close">
				<span aria-hidden="true">×</span>
			</button>
		</div>	
	</div>	
</div>

<!--<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">Popup image</button>

<div id="myModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
	<div class="modal-content">
		<div class="modal-body">
			<img src="//placehold.it/1000x600" class="img-responsive">
		</div>
	</div>
  </div>
</div>-->

<div class="col-xs-12">
	<form>
		<fieldset>
			<legend>Image <small>Add an new image content item</legend>
			<div class="form-group form-group-submit">
<input type="submit" name="submit" id="submit" value="Add" class="btn btn-primary"></div>
		</fieldset>
	</form>
</div>	
