<?php /** @var $this Dlayer_View_Codehinting */ ?>

<script>
</script>

<!--http://www.bootply.com/123443-->

<div class="col-xs-12 small">
	<div class="image-picker-tool panel panel-default">
		<div class="panel-heading">Image picker</div>
		<div class="panel-body">			
			<div class="form-group ip-category">
				<label for="ip-category" class="required">Category</label>
				<select name="ip-category" id="ip-category" class="form-control input-sm">
					<option value="0">Select category</option>
					<option value="1">Category 1</option>
					<option value="2">Category 2</option>
				</select>
				<p class="help-block">Select a category from your Image 
					library to show sub categories.</p>
			</div>
			
			<div class="form-group ip-sub-category">
				<label for="ip-sub-category" class="required">Sub category</label>
				<select name="ip-sub-category" id="ip-sub-category" class="form-control input-sm">
					<option value="0">Select sub category</option>
					<option value="1">Sub category 1</option>
					<option value="2">Sub category 2</option>
					<option value="3">All</option>
				</select>
				<p class="help-block">Select a sub category to list the images 
					defined in the selected category and sub category.</p>
			</div>
			
			<div class="image-list">
				<h4>Images <small>Images for the selected category and 
					sub category</small></h4>
			
				<div class="row" style="padding-bottom: 10px;">
					<div class="col-xs-4">
					<img src="/images/library/1/1.jpg" title="Autumn path" alt="Image library image" width="160" height="120" class="img-thumbnail">
					</div>
					<div class="col-xs-8">
						<p>
							<strong>Name:</strong> Autumn path<br />
							<strong>Dimenisons:</strong> 615 X 453 pixels<br />
							<strong>Size:</strong> 169.4 kb
						</p>
					</div>
					<div class="col-xs-12 text-right">
						<div class="btn-group btn-group-xs" role="group" aria-label="...">
							<button type="button" class="btn btn-primary">Select</button>
							<button type="button" class="btn btn-default" disabled="disabled">View versions</button>
						</div>
					</div>
				</div>
				
				<div class="row" style="padding-bottom: 10px;">
					<div class="col-xs-4">
					<img src="/images/library/7/23.jpg" title="Spring coffee" alt="Image library image" width="160" height="120" class="img-thumbnail">
					</div>
					<div class="col-xs-8">
						<p>
							<strong>Name:</strong> Spring coffee<br />
							<strong>Dimenisons:</strong> 561 X 367 pixels<br />
							<strong>Size:</strong> 41.6 kb
						</p>
						</div>
					<div class="col-xs-12 text-right">
						<div class="btn-group btn-group-xs" role="group" aria-label="...">
							<button type="button" class="btn btn-primary">Select</button>
							<button type="button" class="btn btn-default" disabled="disabled">View versions</button>
						</div>
					</div>
				</div>
				
				<div class="row" style="padding-bottom: 10px;">
					<div class="col-xs-4">
					<img src="/images/library/5/5.jpg" title="Spring coffee" alt="Image library image" width="160" height="120" class="img-thumbnail">
					</div>
					<div class="col-xs-8">
						<p>
							<strong>Name:</strong> Robin<br />
							<strong>Dimenisons:</strong> 615 X 407 pixels<br />
							<strong>Size:</strong> 32.0 kb
						</p>
					</div>
					<div class="col-xs-12 text-right">
						<div class="btn-group btn-group-xs" role="group" aria-label="...">
							<button type="button" class="btn btn-primary">Select</button>
							<button type="button" class="btn btn-default" disabled="disabled">View versions</button>
						</div>
					</div>
				</div>
			</div>
				
			<button type="button" class="close" title="Close" aria-label="Close">
				<span aria-hidden="true">×</span>
			</button>
		</div>	
	</div>	
</div>

<!--<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">Popup image</button>

<div id="myModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
	<div class="modal-content">
		<div class="modal-body">
			<img src="//placehold.it/1000x600" class="img-responsive">
		</div>
	</div>
  </div>
</div>-->

<div class="col-xs-12">
	<form>
		<fieldset>
			<legend>Image <small>Add an new image content item</legend>
			<div class="form-group form-group-submit">
<input type="submit" name="submit" id="submit" value="Add" class="btn btn-primary"></div>
		</fieldset>
	</form>
</div>	
