<?php /** @var $this Dlayer_View_Codehinting */ ?>

<script>
dlayer.designers.imagePickerOpen();
</script>

<div class="col-xs-12 small">
	<div class="image-picker-tool panel panel-default" style="display:none">
		<div class="panel-heading">Image picker</div>
		<div class="panel-body">
			<div class="row">
				<div class="loading col-xs-4 col-xs-offset-4 text-center">
					<img src="/images/dlayer/ajax-loader.gif" title="Loading..." />
				</div>
			</div>
			<div class="form">
			</div>
		</div>	
	</div>	
</div>

<div class="col-xs-12 small">
	<p><a href="#" class="btn btn-primary open-image-picker-tool">Load picker</a></p>
	
	<?php 
	if($this->data != FALSE) {
		echo $this->data['form'];
	}
	?>
</div>