<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div id="content">
    <h1>Library development</h1>
    
    <h2>Thumbnail generator - process</h2>
    
    <p>This action will have attempted to generate a thumbnail for the test 
    image, below will either be a sucdess message or the generated errors, 
    return to the <a href="/dev/thumbnail/index">thumbnail generator.</a> to 
    see and delete the generated image.</p>
    
    <p><strong>Errors:</strong> <?php echo $this->escape($this->error); ?></p>
</div>