<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div id="content">
    <h1>Library development</h1>
    
    <h2>Thumbnail generator - process</h2>
    
    <p>This action will have attempted to generate a thumbnail for the test 
    image, below will either be a sucess message or the generated errors.</p>
    
    <p><strong>Errors:</strong> <?php echo $this->escape($this->error); ?></p>
    
    <p><a href="/dev/thumbnail/index">Return to thumbnail generator.</a></p>
</div>