<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div id="content">
    <h1>Widget designer settings</h1>
    
    <h2>Web site: <?php echo $this->escape($this->site['name']); ?></h2>
    
    <p>Choose a setting to modify using the menu below, you can choose the 
    section and then a setting within that section.</p>
    
    <p>The scope for each setting will be outlined on the settings page, the 
    scopes are app, module and tool.</p>
    
    <?php echo $this->ulNavigation($this->setting_groups['class'], 
    $this->setting_groups['items'], $this->setting_groups['active_url']); ?>
    
    <?php echo $this->ulNavigation($this->settings['class'], 
    $this->settings['items'], $this->settings['active_url']); ?>
</div>