<?php /** @var Dlayer_View_Codehinting */ $this ?>

<div class="col-md-12 col-sm-12">
	<h3>Content area selected</h3>

	<h5><span class="glyphicon glyphicon-play" aria-hidden="true"></span> 
	Add a new content row</h5>

	<p>Add one or more content rows to the selected content area.</p>

	<h5><span class="glyphicon glyphicon-play" aria-hidden="true"></span> 
	Select an existing content row</h5>

	<p>Select a content row, this will allow you to select its content items 
		or allow you to add a new one.

	<h5><span class="glyphicon glyphicon-play" aria-hidden="true"></span> 
	Use the content area sub tools</h5>

	<p>Modify the options for the selected content area.</p>
</div>
