<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div class="col-xs-12">		
	<h3>Help <small>Content area</small></h3>
	
	<p>A content area is an invisible container, content areas are the 
		sections marked out on your template in the Template designer, you 
		can't alter them in the Content manager, only change their display.</p>
	
	<p>A content area should be used to separate areas of your content pages, 
		for example, you might have a content area for the header and navigation 
		items, one for the footer items and one for the main content that makes 
		up your content page.</p>
</div>