<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div class="col-xs-12">
	<h3>Help <small>Create a new jumbotron content item</small></h3>
	
	<p>This tool allows you to add or edit a jumbotron content item, to add 
		a jumbotron content item you need to define the title, a sub title 
		description and an internal name to identity the text by.</p>
	
	<p>A jumbotron content item will initially span the entire width of a 
		content row, the position and width of a jumbotron can be modified 
		using the Size and Position sub tool when in edit mode.</p>
	
	<p>The width and position of the jumbotron content item can be managed 
		via the size and position tab when you are in edit mode, in edit 
		mode you will have access to all the sub tools.</p>
</div> 