<?php /** @var Dlayer_View_Codehinting */ $this ?>

<div class="col-xs-12">		
	<h3>Help <small>Select parent content area or content row</small></h3>
	
	<p>This tool allows you to step backwards by either selecting the parent 
		content area or content row. If you need to return to the content 
		item you can use the back to edit button.</p>
		
	<?php echo $this->furtherReading(
		'the-designers/content-manager/structure-tools/select-parent/', 
		TRUE); ?>
</div>