<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div class="col-xs-12">		
	<h3>Select <small>Select parent content row or content area</small></h3>
	
	<p>Use the buttons below to select either the content row or content 
		area that this content item belongs to. If you would like to return to 
		the edit screen click the back to edit button.</p>
		
	<?php if($this->data != FALSE) { ?>
	
	<h4><span class="glyphicon glyphicon-play" aria-hidden="true"></span> 
	Select the content area</h4>
	
	<p><a href="/content/design/set-selected-div/selected/<?php echo $this->escape($this->data['div_id']); ?>" role="button" class="btn btn-primary">Select content area</a></p>
	
	<h4><span class="glyphicon glyphicon-play" aria-hidden="true"></span> 
	Select the content row</h4>
	
	<p><a href="/content/design/set-selected-content-row/selected/<?php echo $this->escape($this->data['content_row_id']); ?>" role="button" class="btn btn-primary">Select content row</a></p>
	
	<h4><span class="glyphicon glyphicon-play" aria-hidden="true"></span> 
	Back to edit content item</h4>
	
	<p><a href="/content/design/set-selected-content/selected/<?php echo $this->escape($this->data['content_id']); ?>/content-type/<?php echo $this->escape($this->data['content_type']); ?>/tool/<?php echo $this->escape($this->data['tool']); ?>" role="button" class="btn btn-primary">Back to edit</a></p>
	
	<?php } else { ?>
	
	<p class="dev-note bg-danger">There was an error selecting the data for 
		the content item from the system</p>
	<?php } ?>

</div>