<?php /** @var $this Dlayer_View_Codehinting */ ?>

<p>This tool allows you to create a new heading content item using an 
existing piece of text data. When creating a heading item using this tool 
you select some existing text to use and then define the style and content 
container settings as per the heading tool.</p>

<p>Once a new heading content item has been created using this tool it 
becomes a standard heading item which will be editable using the heading 
tool.</p>
