<?php /** @var Dlayer_View_Codehinting */ $this ?>

<div class="col-xs-12">
	<h3>Help <small>Add a heading content item to the content page using 
		existing content.</small></h3>
	
	<p>This tools allows you to create a new heading content using data from 
		an existing or deleted heading content item. Simply select the 
		existing content that you would like to import, the form fields will 
		be populated with your chosen data, you are free to modify any of the 
		imported values if required.</p>
	
	<p>A heading content item will automatically be sized to span the entire 
		width of the content row.</p>
	
	<p>At any time, the size and position of the heading content item can be 
		managed via the size and position tab when the tool is in edit mode, 
		in edit mode you will also get access to all the other sub tools.</p>
	
	<p>Once created the imported content item will behave as a standard 
		heading content item.</p>
		
	<?php echo $this->furtherReading(
		'the-designers/content-manager/import-tools/heading/', 
		TRUE); ?>
</div>