<?php /** @var Dlayer_View_Codehinting */ $this ?>

<div class="row">
	<div class="col-xs-12">
		<h3>Welcome to the Dlayer Web site manager</h3>
		
		<p>Manage your web site using the tools shown to the left, from here 
			you can control the structure of your web site.</p>
	</div>
	
	<div class="col-xs-12 small">
		<form enctype="application/x-www-form-urlencoded" 
			action="/website/design/index" method="post" class="form">
			<fieldset>
				<legend>Edit <small>Edit the page details</small></legend>
				
    			<div class="form-group">
    				<label for="params-name" class="required">Name</label>
    				<input type="text" name="name" id="name" 
    					value="Projects" size="50" maxlength="255" 
    					placeholder="e.g., News page" 
    					class="form-control input-sm" />
    				<p class="help-block">Enter a name for the page, this 
    					will only display within Dlayer, not on your 
    					web site.</p>
    			</div>
    			<div class="form-group">
    				<label for="params-title" class="required">Title</label>
    				<input type="text" name="title" id="name" 
    					value="Our projects" size="50" maxlength="255" 
    					placeholder="e.g., News page" 
    					class="form-control input-sm" />
    				<p class="help-block">Enter the title for your page, 
    					this will be shown in the title bar of the user's 
    					web browser.</p>
    			</div>
    			<div class="form-group">
    				<input type="submit" name="submit" id="submit" 
    					value="Save" class="btn btn-primary">
    			</div>
    		</fieldset>
    	</form>
	</div>
</div>