<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div class="col-xs-12">
	<h3>Help <small>Add a form to the content page</small></h3>
	
	<p>This tools allows you to insert a form from the Form builder, to 
		insert a form you simply need to select the form to use from your 
		form library.</p>
	
	<p>The initial size of the newly inserted form depends on whether or not 
		there are other content items in the content row, Dlayer will 
		attempt to predict a sensible size based on the size of sibling 
		content items. If Dlayer deems that there is enough space left in 
		the content row the form will automatically be sized to fill the 
		rest of the content row. If the form is the only item in the content 
		row or Dlayer thinks any remaining space is too small the form will 
		drop below the other content items and the size will be set so that 
		the inserted form fills the entire width of the content row.</p>
	
	<p>At any time, the width and position of the inserted form can be 
		managed via the size and position tab when the tool is in edit mode, 
		in edit mode you will also get access to all the other sub tools.</p>
</div>