<?php /** @var Dlayer_View_Codehinting */ $this ?>

<div class="col-xs-12">
	<h3>Help <small>Add a form content item to the content page</small></h3>
	
	<p>This tool allows you to add a form content item to the content page, 
		to add a form content item you simply need to select the form that you 
		would like to insert.</p>
	
	<p>The initial size of the newly inserted form content item depends upon 
		whether or not there are any other content items in the content row, 
		Dlayer will attempt to predict a sensible size for you based on the 
		size of any sibling content items and any remaining space, it will 
		attempt to size the form content item to fill all the remaining space. 
		If Dlayer deems that there is not enough remaining space in the content 
		row it will set a sensible default, for form content items the default 
		is six, the form content item will automatically be sized to span half 
		the width of the content row. If the form content item is the only 
		item in the content row the same rule will be applied.</p>
	
	<p>At any time, the size and position of the form content item can be 
		managed via the size and position tab when the tool is in edit mode, 
		in edit mode you will also get access to all the other sub tools.</p>
</div>