<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div class="col-xs-12">
	<h3>Help <small>Import a form into this page</small></h3>
	
	<p>This tool allows you to import a previously generated tool from the 
		Form builder into your content page as a content item.</p>
		
	<p>The form will be wrapped in a container whose initial size depends on 
		whether or not there are other content items in the content row, the 
		form will dynamically fill the container. if the form is the only 
		item in the row the form will span the entire row, otherwise it will 
		span all the remaining space. There is a minimum suggested width, if 
		the form will be smaller than this value the form will drop down below 
		all the other content and fill the entire row, the minimum suggested 
		value is just a guide, it can be overridden manually.</p>
		
	<p>The width and position of an imported form can be managed via the 
		size and position tab when you are in edit mode, in edit mode you 
		will have access to all the other sub tools.</p>
		
	<p>To make changes to the form you need to visit the Form builder, 
		you can access this via the edit tab.</p>
</div>