<?php /** @var Dlayer_View_Codehinting */ $this ?>

<div class="col-xs-12">
	<h3>Help <small>Edit the details for the selected image</small></h3>
	
	<p>This tool allows you to edit the name, description, category and sub
		category for the selected image, all versions of this image will use 
		the new details.</p>
</div>

<div class="col-xs-12 further-reading">
	<?php echo $this->furtherReading('/#image-library'); ?>
</div>
