<?php /** @var $this Dlayer_View_Codehinting */ ?>

<script type="text/javascript">
	$(document).ready(function()
	{
		<?php if($this->div_id == NULL && $this->tool == NULL) { ?>
			dlayer.selectors.content();
		<?php } ?>
		
		<?php if($this->div_id != NULL && $this->content_id == NULL && 
			$this->tool == NULL) { ?>
			dlayer.selectors.contentItem();
			/*dlayer.movers.contentItem();*/
		<?php } ?>
		<?php if($this->div_id != NULL && $this->tool != NULL) { ?>
			/*dlayer.designers.metrics.pageContainer();*/
		<?php } ?>
		<?php if($this->div_id) { ?>
			/*dlayer.designers.metrics.contentBlocks();*/
		<?php } ?>
	});
</script>

<div id="designer">
	<div id="design">
		<?php echo $this->dlayer_page; ?>
	</div>
	<?php if(strlen($this->dlayer_toolbar) > 1) { ?>
		<div id="tools">
			<?php echo $this->dlayer_toolbar; ?>
		</div>
	<?php } ?>
	<div id="ribbon">
		<?php echo $this->dlayer_ribbon; ?>
	</div>
</div>