<?php /** @var $this Dlayer_View_Codehinting */ ?>

<script type="text/javascript">
	$(document).ready(function()
	{
		<?php if($this->div_id == NULL && $this->content_row == NULL 
			&& $this->tool == NULL) { ?>
			dlayer.selectors.contentArea();
		<?php } ?>
		
		<?php if($this->div_id != NULL && $this->content_row_id == NULL) { ?>
			dlayer.selectors.contentRow();
			dlayer.movers.contentRows();
		<?php } ?>
		
		<?php if($this->div_id != NULL && $this->content_row_id != NULL && 
			$this->content_id == NULL && 
			$this->tool['tool'] == 'content-row') { ?>
			dlayer.selectors.contentItem();			
			dlayer.movers.contentItems();
		<?php } ?>
		
		<?php if($this->div_id != NULL && $this->content_row_id != NULL && 
			$this->content_id != NULL && $this->tool != NULL && 
			$this->tool['tool'] != 'content-row') { ?>
			dlayer.selectors.contentItem();
			
			$('.row.selected-row').removeClass('selected-row');
	
		<?php } ?>
		
		// Toggles for tools section
		$('div#tools h4').click(
			function() 
			{
				var selector = this.className;
				$('div.' + selector).toggle();
				
				if($('h4.' + selector + ' > span').hasClass('glyphicon-minus')) {
					$('h4.' + selector + ' > span').removeClass('glyphicon-minus');
					$('h4.' + selector + ' > span').addClass('glyphicon-plus');
				} else {
					$('h4.' + selector + ' > span').removeClass('glyphicon-plus');
					$('h4.' + selector + ' > span').addClass('glyphicon-minus');
				}
			}
		)
		
		<?php if($this->tool != NULL && in_array($this->tool['tool'], 
			array('import-text', 'import-heading', 'import-jumbotron')) == FALSE) { ?>
		$('div#tools h4.tool-row-4').trigger('click');
		<?php } ?>
	});
</script>

<div id="designer">
	<div id="design">
		<?php echo $this->dlayer_page; ?>
	</div>
	<?php if(strlen($this->dlayer_toolbar) > 1) { ?>
		<div id="tools">
			<?php echo $this->dlayer_toolbar; ?>
		</div>
	<?php } ?>
	<div id="ribbon">
		<?php echo $this->dlayer_ribbon; ?>
	</div>
</div>