<?php /** @var $this Dlayer_View_Codehinting */?>

<script type="text/javascript">
	$(document).ready(function()
	{
		<?php if($this->page_selected === NULL) { ?>
		contentManager.pageSelector();
		<?php } ?>

		<?php if($this->page_selected !== NULL) { ?>
		contentManager.rowMover();
		contentManager.rowSelector();
		<?php } ?>

		<?php if($this->page_selected !== NULL && $this->row_id !== NULL) { ?>
		contentManager.columnMover();
		contentManager.columnSelector();
		<?php } ?>

		<?php if($this->page_selected !== NULL && $this->row_id !== NULL && $this->column_id !== NULL) { ?>
		contentManager.contentMover();
		contentManager.contentSelector();
		<?php } ?>

		contentManager.toggleRows();

		$('div.tools h4').click(
			function() 
			{
				var selector = this.className;

				$('div.' + selector).toggle();
				
				if($('h4.' + selector + ' > span').hasClass('glyphicon-minus')) {
					$('h4.' + selector + ' > span').removeClass('glyphicon-minus');
					$('h4.' + selector + ' > span').addClass('glyphicon-plus');
				} else {
					$('h4.' + selector + ' > span').removeClass('glyphicon-plus');
					$('h4.' + selector + ' > span').addClass('glyphicon-minus');
				}
			}
		);
		
		<?php if($this->tool != NULL && in_array($this->tool['tool'], 
			array('import-text', 'import-heading', 'import-jumbotron')) == FALSE) { ?>
		$('div#tools h4.tool-row-4').trigger('click');
		<?php } ?>
	});
</script>

<div id="designer">    
    <div class="row">
        <div class="col-lg-9 design designer-left">
            <?php echo $this->page; ?>
        </div>
        <div class="col-lg-3 designer-right">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 ribbon">
                    <?php if(strlen($this->ribbon) > 0)
                    {
                        echo $this->ribbon;
                    }
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>
