<?php
/** @var $this Dlayer_View_Codehinting */
?>

<script>
$(document).ready(function() {
	
	// Onclick populate data of modal dialog 
	$(".image-modal-dialog").on("click", function() {
		
		$('#imageModalDialogSrc').attr('src', $('img', this).attr('src'));
		$('#imageModalDialogLabel').html($('img', this).attr('title'));
		
		var caption = ($('p.img-caption', this).text());		
		if(caption.length > 0) {
			$('#imageModalDialogCaption').html(caption);	
		}
		
		$('#imageModalDialog').modal('show');
	});
});
</script>

<style>
/*Content font family setting, defined in settings*/
#design > div.content-manager * {
	font-family: <?php echo $this->base_font_family_content; ?>;
}

/*Form font family setting, defined in settings*/
#design > div.content-manager div.imported-form * {
	font-family: <?php echo $this->base_font_family_form; ?>;
}

/*Heading styles define in settings*/
<?php foreach($this->heading_styles as $heading) { ?>
#design > div.content-manager <?php echo $this->escape($heading['tag']); ?> {
<?php if($heading['style'] != 'normal') { ?>
	font-style: <?php echo $this->escape($heading['style']); ?>;
<?php } ?>
	font-weight: <?php echo $this->escape($heading['weight']); ?>;
<?php if($heading['decoration'] != 'none') { ?>
	text-decoration: <?php echo $this->escape($heading['decoration']); ?>;
<?php } ?>
	color: <?php echo $this->escape($heading['color']); ?>;
	font-size: <?php echo $this->escape($heading['size']); ?>px;
}
<?php } ?>

/*Styles defined in form builder*/
<?php
foreach ($this->form_styles as $form_id => $form_styles) {
	foreach($form_styles as $field_id => $field_styles) {
		if(count($field_styles) > 0) {
			echo 'div.content-manager .content-' . $form_id .
				' .field_row.row_' . $field_id . " {\r\n";
			foreach($field_styles as $style) {
				echo $style . ";\r\n";
			}
			echo "}\r\n";
		}
	}
} 
?>

</style>

<?php echo $this->contentPagePreview($this->rows, $this->columns, $this->content, $this->row_styles,
	$this->content_styles, $this->page_selected, $this->column_id, $this->row_id, $this->content_id); ?>

<div class="modal fade" id="imageModalDialog" tabindex="-1" role="dialog" 
	aria-labelledby="imageModalDialogLabel" aria-hidden="true">	
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" 
					aria-label="Close"><span aria-hidden="true">&times;</span>
				</button>
				<h4 class="modal-title" id="imageModalDialogLabel"></h4>
			</div>
			<div class="modal-body">
				<img id="imageModalDialogSrc" src="" class="img-rounded img-responsive" title="">
				<p id="imageModalDialogCaption" class="img-caption text-muted text-center small">
					
				</p>
			</div>
		</div>
	</div>
</div>
