<?php
/** @var $this Dlayer_View_Codehinting */
?>

<div class="content-manager">
    <?php echo $this->contentPage(
        $this->page_id,
        $this->rows,
        $this->columns,
        $this->content,
        $this->page_selected,
        $this->column_id,
        $this->row_id,
        $this->content_id
    )->setStyles(
        $this->styling_content_container,
        $this->styling_rows,
        $this->styling_columns,
        $this->styling_content_items
    )->setResponsiveOptions(
        $this->responsive_columns_widths
    ); ?>
</div>
