<?php
/** @var $this Dlayer_View_Codehinting */
?>

<script>
$(document).ready(function() {
	
	// Onclick populate data of modal dialog 
	$(".image-modal-dialog").on("click", function() {
		
		$('#imageModalDialogSrc').attr('src', $('img', this).attr('src'));
		$('#imageModalDialogLabel').html($('img', this).attr('title'));
		
		var caption = ($('p.img-caption', this).text());		
		if(caption.length > 0) {
			$('#imageModalDialogCaption').html(caption);	
		}
		
		$('#imageModalDialog').modal('show');
	});
});
</script>

<?php echo $this->contentPagePreview($this->page_id, $this->rows, $this->columns, $this->content)->setStyles($this->styling_page, $this->styling_rows, $this->styling_columns, $this->styling_content_items); ?>

<div class="modal fade" id="imageModalDialog" tabindex="-1" role="dialog" 
	aria-labelledby="imageModalDialogLabel" aria-hidden="true">	
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" 
					aria-label="Close"><span aria-hidden="true">&times;</span>
				</button>
				<h4 class="modal-title" id="imageModalDialogLabel"></h4>
			</div>
			<div class="modal-body">
				<img id="imageModalDialogSrc" src="" class="img-rounded img-responsive" title="">
				<p id="imageModalDialogCaption" class="img-caption text-muted text-center small">
					
				</p>
			</div>
		</div>
	</div>
</div>
