<?php
/** @var $this Dlayer_View_Codehinting */
?>

<style>
#design > div.content-manager * {
	font-family: <?php echo $this->base_font_family; ?>;
}

<?php foreach($this->heading_styles as $heading) { ?>
#designer > #page <?php echo $this->escape($heading['tag']); ?> {
	<?php if($heading['style'] != 'normal') { ?>
	font-style: <?php echo $this->escape($heading['style']); ?>;
	<?php } ?>
	font-weight: <?php echo $this->escape($heading['weight']); ?>;
	<?php if($heading['decoration'] != 'none') { ?>
	text-decoration: <?php echo $this->escape($heading['decoration']); ?>;
	<?php } ?>
	color: <?php echo $this->escape($heading['color']); ?>;
	font-size: <?php echo $this->escape($heading['size']); ?>px;
}
<?php } ?>

</style>

<?php echo $this->pagePreview($this->template, $this->content_rows, 
	$this->content, $this->template_styles, $this->content_row_styles, 
	$this->content_container_styles, $this->content_styles); ?>

<!--<div class="modal fade" id="imageModal20" tabindex="-1" role="dialog" 
	aria-labelledby="myModalLabel" aria-hidden="true">	
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" 
					aria-label="Close"><span aria-hidden="true">&times;</span>
				</button>
				<h4 class="modal-title" id="imageModal20Label">Autumn Path</h4>
			</div>
			<div class="modal-body">
				<img src="/images/library/1/1.jpg" class="content-20 img-rounded img-responsive" title="Autumn path">
				<p class="img-caption text-muted text-center small">
					Caption: This is the caption for the newly inserted image.
				</p>
			</div>
		</div>
	</div>
</div>-->