<?php /** @var $this Dlayer_View_Codehinting */ ?>

<?php 

/**
* @todo Need to update this, use database come up with a cleaner, more 
* re-usable solution
*/

$groups = array(
	1=>'', 
	2=>'Structure <small>Change the page structure</small>',
	3=>'Create <small>Create a new content item</small>',
	4=>'Import <small>Create a new content item using existing content 
	data</small>'
);

foreach($this->tools as $group_id => $group) {

	$html = '';

	foreach($group as $tool) {

		$show = FALSE;
		$selected = FALSE;
		
		switch($tool['base']) {
			case 2:
				if($this->div_id != NULL) {
					$show = TRUE;
				}			
				break;
			
			case 1:
				/**
				* Show the add content row tool if content area selected and a 
				* content row is not selected
				*/
				if($tool['tool'] == 'add-content-row' && $this->div_id != NULL &&
					$this->content_row_id == NULL) {
						
					$show = TRUE;
				}
				
				/**
				* Show the content row tool if a content area and content row 
				* is selected
				*/
				if($tool['tool'] == 'content-row' && $this->div_id != NULL &&
					$this->content_row_id != NULL && 
					$this->tool['tool'] == 'content-row') {
						
					$show = TRUE;
				}
				
				// Show move row tool if content area and content row selected
				if($tool['tool'] == 'move-row' && $this->div_id != NULL && 
					$this->content_row_id != NULL) {
						
					$show = TRUE;
				}
				
				/**
				* Show move item tool if content area, content row and 
				* content id selected
				*/
				if($tool['tool'] == 'move-item' && $this->div_id != NULL && 
					$this->content_row_id != NULL && 
					$this->content_id != NULL) {
						
					$show = TRUE;
				}
							
				break;
			
			case 0:
				if($this->div_id != NULL && $this->content_row_id != NULL) {
					$show = TRUE;
				}
				break;
				
			default:
				break;
		}
				
		// Set selected status for tool
		if($this->tool != FALSE && $this->tool['tool'] == $tool['tool']) {
			$selected = TRUE;
		}
		
		$reset = NULL;

		if($show == TRUE) {
			if($this->content_id != NULL) {
				if($tool['tool'] != 'move-item') {
					$reset = '/reset/1';
				}
			}
			
			$class = "btn btn-default";
			
			if($selected == TRUE) {
				$class = "btn btn-primary";
			}
			
			if($tool['tool'] == 'cancel') {
				$class = "btn btn-danger";
			}
			
			$html .= '<a href="/content/design/set-tool/tool/' . 
			$tool['tool'] . $reset . '"class="' . $class . '">' . 
			$tool['name'] . '</a> ';
		}
	}

	if(strlen($html) > 0) {
		echo '<div class="row">';
		echo '<div class="col-xs-12">';
		if(strlen($groups[$group_id]) > 0) {
			echo '<h4 class="tool-row-' . $group_id . '"> 
				<span class="glyphicon glyphicon-minus" 
				aria-hidden="true"></span> ' . 
				$groups[$group_id] . '</h4>';
		}
		echo '<div class="btn-group btn-group-sm tool-row-' . $group_id . 
			'" role="group">';
		echo $html;
		echo '</div>';
		echo '</div>';
		echo '</div>';
	}
} 
?>