<?php /** @var $this Dlayer_View_Codehinting */ ?>

<?php 

/**
* @todo Need to update this, use database come up with a cleaner, more 
* re-usable solution
*/

$groups = array(
	1=>'', 
	2=>'Page structure',
	3=>'Content items',
	4=>'Import tools'
);

foreach($this->tools as $group_id => $group) {

	$html = '';

	foreach($group as $tool) {

		$show = FALSE;
		$selected = FALSE;
		
		// Show cancel tool
		if($this->div_id != NULL && $tool['tool'] == 'cancel') {
			$show = TRUE;
		}
		
		// Show content row tool if div selected
		if($this->div_id != NULL && $tool['tool'] == 'content-row') {
			$show = TRUE;
		}
		
		// Show content tools if row selected
		if($this->div_id != NULL && $this->content_row_id != NULL) {
			$show = TRUE;
		}
		
		// Hide content row tool is content row selected
		if($this->div_id != NULL && $this->content_row_id != NULL 
			&& $tool['tool'] == 'content-row') {
			$show = FALSE;
		}
		
		// Set selected status for tool
		if($this->tool['tool'] == $tool['tool']) {
			$selected = TRUE;
		}
		
		$reset = NULL;

		if($show == TRUE) {
			if($this->content_id != NULL) {
				$reset = '/reset/1';
			}
			
			$class = "btn btn-default";
			
			if($selected == TRUE) {
				$class = "btn btn-primary";
			}
			
			if($tool['tool'] == 'cancel') {
				$class = "btn btn-danger";
			}
			
			$html .= '<a href="/content/design/set-tool/tool/' . 
			$tool['tool'] . $reset . '"class="' . $class . '">' . 
			$tool['name'] . '</a> ';
		}
	}

	if(strlen($html) > 0) {
		echo '<div class="row">' . PHP_EOL;
		echo '<div class="col-xs-12">' . PHP_EOL;
		echo '<div class="btn-group btn-group-sm" role="group">' . PHP_EOL;
		if(strlen($groups[$group_id]) > 0) {
			echo '<h4>' . $this->escape($groups[$group_id]) . '</h4>' . PHP_EOL;
		}
		echo $html;
		echo '</div>' . PHP_EOL;
		echo '</div>' . PHP_EOL;
		echo '</div>' . PHP_EOL;
	}
} 
?>