<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div class="image">
<img src="/images/library/1/1.jpg" width="960" height="720" title="Gradient 1" alt="Library image">
</div>

<div class="details">
    <h1>Gradient 1</h1>
    
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam varius purus et dui cursus, sit amet dapibus justo facilisis. Nullam bibendum erat at vestibulum mollis. Quisque leo quam, sodales non arcu sed, eleifend blandit nisi. Aenean facilisis posuere lacus, ut blandit ante tempor lacinia. Maecenas et purus eu dui consectetur lobortis sed sed neque. Etiam varius erat iaculis vestibulum malesuada.</p>
    
    <div class="col_1">
    <h2>Details</h2>
    <p><strong>Category</strong>: Backgrounds</p>
    <p><strong>Sub category</strong>: Gradients</p>
    <p><strong>Dimensions</strong>: 960 x 720 pixels</p>
    <p><strong>Size</strong>: 12000 bytes</p>
    <p><strong>Uploaded</strong>: 15th July 2014 15:43</p>
    <p><strong>Uploaded by</strong>: user-1@dlayer.com</p>
    </div>
    <div class="col_2">
    <h2>Version history</h2>
    <p><strong>Selected version</strong>: 1 </p>
    <p><strong>Number of versions</strong>: 1</p>
    <p><strong>Version 1</strong>:15th Jul 2014 / Add to library</p>
    </div>
    <div class="col_3">
    <h2>Usage</h2>
    <p>This version of the selected image is not currently in use by any 
    templates, widgets or content items.</p>
    </div>
</div>