<?php /** @var Dlayer_View_Codehinting */ $this ?>

<div class="row">
	<div class="col-md-12">
		<img src="/images/library/<?php echo $this->escape(
			$this->image_id); ?>/<?php echo $this->escape(
			$this->version_id); ?><?php echo $this->escape(
			$this->detail['extension']); ?>" width="<?php echo $this->escape(
			$this->detail['width']); ?>" height="<?php echo $this->escape(
			$this->detail['height']); ?>" title="<?php echo $this->escape(
			$this->detail['name']); ?>" alt="Library image" class="img-responsive">
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		<h2><?php echo $this->escape($this->detail['name']); ?></h2>
	</div>

	<div class="col-md-12">
		<p><?php echo nl2br($this->escape($this->detail['description'])); ?></p>
	</div>
	
	<div class="col-md-4">
		<h3>Details <small>Information about the image</small></h3>
		<ul class="list-unstyled">
			<li><strong>Category</strong>: <a href="/image/design/set-tool/tool/cancel"><?php echo $this->escape($this->detail['category']); ?></a></li>
			<li><strong>Sub category</strong>: <a href="/image/design/set-tool/tool/cancel"><?php echo $this->escape($this->detail['sub_category']); ?></a></li>
			<li><strong>Dimensions</strong>: <?php echo $this->escape($this->detail['width']); ?> x <?php echo $this->escape($this->detail['height']); ?> pixels</li>
			<li><strong>Size</strong>: <?php echo $this->escape($this->detail['size']); ?></li>
			<li><strong>Type</strong>: <?php echo $this->escape($this->detail['type']); ?></li>
			<li><strong>Uploaded</strong>: <?php echo $this->escape($this->detail['uploaded']); ?></li>
			<li><strong>Uploaded by</strong>: <?php echo $this->escape($this->detail['email']); ?></li>
		</ul>
	</div>
	<div class="col-md-4">
		<h3>Version history <small>Full image history</small></h3>
		<p><strong>Selected</strong>: <?php echo $this->escape($this->versions[$this->version_id]['version']); ?></p>
		<p><strong>Number of versions</strong>: <?php echo count($this->versions); ?></p>
		<ul class="list-unstyled">
		<?php foreach($this->versions as $version) { ?>
			<li><a href="/image/design/set-selected-image/image/<?php echo $this->escape($version['image_id']); ?>/version/<?php echo $this->escape($version['version_id']); ?>"><?php echo $this->escape($version['version']); ?></a>: 
				<?php echo $this->escape($version['width']); ?> x 
				<?php echo $this->escape($version['height']); ?> / 
				<?php echo $this->escape($version['size']); ?> / 
				<?php echo $this->escape($version['uploaded']); ?> / 
			<?php echo $this->escape($version['tool']); ?></li>
		<?php } ?>
		</ul>
	</div>
	<div class="col-md-4">
		<h3>Usage <small>How is this image used?</small></h3>
		<?php if($this->usage == FALSE) { ?>
			<p>This version of the selected image is not currently in use by any 
				templates, widgets or content items.</p>
			<?php } ?>
	</div>
</div>