<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div class="image">
<img src="/images/library/1/1.jpg" width="960" height="720" title="Gradient 1" alt="Library image">
</div>

<div class="details">
    <h1><?php echo $this->escape($this->detail['name']); ?></h1>
    
    <p><?php echo nl2br($this->escape($this->detail['description'])); ?></p>
    
    <div class="col_1">
    <h2>Details</h2>
    <p><strong>Category</strong>: <?php echo $this->escape($this->detail['category']); ?></p>
    <p><strong>Sub category</strong>: <?php echo $this->escape($this->detail['sub_category']); ?></p>
    <p><strong>Dimensions</strong>: <?php echo $this->escape($this->detail['width']); ?> x <?php echo $this->escape($this->detail['height']); ?> pixels</p>
    <p><strong>Size</strong>: <?php echo $this->escape($this->detail['size']); ?></p>
    <p><strong>Uploaded</strong>: <?php echo $this->escape($this->detail['uploaded']); ?></p>
    <p><strong>Uploaded by</strong>: <?php echo $this->escape($this->detail['email']); ?></p>
    </div>
    <div class="col_2">
    <h2>Version history</h2>
    <p><strong>Selected</strong>: <?php echo $this->escape($this->versions[$this->version_id]['version']); ?></p>
    <p><strong>Number of versions</strong>: <?php echo count($this->versions); ?></p>
    <?php foreach($this->versions as $version) { ?>
    <p><a href="/image/design/set-selected-image/image/<?php echo $this->escape($version['image_id']); ?>/version/<?php echo $this->escape($version['version_id']); ?>"><?php echo $this->escape($version['version']); ?></a>: 
    <?php echo $this->escape($version['width']); ?> x 
    <?php echo $this->escape($version['height']); ?> / 
    <?php echo $this->escape($version['size']); ?> / 
    <?php echo $this->escape($version['uploaded']); ?> / 
    <?php echo $this->escape($version['tool']); ?></p>
    <?php } ?>
    
    </div>
    <div class="col_3">
    <h2>Usage</h2>
    <p>This version of the selected image is not currently in use by any 
    templates, widgets or content items.</p>
    </div>
</div>