<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div id="designer">
    <section id="library">
        <?php echo $this->dlayer_library; ?>
    </section>
    <?php if($this->image_id == NULL) { ?>
    <section id="filter">
        <?php echo $this->filter_form; ?>
    </section>
    <?php } ?>
    <?php if(strlen($this->dlayer_toolbar) > 1) { ?>
    <section id="tools">
        <?php echo $this->dlayer_toolbar; ?>
    </section>
    <?php } ?>
    <section id="ribbon">
        <?php echo $this->dlayer_ribbon; ?>
    </section>
</div>

<script type="text/javascript">
dlayer.tools.image.fn.sub_categories_filter();
</script>
