<?php /** @var $this Dlayer_View_Codehinting */ ?>

<h1>Image library - Filter: Backgrounds/Misc.</h1>

<?php foreach($this->images as $row) { ?>
<div class="row">
    <?php foreach($row as $image) { ?>
    <div id="image_<?php echo $this->escape($image['image_id']); ?>" 
    class="container">
        <div class="image"></div>
        <div class="row">
            <div class="title"><?php echo $this->escape(
            $image['name']); ?></div>
        </div>
        <div class="row">
            <div class="size"><?php echo $this->escape(
            $image['size']); ?></div>
            <div class="uploaded"><?php echo $this->escape(
            $image['uploaded']); ?></div>
        </div>
    </div>
    <?php } ?>
</div>
<?php } ?>