<?php /** @var Dlayer_View_Codehinting */ $this ?>

<div class="library">
	<div class="row">
		<div class="col-md-12">
			<h2><?php echo $this->escape(
					$this->title['category']['name']); ?>
				<?php if($this->title['category']['name'] != Dlayer_Config::IMAGE_LIBRARY_DEFAULT_CATEGORY) { ?>
					<small><a title="Edit category" href="/image/design/set-tool/tool/category/edit/1">[Edit]</a></small>
					<?php } ?>/ <?php echo $this->escape($this->title['sub_category']['name']); ?> 
				<?php if($this->title['sub_category']['name'] != Dlayer_Config::IMAGE_LIBRARY_DEFAULT_SUB_CATEGORY) { ?> 
					<small><a title="Edit sub category" href="/image/design/set-tool/tool/subcategory/edit/1">[Edit]</a></small>
					<?php } ?>
			</h2>
		</div>
	</div>
    <div class="row">
		<?php if(count($this->images) > 0) { ?>
			<div class="col-md-6 col-xs-12">
				<div class="btn-toolbar">
					<div class="btn-group">
						<?php if($this->sort != 'name') { ?>
							<a title="Sort by name" href="/image/design/set-sort/sort/name" class="btn btn-default btn-sm">Name</a>
						<?php } else { ?>
							<a title="Sorted by name" href="#" class="btn btn-primary btn-sm">Name</a>
						<?php } ?> 
						<?php if($this->sort != 'size') { ?>
							<a title="Sort by size" href="/image/design/set-sort/sort/size" class="btn btn-default btn-sm">Size</a>
						<?php } else { ?>
							<a title="Sorted by size" href="#" class="btn btn-primary btn-sm">Size</a>
						<?php } ?> 
						<?php if($this->sort != 'uploaded') { ?>
							<a title="Sort by date uploaded to library" href="/image/design/set-sort/sort/uploaded" class="btn btn-default btn-sm">Uploaded</a>
						<?php } else { ?>
							<a title="Sorted by date uploaded to library" href="#" class="btn btn-primary btn-sm">Uploaded</a>
						<?php } ?> 
					</div>
					<div class="btn-group">
						<?php if($this->sort_order != 'asc') { ?>
							<a title="Display in ascending order" href="/image/design/set-sort/order/asc" class="btn btn-default btn-sm">Asc.</a>
						<?php } else { ?>
							<a title="Displayed in ascending order" href="#" class="btn btn-primary btn-sm">Asc.</a>
						<?php } ?> 
						<?php if($this->sort_order != 'desc') { ?>
							<a title="Display in descending order" href="/image/design/set-sort/order/desc" class="btn btn-default btn-sm">Desc.</a>
						<?php } else { ?>
							<a title="Displayed in descending order" href="#" class="btn btn-primary btn-sm">Desc.</a>
						<?php } ?>
					</div>
				</div>
			</div>
		<?php } ?>	

		<?php if($this->images_count > Dlayer_Config::IMAGE_LIBRARY_THUMB_PER_PAGE) { ?>
			<div class="col-md-6 col-xs-12 small">
			<?php echo $this->bootstrapPagination($this->per_page, $this->start, 
				$this->images_count, '/image/design/index', 1, 'Previous', 'Next', 
				'Image', 'Images'); ?>
			</div>
		<?php } ?>
	</div>

	<?php if(count($this->images) > 0) { ?>
		<?php foreach($this->images as $row) { ?>
			<div class="row" style="padding-top:1.5em;">
				<?php foreach($row as $image) { ?>
					<div class="col-md-2 col-sm-4 col-xs-12" style="margin-bottom:0.5em;" id="image_<?php echo $this->escape($image['image_id']); ?>">
						<div class="row">
							<div class="col-xs-12" style="margin-bottom:0.5em;">
								<a href="/image/design/set-selected-image/image/<?php echo $this->escape(
										$image['image_id']); ?>/version/<?php echo $this->escape(
										$image['version_id']); ?>">
									<img src="/images/library/<?php echo $this->escape(
											$image['image_id']); ?>/<?php echo $this->escape(
											$image['version_id']); ?><?php echo $this->escape(
											$image['extension']); ?>" title="<?php echo $this->escape(
											$image['name']); ?>" alt="Image library image" 
                                            class="img-thumbnail img-responsive" /></a>
							</div>
							<div class="col-xs-12" style="margin-bottom:0.5em;">
								<a title="Select image and go to detail view" 
									href="/image/design/set-selected-image/image/<?php echo $this->escape(
										$image['image_id']); ?>/version/<?php echo $this->escape(
										$image['version_id']); ?>" class="btn btn-primary btn-xs">
									<?php echo $this->escape(
									$image['name']); ?> <span title="Number of versions" class="badge"><?php echo $this->escape(
									$image['versions']); ?></span></a>
							</div>
							<div class="col-xs-12 small" title="Size">Size: <?php echo $this->escape(
								$image['size']); ?></div>
							<div class="col-xs-12 small" title="Date uploaded to library">Uploaded: <?php echo $this->escape(
								$image['uploaded']); ?></div>
							<div class="clearfix visible-xs-block"></div>
						</div>
					</div>
				<?php } ?>
			</div>
		<?php } ?>
	<?php } else { ?>
		<div class="row">
			<div class="col-md-12">
				<p>There are no images to display, add an image to your Image
					library using the <mark>add to library</mark> tool.</p>
			</div>
		</div>
	<?php } ?>
</div>