<?php /** @var $this Dlayer_View_Codehinting */ ?>

<?php 

foreach($this->tools as $group) {
    
    $html = '';
    
    foreach($group as $tool) {
        
        $show = FALSE;
        $selected = FALSE;
        
        if($this->image_id == NULL) { 
            if($tool['tool'] != 'cancel' && $tool['base'] == 1) {
                $show = TRUE;
            } else {
                if($this->tool != FALSE && $tool['tool'] == 'cancel') {
                    $show = TRUE;
                }
            }
        } else {
            $show = TRUE;
        }
        
        if($this->tool['tool'] == $tool['tool']) {
            $selected = TRUE;
        }
                        
        if($show == TRUE) {            
            if($selected == FALSE) {
                $html .= '<div class="tool">';
            } else {
                $html .= '<div class="tool selected">';
            }
            
            $html .= '<a href="/image/design/set-tool/tool/' . 
            $tool['tool'] . '">' . $tool['name'] . '</a></div>' . 
            PHP_EOL;
        }
    }
    
    if(strlen($html) > 0) {
        echo '<div class="group">' . PHP_EOL;
        echo $html;
        echo '</div>' . PHP_EOL;
    }
}  
?>