<?php /** @var Dlayer_View_Codehinting */ $this ?>

<?php 
foreach($this->tools as $group) {
    
    $html = '';
    
    foreach($group as $tool) {
        
        $show = FALSE;
        $selected = FALSE;
               
        if($this->tool == FALSE) {
			if($this->image_id == NULL) {
				if($tool['base'] == 1) {
					$show = TRUE;
				}
			} else {
				if($tool['base'] == 0) {
					$show = TRUE;
				}
			}
        } else {
        	if($this->image_id == NULL) {
				if($tool['base'] == 1 || $tool['tool'] == 'cancel') {
					$show = TRUE;
				}
			} else {
				if($tool['base'] == 0 || $tool['tool'] == 'cancel') {
					$show = TRUE;
				}
			}
        }
        
        if($this->tool['tool'] == $tool['tool']) {
            $selected = TRUE;
        }
        
        if($show == TRUE) {
            $class = "btn btn-default";
            
            if($selected == TRUE) {
                $class = "btn btn-primary";
            }
            
            if($tool['tool'] == 'cancel') {
                $class = "btn btn-danger";
            }
            
            $html .= '<a href="/image/design/set-tool/tool/' . 
            $tool['tool'] . '"class="' . $class . '">' . 
            $tool['name'] . '</a> ';
        }
    }
    
    if(strlen($html) > 0) {
    	echo '<div class="row"><div class="col-xs-12">';
        echo '<div class="btn-group btn-group-sm" role="group">';
        echo $html;
        echo '</div></div></div>';
    }
}  
?>