<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div id="tab_content_1" class="content open">
    <h2>Welcome to the Dlayer Template designer.</h2>
    
    <p>Select the block that you want to work on, if the block is selectable 
    it will highlight when you hover the mouse over it, click the left mouse 
    button to select the block.</p>
    
    <p>Once you have selected a block the tools that can be used on that block 
    will be shown in the tools section.</p>
</div>