<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div class="row">
	<div class="col-xs-12">
		<h2>Welcome to the Template designer</h2>
		
		<h4><span class="glyphicon glyphicon-play" aria-hidden="true"></span> 
		Select a content area to begin</h4>
		
		<p>To use any of the tools in the Template designer you first need 
			to select a content area. If a content area is selectable it will 
			highlight when you hover the mouse over it, to select the area 
			simply click the left mouse button.</p>
		
		<p>Once you have selected a content area the tools that can be used 
			upon the area will be shown in the tools section.</p>
		
		<p class="dev-note bg-info">The height setting for all content area 
			is dynamic by default, they will automatically resize themselves 
			to their content. Content areas will appear to have a fixed height 
			in both the Template designer and Content manager so that they 
			are selectable. The height setting for a content area can be 
			toggled by expanding the metrics section below the tool bar.</p>
	</div>
</div>