<?php /** @var Dlayer_View_Codehinting */ $this ?>

<div class="row">
	<div class="col-xs-12">
		<h2>Content area selected</h2>
		
		<h4><span class="glyphicon glyphicon-play" aria-hidden="true"></span> 
		Now select a design tool</h4>
		
		<h4><span class="glyphicon glyphicon-play" aria-hidden="true"></span> 
		Toggle the height setting</h4>
		
		<p>Select a design tool from the tool bar, once you have selected a 
			tool the side bar will update to show all the options for the 
			selected tool.</p>
		
		<p>To switch the height setting for the content area expand the 
			metrics section and use the toggle button.</p>
		
		<p class="dev-note bg-info">If the content area is being used by a 
			content page and has one of more content items attached it there 
			will be a visual representation in your design an access to 
			certain tools will be limited.</p>
	</div>
</div>