<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div class="row">
	<div class="col-xs-12">
		<h2>Content block selected <small>Now select a design tool</small></h2>
	</div>

	<div class="col-xs-12">
		<p>Now that you have selected a content block you can choose a 
			design tool, once you have selected a tool this section will be 
			updated to show the option tab and options for the selected 
			tool.</p>
			
		<p class="dev-note bg-info">If this template is being used by an 
			active content page and the selected content block has had one or 
			more content items attached to it there will be visual 
			representation in your design.</p>
	</div>
</div>