<?php /** @var Dlayer_View_Codehinting */ $this ?>

<div class="col-xs-12">
	<h3>Help <small>Create a password form field</small></h3>

	<p>This tool allows you to quickly add a password field to your form, the 
		password field is a password field with the values and options 
		preset.</p>

	<p>After addition all the values and options can be changed, the field 
		will behave as per a standard password field because that is actually 
		what it is after addition.</p>
</div>