<?php /** @var Dlayer_View_Codehinting */ $this ?>

<div class="col-md-12 col-sm-12">
	<h3>Help <small>Add password field</small></h3>

	<p>This tool allows you to quickly add a password field to your form, a 
		password field is simply a password field where the options are already 
		set.</p>
		
	<p>Once the password field has been added to your form you can edit it as 
		you would any password field, all the options are configurable.</p>	
</div>

<div class="col-md-12 col-sm-12 further-reading">
	<?php echo $this->furtherReading('/#form-builder'); ?>
</div>
