<?php /** @var Dlayer_View_Codehinting */ $this ?>

<style>
	.ribbon form legend {
		display: none;
	}
	.ribbon form .form-group {
		display: none;
	}
	.ribbon form .form-group-submit {
		display: block;
	}
</style>

<div class="col-xs-12">
	<h3>Add <small>Password field</small></h3>

	<p>Click <mark>Add password field</mark> to add a password field to your 
		form, the options have all been preset, you can change them later if 
		required.</p>
</div>

<div class="col-xs-12">
	<?php 
	if($this->data != FALSE) {
		echo $this->data['form'];
	}
	?>
</div>