<?php /** @var Dlayer_View_Codehinting */ $this ?>

<?php 
$edges = array();
$edges[] = array('icon'=>'border-full-1px.png', 
                 'title'=>'Thin', 
                 'description'=>'Add a thin border all the way around the 
                 selected block.', 
                 'position'=>'full',
                 'width'=>1, 
                 'color_hex'=>'#000000');
$edges[] = array('icon'=>'border-full-2px.png', 
                 'title'=>'Medium', 
                 'description'=>'Add a medium border all the way around the 
                 selected block.', 
                 'position'=>'full', 
                 'width'=>2, 
                 'color_hex'=>'#000000');
$edges[] = array('icon'=>'border-full-5px.png', 
                 'title'=>'Thick', 
                 'description'=>'Add a thick border all the way around the 
                 selected block.', 
                 'position'=>'full', 
                 'width'=>5, 
                 'color_hex'=>'#000000');
?>

<?php echo $this->colorPicker()->picker($this->color_picker_data['palettes'], 
$this->color_picker_data['history']); ?>

<?php foreach($edges as $k=>$edge) { ?>
<div class="block">
    <div class="image">
    <img src="/images/ribbon/template/<?php echo $this->escape($edge['icon']); ?>" 
    width="60" height="40" /></div>
    <div class="content">
        <div class="title"><?php echo $this->escape($edge['title']); ?></div>
        <div class="text"><?php echo $this->escape($edge['description']); ?></div>
    </div>
    <form action="/template/process/auto-tool" method="post">
        <input type="hidden" name="id" value="<?php echo $this->escape($this->div_id); ?>" />
        <input type="hidden" name="tool" value="border" />
        <input type="hidden" name="params[multi_use]" value="<?php echo $this->escape($this->multi_use); ?>" />
        <input type="hidden" name="params[position]" 
        value="<?php echo $this->escape($edge['position']); ?>" />
        <select name="params[style]">
            <?php foreach($this->data['styles'] as $style=>$name) { ?>
            <option value="<?php echo $this->escape($style); ?>" 
            label="<?php echo $this->escape($name); ?>">
            <?php echo $this->escape($name); ?></option>
            <?php } ?>
        </select>
        <input type="hidden" name="params[width]" class="int_3" size="3" 
        maxlength="3" value="<?php echo $this->escape($edge['width']); ?>" />
        <input type="hidden" id="color_hex_<?php echo $k; ?>" 
        name="params[color_hex]" size="7" maxlength="7" 
        value="<?php echo $this->escape($edge['color_hex']); ?>" />
        <div class="color_picker" id="picker_color_hex_<?php echo $k; ?>" 
        style="background-color:<?php echo $this->escape($edge['color_hex']); ?>;">&nbsp;</div>
        <input type="submit" class="submit" name="submit" value="Go" />
    </form>
</div>
<?php } ?>

<div class="block">
    <div class="image">
    <img src="/images/ribbon/template/border-full-clear.png" width="60" 
    height="40" /></div>
    <div class="content">
        <div class="title">Clear</div>
        <div class="text">Clear all the defined borders for the selected 
        block.</div>
    </div>
    <form action="/template/process/auto-tool" method="post">
        <input type="hidden" name="id" value="<?php echo $this->escape($this->div_id); ?>" />
        <input type="hidden" name="tool" value="border" />
        <input type="hidden" name="params[multi_use]" value="<?php echo $this->escape($this->multi_use); ?>" />
        <input type="hidden" name="params[position]" value="full" />
        <input type="hidden" name="params[style]" value="none" />
        <input type="hidden" name="params[width]" class="int_3" size="3" 
        maxlength="3" value="0" />
        <input type="hidden" name="params[color_hex]" class="color" size="7" 
        maxlength="7" value="#000000" />
        <input type="submit" class="submit no_fields" name="submit" value="Go" />
    </form>
</div>

<?php echo $this->colorPicker()->javascript(); ?>