<?php /** @var Dlayer_View_Codehinting */ $this ?>

<h2>Set borders</h2>

<p>This tool allows you to set the border for the selected template block.</p>

<p>You can define a border for all edges in one go, choosing the style and 
colour or you can define individual borders using the custom tab.</p>

<p>If required the modifier system will be called after the tool has 
processed to update the size of an content items that may have been affected 
by the change.</p>