<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div class="col-xs-12">
	<h3>Help <small>Create a new text item using existing content</small></h3>
	
	<p>This tool allows you to create a new text content item using existing 
		content from an earlier text content item. Simply select the content 
		to import, a preview will be shown to allow you to confirm that you 
		are selecting the correct content.</p>
	
	<p>The initial size of a text content item depends on whether or not 
		there are other content items in the content row, if the text item 
		is the only item in the  row the content will span the entire row, 
		otherwise it will span all the remaining space. There is a minimum 
		suggested width, if the content item will be smaller than this value 
		the content item will drop down below all the other content and fill 
		the entire row, the minimum suggested value is just a guide, it can 
		be overridden manually.</p>
</div>
