<?php /** @var $this Dlayer_View_Codehinting */ ?>

<h2>Import an existing text content item</h2>

<p>This tool allows you to create a new text content item using an existing 
piece of text data. When creating a text item using this tool you select some 
existing text to use and then define the content container settings as per 
the text tool.</p>

<p>Once a new text content item has been created using this tool it becomes 
a standard text item which will be editable using the text tool.</p>
