<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div class="col-xs-12">
	<h3>Help <small>Create a new text item using existing content</small></h3>
	
	<p>This tool allows you to create a new text content using existing 
		content from an earlier text content item. Simply select the content 
		to import and preview will be shown to allow you to confirm that you 
		are selecting the correct content.</p>
	
	<p>The initial size of the newly created text content item depends on 
		whether or not there are other content items in the row, if the text 
		item is the only item the content will span the entire row, otherwise 
		it will span all the remaining space. If there is not enough space 
		for the text content item it will drop down below the other content 
		items.</p>
</div>
