<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div class="col-xs-12">		
	<h3>Content row selected <small>Manage the row, select a content item 
		to edit or add a new content item</small></h3>
		
	<p>To manage the properties for this content row select a sub tool using 
		the tabs shown above</p> 
	
	<p>To edit a content item please click to selected, the tool and ribbon 
		area will update to show the edit controls for the selected content 
		item.</p>
		
	<p>To add a brand new content item to the selected row click the tool 
		that corresponds to the content item you want to create.</p>
</div>