<?php /** @var Dlayer_View_Codehinting */ $this ?>

<div class="col-md-12 col-sm-12">
	<h3>Help <small>Content row</small></h3>
	
	<p>A content row is an invisible container that spans the entire width of 
		a content area, it is used primarily to control the layout and size 
		of the content items it contains.</p>
		
	<p>Dlayer uses a HTML, CSS, and JS framework called Bootstrap, content 
		rows in Dlayer are called rows in Bootstrap. Bootstrap is a very 
		clever system that splits each row into a number of columns, these 
		can then be used for sizing and positioning, Dlayer builds upon 
		this.</p>
		
	<p>There are twelve columns to a content row, when a content item is 
		created a sensible size is initially set by Dlayer, Dlayer looks at 
		the type of item being created and how many other items there are in 
		the row, refer to each tool to see how Dlayer calculates the initial 
		size.</p>
</div>

<div class="col-md-12 col-sm-12 further-reading">
	<?php echo $this->furtherReading('/#content-manager'); ?>
</div>
