<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div class="col-xs-12">		
	<h3>Help <small>Content row</small></h3>
	
	<p>Content rows are invisible containers for content items, they span the 
		entire content area and allow you to line up multiple content items. 
		You can add one or more content items to a row and the content items 
		don't need to span the entire row.</p>
	
	<p>Initially, new content items will span the entire width of the row, 
		to alter this use the sizing tab when editing the content item.</p>
</div>