<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div class="row">
	<div class="col-md-12">
		<h1>Bugs <small>Known bugs</small></h1>
		
		<p>Dlayer is an alpha level product, although every intention is made to 
			ensure nothing slips through there are going to be bugs as I develop the 
			system.</p>

		<p>Listed below are the known bugs to date, some will be because I 
			failed to account for every possibility, some because I just made a 
			mistake and some because I haven't yet finished the section in 
			question, fixed bugs will stick around on the page for a little while.</p>

		<p>There will probably always be a few bugs, I will fix bugs either based 
			on their severity or based on the development plan.</p>

		<hr />

		<h3>Content width modifier: Affects Template designer and Content 
			manager.</h3>

		<p>The Template designer calls the modifier system when the page block 
			being edited has active content on an page based upon the selected 
			template.</p>

		<p>If a user modifies the width of a page block to the left or right of 
			a page block that has content the size of the page block with content is 
			affected. Even though the page block with content is altered the 
			modifier system isn't currently being called. This will be rectified 
			in a future update, I'll update the relevant tools to call the modifier 
			when a sibling block could be affected.</p>

		<h3><s>Import form: Affects Content manager</s></h3>

		<p class="bg-success dev-note">(Fixed in release v0.41)</p>

		<p>The approximate or absolute width of a form isn't currently being 
			calculated by Dlayer, as such it is possible to import a form into a 
			page block that is not big enough to contain it.</p>

		<p>In a future update the tool will only display forms that can fit 
			into the requested page block based on the layout options defined for 
			the form.</p>

		<p class="bg-info dev-note">The import form tool has been updated to stop a 
			user importing a form into a page container which is too small for it.</p>

		<p class="bg-info dev-note">The submit button on the import form is disabled 
			when the selected form won't fit, a message is also shown to the user. 
			When submitted the tool checks the page container against the current 
			minimum width of the form and also the requested padding.</p>

		<h3><s>Live preview: Affects Form builder and Content manager</s></h3>

		<p class="bg-success dev-note">(Fixed in release v0.36)</p>

		<p>Changes made by the live preview functions aren't reset when a user 
			switches tool tabs.</p>

		<p>The tool tabs are loaded via AJAX and populated with the most 
			current data in the database, they don't look at the current state of 
			the designer and pull the current values.</p>

		<p>I can either update the tool tab AJAX to look at current designer 
			data and update accordingly or reset preview function of tab switch.</p>

		<p>I will probably opt for the reset because there is lots of 
			complexity behind each of the tool tabs, later when live editing is 
			developed the tool tabs will work in unison.</p>

		<p class="bg-info dev-note">Unsaved changes are reset when the user switches 
			tool tabs.</p>

		<h3>Content width modifier: Affects Template designer and Content 
			manager.</h3>

		<p>The content width modifier needs to be updated to honour the 
			validation rules used by the import form tool, currently although you 
			can't import a form into a container that is too small for it you can 
			resize the container below the forms set minimum width.</p>

		<hr />

		<p>If you find any bugs not listed please let me know via my 
			<a href="http://www.g3d-development.com/blog/">blog.</a></p>
	</div>
</div>