<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div class="row">
	<div class="col-md-12 col-xs-12">
		<h1>Bugs <small>The nasty critters bring down my app quality</small></h1>
		
		<p>Dlayer is an alpha level product, I'm attempting to ensure that 
			nothing slips through testing but obviously there are going to be 
			bugs.</p>
		
		<p>Listed below are all the known bugs, both open and closed. Bugs 
			occur for a number of reasons, I might have made a mistake, I 
			might have failed to account for every possibility with a 
			feature or I might not yet have finished a feature knowing that 
			I will be going back to rework on it.</p>
		
		<p class="dev-note bg-info">If you find any bugs that aren't listed 
			here please let me know via my blog or email me at 
			dean (at) g3d-development (dot) com.</p>
			
		<h2>Open bugs <small>Still to fix</small></h2>
		
		<p>The bugs listed below are open, I will fix them either based on 
			their severity or based upon whether the feature is due to be 
			worked on soon in my development plan.</p>
		
		<p>There are currently no open bugs, this isn’t because I am 
			awesome, I've just been through a large refocus and to date 
			haven't spotted any bugs.</p>
			
		<h4>Selectors <small>Designer: Content manager - 
			Filed: 2nd March 2015</small></h4>
		
		<p>Two colours are used when selecting items in the content manager, 
			yellow for a selected item and blue for a selectable child item 
			on hover.</p>
			
		<p>When a background colour is defined for a content container or 
			content item the selector function doesn’t override the items 
			background colour meaning it can be difficult to work out which 
			item or type of item is being selected.</p>
		
		<h2>Closed bugs <small>Either squished or no longer 
			an issue</small></h2>
		
		<p>The bugs listed below are all closed, they have either been fixed 
			or are no longer applicable due to a change in how Dlayer 
			works.</p>
			
		<h4>Nothing here yet!</h4>
	</div>
</div>