<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div class="row">
	<div class="col-md-12 col-xs-12">
		<h1>Development plan <small>Plan of attack</small></h1>
		
		<p>The development plan for Dlayer exists in my head, the 
			specifications, OneNote and all over the white board in my man 
			cave, it is structured towards getting Dlayer into a position 
			where a user will be able to create a simple multi-page web site 
			with minor dynamic functionality. As soon as I have added enough 
			functionality to the Template designer, Content manager, Form 
			builder and Web site manager to achieve this goal I will dedicate 
			my time towards filling out the Content manager and Form 
			builder.</p>
		
		<p class="dev-note bg-info">This is a rolling list of the features 
			in my short term to do list, it will be updated periodically as 
			features are completed, I’m not going to detail my long term 
			development plans.</p>
		
		<p>The development of the Widget designer will always lag behind 
			the other designers, the Widget designer is an incredibly 
			complicated system because in addition to allowing dynamic 
			functionality it is in effect an amalgamation of all the 
			other designers.</p>
			
		<h2>Template designer <small>To do list for Template designer</small></h2>
		
		<h4>Background image</h4>
		
		<p>Need to allow the user to define a background image for a 
			content area.</p>
		
		<h4>Content area background styling</h4>
		
		<p>Need to allow the user to define the styling for a content area, 
			initially background colour.</p>
		
		<h2>Content manager <small>To do list for Content manager</small></h2>
		
		<h4><s>Move content items</s></h4>
		
		<p>Need to allow the user to move content items, initially within a 
			content row using visual controls and then using a tool to move a 
			content item from one row to another.</p>
			
		<p class="dev-note bg-success">Added ability to modify the sort order 
			for content items within a content row in v0.60</p>
			
		<p class="dev-note bg-success">Added ability to move content items to 
			another content row in v0.63</p>
		
		<h4>Delete content row</h4>
		
		<p>Need to allow the user to delete a content row, content items are 
			also deleted but only the definition data, the actual data for 
			each content item will be stored in the relevant reference 
			tables.</p>
		
		<h4>Delete content item</h4>
		
		<p>Need to allow the user to delete a content item, only the 
			definition of the content item is deleted, the actual data will 
			still persist in the reference tables.</p>
		
		<h4><s>Content item position</s></h4>
		
		<p>Need to allow the user to define the offsetting for a content 
			item.</p>
			
		<p class="dev-note bg-success">Added ability to define offset as a 
			value between 0 and 12 in v0.62</p>
		
		<h4><s>Move content rows</s></h4>
		
		<p>Need to allow the user to move content rows between content 
			areas.</p>
			
		<p class="dev-note bg-success">Added move row tool in v0.63. In 
			addition to moving the content row it also runs acleanup method 
			on the content area the row moves from.</p>
		
		<h4><s>Import heading</s></h4>
		
		<p>Need to return the import heading tool, this tool allows a 
			user to effectively duplicate an existing heading content item.</p>
			
		<p class="dev-note bg-success">Tool added in v0.61</p>
		
		<h4><s>Import text</s></h4>
		
		<p>Need to return the import text tool, the tool allows a user 
			to effectively duplicate an existing text content item.</p>
			
		<p class="dev-note bg-success">Tool added in v0.61</p>
		
		<h4><s>Import jumbotron</s></h4>
		
		<p>Need to allow the user to import a jumbotron.</p>
			
		<p class="dev-note bg-success">Tool added in v0.62</p>
		
		<h4>Live previews</h4>
		
		<p>Need to add live previews back into the Content manager as in 
			the Form builder, shows changes live in the designer view when 
			changes are made in the tool section.</p>
		
		<h4>Image content item</h4>
		
		<p>Need to allow the user to import an image from the image library, 
			caption, description and type all definable options.</p>
		
		<h4>Content item background image</h4>
		
		<p>Need to allow the user to define a background image for a 
			content item</p>
		
		<h4><s>Content container styling</s></h4>
		
		<p>Need to allow the user to define the styling for a content item 
			container, initially the background colour.</p>
			
		<p class="dev-note bg-success">Added ability to define container 
			background colour in v0.58</p>
		
		<h4><s>Content item styling</s></h4>
		
		<p>Need to allow the user to define the styling for a content item, 
			initially the background colour.</p>
			
		<p class="dev-note bg-success">Added ability to define content item  
			background colour in v0.59</p>
			
		<h4><s>Jumbotron content item</s></h4>
		
		<p>Add the jumbotron content item to the Content manager, a jumbotron 
			is a masthead for a page, initially only allow user to define 
			title and sub title, add support later for buttons.</p>
			
		<p class="dev-note bg-success">Added ability to create a jumbotron, 
			initially just a title and sub title in v0.59</p>
			
		<p class="dev-note bg-success">Added styling and position tabs to 
			Jumbotron tool in v0.60</p>
		
		<h4>Content row styling</h4>
		
		<p>Need to allow the user to define the styling for a content row, 
			initially the background colour.</p>
		
		<h4>Store item</h4>
		
		<p>Need to allow a user to store an item in a temporary scratch 
			pad.</p>
		
		<h2>Form builder <small>To do list for Form builder</small></h2>
		
		<h4>Elements</h4>
		
		<p>Add the missing element types, select, file, radio, hidden, 
			colour and number to the Form builder.</p>
		
		<h4>Preset tools</h4>
		
		<p>Add additional preset tools, for example salutation, address and 
			postcode.</p>
	</div>
</div>