<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div class="row">
	<div class="col-md-12 col-xs-12">
		<h1>Development plan <small>Plan of attack</small></h1>
		
		<p>The development plan for Dlayer exists in my head, the 
			specifications, OneNote and all over the white board in my man 
			cave, it is structured towards getting Dlayer into a position 
			where a user will be able to create a simple multi-page web site 
			with minor dynamic functionality. As soon as I have added enough 
			functionality to the Template designer, Content manager, Form 
			builder and Web site manager to achieve this goal I will dedicate 
			my time towards filling out the Content manager and Form 
			builder.</p>
		
		<p class="dev-note bg-info">This is a rolling list of the features 
			in my short term to do list, it will be updated periodically as 
			features are completed, I'm not going to detail my long term 
			development plans.</p>
		
		<p>The development of the Widget designer will always lag behind 
			the other designers, the Widget designer is an incredibly 
			complicated system because in addition to allowing dynamic 
			functionality it is in effect an amalgamation of all the 
			other designers.</p>
			
		<p><b>-- Last updated: 30th May 2015</b></p>
			
		<h2>Widget designer <small>To do list for Widget designer</small></h2>
		
		<h4>Preview</h4>
		
		<p>Get a preview of the Widget designer in place.</p>
			
		<h2>Template designer <small>To do list for Template designer</small></h2>
		
		<h4>Background image</h4>
		
		<p>Need to allow the user to define a background image for a 
			content area.</p>
		
		<h4>Content area background styling</h4>
		
		<p>Need to allow the user to define the styling for a content area, 
			initially background colour both solid colour and a gradient.</p>
		
		<h2>Content manager <small>To do list for Content manager</small></h2>
		
		<h4>Delete content row</h4>
		
		<p>Need to allow the user to delete a content row, content items are 
			also deleted but only the definition data, the actual data for 
			each content item will be stored in the relevant reference tables.</p>
		
		<h4>Delete content item</h4>
		
		<p>Need to allow the user to delete a content item, only the 
			definition of the content item is deleted, the actual data will 
			still persist in the reference tables.</p>
		
		<h4><s>Image picker</s></h4>
		
		<p>Need to develop the image picker for the add image tool.</p>
		
		<p class="dev-note bg-success">Added in version 0.74, still some work 
			to do on making it as reusable as the colour picker.</p>
		
		<h4>Content item background image</h4>
		
		<p>Need to allow the user to define a background image for a 
			content item.</p>
		
		<h4>Save item</h4>
		
		<p>Need to allow a user to save an item, saved items can be used as 
			the basis for Widget development.</p>
		
		<h2>Form builder <small>To do list for Form builder</small></h2>
		
		<h4>Elements</h4>
		
		<p>Add the missing element types, select, file, radio, hidden, 
			colour and number to the Form builder.</p>
		
		<h4>Preset tools</h4>
		
		<p>Add additional preset tools, for example salutation, address and 
			postcode.</p>
			
		<h4>Settings</h4>
		
		<p>Rework form settings, need actions, layout and setting tools.</p>
		
		<p class="dev-note bg-success">v0.76 - Added layout settings tool.</p>
	</div>
</div>