<?php /** @var Dlayer_View_Codehinting */ $this ?>

<div class="row">
	<div class="col-md-12 col-xs-12">
		<h1>Development log <small>Work to date</small></h1>
		
		<p>The list below shows some of the development updates for 
			Dlayer.com, it is far from exhaustive, it is just a few of the 
			changes from my SVN and GIT commits, not actual commit comments 
			but the result of one or more.</p>

		<p>I'm not hiding the rest of the updates, they just wouldn't mean 
			anything to the reader, they are either trivial, house keeping, 
			efactoring or changes to the base system or currently hidden 
			parts of Dlayer.</p>

		<p>The list below is only intended to give you an idea of how 
			development is progressing.</p>

		<?php echo $this->bootstrapPagination($this->per_page, $this->start, 
			$this->updates_count, '/dlayer/index/development-log', 2); ?>
			
		<table class="table table-hover">
			<tr>
				<th class="col-md-2 col-xs-4">Date of change</th>
				<th class="col-md-10 col-xs-8">Change, Improvment or Fix</th>
			</tr>
			
			<?php foreach($this->updates as $update) { ?>
			
			<?php
			switch($update['release']) {
				case 1:
					$class = ' class="info"';
					$append = '<span class="label label-success">Release</span> ';
				break;
				
				case 2:
					$class = NULL;
					$append = '<span class="label label-danger">Bug</span> ';
				break;
				
				default:
					$class = NULL;
					$append = NULL;	
				break;				
			}			
			?>

			<tr<?php echo $class; ?>>
				<td><?php echo $this->escape($update['change_date']); ?></td>
				<td><?php echo $append . $this->escape($update['change']); ?></td>
			</tr>
			<?php } ?>
		</table>
		
		<?php echo $this->bootstrapPagination($this->per_page, $this->start, 
			$this->updates_count, '/dlayer/index/development-log', 2); ?>
	</div>
</div>