<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div class="row">
	<div class="col-md-12 col-xs-12">
		<h1>Dlayer <small>What is it?</small></h1>
	
		<h2>Overview <small>One sentance overview</small></h2>
		
		<p>Dlayer is a web development tool aimed primarily at users that 
			don't have any web design or web development experience.</p>

		<h3>Goal <small>Are there any?</small></h3>

		<p>Dlayer has two main goals, the first is to simplify web 
			development, the second is provide the user with full control 
			over every single element and attribute that can be used to 
			create a web page, these are two goals that initially appear to 
			be very much at odds with each other.</p>
		
		<ol>
			<li>Simplify web development; A user should be able to build a 
				web page and then a web site without writing a single line 
				of CSS, HTML, Javascript or code.</li>
			<li>Provide full control; A user will have full control over 
				every element and attribute that can be used to create a web 
				page or web site.</li>
		</ol>
		
		<p>It needs to be stated that Dlayer is not a template system, 
			the user has real control over every element and attribute, 
			there is no smoke and mirrors, a user will not just be setting 
			options on limited predefined widgets although obviously a 
			library of modifiable widgets will exist.</p>

		<h3>Timeframe <small>How long?</small></h3>

		<p>When it is done!</p>
	</div>
</div>