<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div class="row">
	<div class="col-md-12">
		<h1>Dlayer <small>What is it?</small></h1>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		<h2>Overview</h2>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		<p>Dlayer is a web site development tool.</p>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		<h3>Goal</h3>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		<p>Dlayer has two core goals, the first is to simplify web development,
		the second is to provide full control over every element and attribute, 
		two goals that appear to be at odds with each other.</p>
		
		<ol>
			<li>Simplify web site development, a user should be able to 
			build a web site without writing a single line of html, css 
			or code.</li>
			<li>Provide full control over every element and attribute.</li>
		</ol>
		
		<p>It needs to be stated that Dlayer is not a clever templating system 
		with hundreds of pre-defined widgets, the user has real control over 
		every element and attribute.</p>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		<h3>Timeframe</h3>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		<p>When it is done!</p>
	</div>
</div>