<?php /** @var Dlayer_View_Codehinting */ $this ?>

<div class="row">
	<div class="col-md-12 col-xs-12">
		<h1>Dlayer <small>What is it?</small></h1>
	
		<h2>Overview <small>One sentance overview</small></h2>
		
		<p>Dlayer is a web development tool aimed primarily at users that 
			don't have any web design or web development experience.</p>

		<h3>Goals <small>Are there any?</small></h3>

		<p>Dlayer has two core goals, the first is to simplify web development 
			and web designer and the second is to provide the user will full 
			control over every element and attribute that can be used to 
			create a web page and web site, these are two goals that initially 
			appear to be very much at odds with each other.</p>
		
		<ol>
			<li>Simplify web development; A user should be able to build a 
				web page and web site without writing a single line of HTML, 
				CSS, JavaScript or code.</li>
			<li>Provide full control; A user will have full control over every 
				element and attribute that can be used to create a web page or 
				web site without necessarily knowing what the attributes 
				are.</li>
		</ol>
		
		<p>I believe it needs to be stated that Dlayer is not a template 
			system, the user has real control over every element and 
			attribute, there is no smoke and mirrors here. A user will not be 
			simply setting a few options on limited predefined widgets. 
			Predefined widgets will exist later in the app but a user will 
			be able to manipulate then anyway they like.</p>

		<h3>Timeframe <small>How long?</small></h3>

		<p>When it is done!</p>
		
		<p>I have been plugging away at this in one form or another since 
			2008, there is no point attempting to define a real estimate for 
			completion, life spends far too much time getting in the way of 
			my development time.</p>
	</div>
</div>