<?php /** @var $this Dlayer_View_Codehinting */ ?>

<article id="content">
    <h1>The history of Dlayer</h1>

    <h2>The idea</h2>

    <p>The idea for Dlayer solidified in early 2008, I can't pin an exact date 
    on when I settled on the final idea but I do know that I had been thinking 
    about the concept for a few years prior to 2008.</p>

    <p>Looking back I believe that part of the reason it took a couple of 
    years for the idea to cement was because before 2008 I wasn't completely 
    sure of my abilities. For the majority of the previous decade I had been 
    working either by myself or in small teams with junior members. Later on 
    I became conscious that I artificially limited some of my personal 
    development projects due to lack of self-belief.</p>

    <h2>The Dlayer that never was</h2>

    <p>There was potentially another Dlayer in early 2008, as in I nearly
    started developing a product with two colleagues from work.</p>

    <p>At the time I was Head of Development at a small web development firm
    in Newbury, I would have been working on the private project with the
    Designer and one of the Project managers.</p>

    <p>During a carpool drive home my Designer and I talked about working on a
    project together, the plan was that he would do all the creative work and
    I would do all the development work.</p>

    <p>It needs to be stated that the proposed system was not Dlayer and would
    never have been able to become Dlayer, it was a simple template based 
    system. The Designer was going to create thousands of small image and 
    HTML assets and I was going to build the system that would allow a user 
    to join it all together.</p>

    <p>Although on the surface someone may believe they can argue that the
    two systems are similar they couldn't be more different, both conceptually
    and architecturally. Dlayer exists, the other system doesn't, I'm
    mentioning it here specifically because there is and never was a link
    between Dlayer and the proposed system.</p>

    <p>Long story short, nothing happened, neither party was willing to commit 
    either fully or partially to the project, it was just a wistful dream.</p>

    <p>Time wise both projects overlapped at the concept stage, in reality
    there was only ever a vague idea for the group project, not even a real
    concept, Dlayer developed on its own.</p>

    <h2>Delayed start</h2>

    <p>Between 2008 and early 2010 very little development happened, I wrote
    thousands of lines of code and documentation as well as diagrams describing
    how I intended on Dlayer to work but no production level code.</p>

    <p>During the period I created several small proof of concept apps to test
    my ideas, specifically to test how the template designer and content
    manager could work. </p>

    <p>There are several reasons for the lack of development during that
    period, I met my wife to be, moved over to contracting and in
    general time just got away from me.</p>

    <h2>Development begins</h2>

    <p>In early 2010 I realised how long I had been sitting on the concept, I
    spent the next few months collating all my documentation and planning the
    development.</p>

    <p>In September 2010 I finally began development on the first 'proper'
    version of Dlayer. </p>

    <p>During the next twenty one months I created two separate versions of
    Dlayer, both of which stalled at the same point, I kept stumbling with how
    I wanted to manage the relationship between a template and a page, it
    wasn't until early 2012 that I realised the problem, I was making that
    app far too complicated.</p>

    <p>I had got far too close to the project, it took a meeting with my best
    friend to realise that, after reviewing the points my friend had brought
    up I realised my error, the app was too complicated because I had not only
    strayed from the initial goals but also from the initial designs.</p>

    <p>I gave myself a rather large kick in the arse and started reviewing my
    notes and planning development for a new version.</p>

    <p>I started development of the third version on the 1st May 2012, my
    current specification refers to that version and mirrors the original
    concept from early 2008.</p>
</article>