<?php /** @var Dlayer_View_Codehinting */ $this ?>

<div class="row">
	<div class="col-md-12 col-xs-12">
		<h1>The history of Dlayer <small>How it came to be</small></h1>

		<h2>The idea <small>When was the lightbulb moment?</small></h2>
		
		
		<p>Thinking back I believe the initial idea for Dlayer solidified in 
			early 2008, I can't pin down the exact date that I settled on the 
			final idea but I do know that I had been thinking about the 
			concept, either in parts or as a whole for at least a few years 
			prior to 2008.</p>
		
		<p>I've spent a lot of time thinking about why it took so long for 
			the idea to cement and I believe now that before 2008 I wasn't 
			completely sure of my abilities, for the majority of the previous 
			decade I had either been working by myself or in very small teams 
			with only junior members, I didn't have any peers to compare 
			myself to. I started working in larger and more skilled teams 
			after 2008 and became very conscious I had artificially limited 
			some of my early development projects because I thought I wasn't 
			able to complete them on my own or I was lacking certain 
			skills.</p>
		
		<h2>The Dlayer that never was <small>Wistful thinking!</small></h2>
		
		<p>There was nearly a vaguely similar product to Dlayer in 2008, as in 
			I nearly started working on a product with two other colleagues 
			from work. At the time I was Head of Development at a small web 
			development company in Newbury, UK, I would have been working on 
			the product with one of the Product Managers, lets call him Foo 
			and the Lead Designer, lets call him Bar.</p>
		
		<p>During a carpool drive home with Bar we talked about working on a 
			project together, the plan was that he would do all the creative 
			work and I would do all the development work, Foo was going to 
			handle commercial and marketing.</p>
		
		<p>Before I continue with the story it needs to be stated that the 
			proposed product was not Dlayer and it would never have been able 
			to become Dlayer, it was a very simple template driven system. 
			Bar was going to create thousands or small image and HTML assets 
			and I was going to develop a system that would allow users to 
			join them all together to create whatever they wanted.</p>
		
		<p>Although on the surface it could be argued that this product and 
			Dlayer are similar the reality is they couldn't be any more 
			different if they tried, it would be like attempting to argue 
			that a unicycle and  Mercedes SLK are the same, oh my god, a 
			car analogy. The two products differed both conceptually and 
			architecturally, on top of that, Dlayer exists and is on the web, 
			this imagined other product never even got to the planning 
			stage.</p>
		
		<p>Why am I mentioning the other potential product here? Three 
			reasons, firstly, full disclosure, I've no reason to hide 
			anything, secondly, I know there is an link between the two 
			products and never was, lastly, this all happened around the 
			time I started working on Dlayer, 2008.</p>
		
		<p>Very boring and long story short, nothing happened, neither Foo or 
			Bar were willing to commit to the product, even partially, it was 
			all just a wistful dream.</p>

		<h2>Delayed start <small>Procrastination?</small></h2>
		
		<p>Between 2008 and early 2010 there was very little real development 
			on what would later become the product you are reading about. 
			During the mentioned time frame I wrote thousands of lines of 
			code, mainly samples, endless documentation and created hundreds 
			of diagrams detailing how I intended the app to work, however, 
			very little real code.</p>
		
		<p>There are a multitude of reasons for the lack of development, two 
			of the major reasons being that I met my wife to be and I moved 
			over to contracting rather than full time development roles, 
			time just managed to get away from me.</p>

		<h2>Development begins <small>Finally!</small></h2>
		
		<p>In early 2010 I realised how long I had been sitting on the concept 
			for Dlayer and how very little I had to show for two years of 
			work. I spent the next few months collating all my documentation 
			and started planning the development of Dlayer. Development 
			began in earnest during September, I had finally started 
			development on the first real version of the product that would 
			later become the concept that is currently hosted at 
			<a href="https://www.dlayer.com">https://www.dlayer.com.</a></p>
		
		<p>Over the next 21 months I created two separate versions of Dlayer, 
			they both stalled at exactly the same point, I kept stumbling 
			with how I wanted to handle the relationship between a content 
			page and a  content page template.</p>
		
		<p>Hindsight is a wonderful thing, I had got far too close to the 
			project, it took a meeting with my best friend, lets call him 
			Dan to realise that. I let Dan have a play with the latest 
			version and after a very long postmortem I realised my error, 
			Dlayer was far too complicated, I had strayed from my original 
			concept and primary goal, a user shouldn't need to understand 
			web design or web development, Dlayer was at that point a tool 
			only really usable by web developers.</p>
		
		<p>I gave myself a rather large kick in the arse and went back to 
			my original notes and planned development for yet another version 
			of Dlayer, third times a charm?</p>
		
		<p>I started the development of the current version on the 1st May 
			2012, the current specification refers to this version and it 
			very much mirrors the original concept I started outlining in 
			2008.</p>
	</div>
</div>