<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div id="content">
    <h1>Dlayer</h1>
    
    <p>You can edit the details for the current site using the form below.</p>
    
    <p><em>At the moment whilst Dlayer is in early development all that needs 
    to be defined for a site is the name, as the system evolves 
    additional data will need to be defined.</em></p>
    
    <?php echo $this->form; ?>
</div>