<?php /** @var Dlayer_View_Codehinting */ $this ?>

<div class="row">
	<div class="col-md-12 col-xs-12">
		<h1>Web site manager <small>Web site management</small></h1>

		<p>Use the form below to edit the details for the selected web 
			site.</p>
	</div>
</div>

<div class="row">
	<div class="col-md-6 col-xs-12">
		<?php echo $this->form; ?>
	</div>	
	<div class="col-md-12 col-xs-12">
		<?php echo $this->furtherReading(); ?>
	</div>
</div>
