<?php /** @var Dlayer_View_Codehinting */ $this ?>

<div class="row">
	<div class="col-md-12 col-xs-12">	
		<h1>Dlayer Demo <small>Web development simplified</small></h1>
		
		<h2>Welcome to Dlayer</h2>
		
		<p>The goal of this demo is simple, it is meant to showcase 
			the designers that are currently in development, please check the 
			docs at <a href="http://www.dlayer.com">Dlayer.com</a> to see what 
			other designers are planned.</p>
		
		<p>Dlayer is an Open Source project so if you see something you 
			think could be better you can let me know on 
			<a href="https://github.com/Dlayer/dlayer">GitHub</a> or code it 
			yourself, if you spot a bug please check the issues list on 
			<a href="https://github.com/Dlayer/dlayer">GitHub</a>, if your bug 
			is not listed please add it.</p>
		
		<h3>Designers <small>All still in development</small></h3>

		<ol>
			<?php foreach($this->modules_enabled as $module) { ?>
				<li><a href="/<?php echo $this->escape($module['name']); ?>">
					<?php echo $this->escape($module['title']); ?></a> - 
				<?php echo $module['description']; ?></li>
				<?php } ?>
		</ol>
		
		<h3>Demo sites <small>Play at will, reset periodically</small></h3>

		<?php foreach($this->sites as $site) { ?>
			<?php if($site['id'] == $this->site_id) { ?>
				<p>
					<button type="button" class="btn btn-default btn-xs"><?php echo $this->escape($site['name']); ?></button>  
					<?php if($site['name'] != 'Sample site 1') { ?>
						<a href="/dlayer/index/edit-site" class="btn btn-default btn-xs">Edit</a> 
					<?php } ?>
					<a href="#" class="btn btn-default btn-xs disabled">Copy</a> 
					<span class="label label-success">Selected</span>
				</p>
				<?php } else { ?>
				<p>
					<a href="/dlayer/index/activate/site/<?php echo $this->escape($site['id']); ?>" class="btn btn-default btn-xs">
					<?php echo $this->escape($site['name']); ?></a>
				</p>
				<?php } ?>
			<?php } ?>
		<p><a href="/dlayer/index/new-site" class="btn btn-primary btn">New web site</a></p>
	</div>
</div>
<div class="row">
	<div class="col-md-12 col-xs-12">
		<?php echo $this->furtherReading(); ?>
	</div>
</div>