<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div class="row">
	<div class="col-md-12 col-xs-12">	
		<h1>Dlayer <small>Web development simplified</small></h1>
		
		<h3>Welcome to Dlayer</h3>
		
		<p class="bg-info dev-note">
			There are currently eight sections within Dlayer, each one is 
			tailored to a specific part of the web development process, please 
			check out each of them and if you have any feedback I would be 
			very happy to hear it, you can contact me either via my 
			<a class="btn btn-primary btn-xs" href="http://www.g3d-development.com" role="button">Development blog</a>
			 or by 
			<a class="btn btn-primary btn-xs" href="mailto:dean@g3d-development.com" role="button">Emailing me</a>
		</p>

		<p class="bg-warning dev-note">The entire app should be considered as a 
			very early alpha, as you will see below almost every section is 
			still in development or planning.</p>
	</div>
</div>

<div class="row">
	<div class="col-md-12 col-xs-12">
		<h2>Enabled sections <small>Either partial functionality or a 
			preview</small></h2>

		<p>The <?php echo count($this->modules_enabled); ?> sections listed 
			below are accessible, they are either actively being 
			developed, on hold because I need to bring up other parts of the 
			app before continuing development or in a preview state.</p>

		<ol>
			<?php foreach($this->modules_enabled as $module) { ?>
				<li><a href="/<?php echo $this->escape($module['name']); ?>">
					<?php echo $this->escape($module['title']); ?></a> - 
				<?php echo $module['description']; ?></li>
				<?php } ?>
		</ol>

		<h2>Disabled sections <small>Not for public consumption</small></h2>

		<p>The <?php echo count($this->modules_disabled); ?> sections listed 
			below are not accessible, this could be because they are still in 
			early development, planning or in a transition period, they are not 
			ready for prime time.</p>

		<ol>
			<?php foreach($this->modules_disabled as $module) { ?>
				<li><?php echo $this->escape($module['title']); ?> - 
				<?php echo $module['description']; ?></li>
				<?php } ?>
		</ol>
	</div>
</div>

<div class="row">
	<div class="col-md-12 col-xs-12">
		<h2>Web site <small>Your web sites</small></h2>

		<?php foreach($this->sites as $site) { ?>
			<?php if($site['id'] == $this->site_id) { ?>
				<p>
					<button type="button" class="btn btn-default btn-xs"><?php echo $this->escape($site['name']); ?></button>  
					<?php if($site['name'] != 'Sample site 1') { ?>
						<a href="/dlayer/index/edit-site" class="btn btn-default btn-xs">Edit</a> 
					<?php } ?>
					<a href="#" class="btn btn-default btn-xs disabled">Copy</a> 
					<span class="label label-success">Selected</span>
				</p>
				<?php } else { ?>
				<p>
					<a href="/dlayer/index/activate/site/<?php echo $this->escape($site['id']); ?>" class="btn btn-default btn-xs">
					<?php echo $this->escape($site['name']); ?></a>
				</p>
				<?php } ?>
			<?php } ?>
		<p><a href="/dlayer/index/new-site" class="btn btn-primary btn">New web site</a></p>
	</div>
</div>