<?php /** @var $this Dlayer_View_Codehinting */?>

<div class="row">
	<div class="col-md-6 col-sm-6 col-xs-12">
		<?php echo $this->form; ?>

        <?php if ($this->test_credentials !== false) { ?>
		
		<h3>Test credentials.</h3>
		
		<p>Please use one of the free combinations below to sign in to the demo.</p>
			
		<ul>
			<?php foreach($this->test_credentials as $identity) { ?>
				<li>
				<strong>Username:</strong> <?php echo $this->escape($identity['identity']); ?><br />
				<strong>Password:</strong> password-<?php echo $this->escape($identity['id']); ?> 
				<?php if($identity['logged_in'] == 1) { ?> 
				<span class="label label-danger">Account signed in</span>
				<?php } else { ?>
				<span class="label label-success">Account free</span>
				<?php } ?>
				</li>
			<?php } ?>
		</ul>

        <?php } else { ?>
        <h3>No account?</h3>
        <p>Please ask your site administrator to create an account if you don't have one.</p>
        <?php } ?>
	</div>

    <div class="col-md-6 col-sm-6 col-xs-12">
        <h3><span class="label label-success">v1.15</span> Blog/Rich text content items <small class="text-muted">(In progress)</small></h3>

        <ul>
            <li>Enabled the rich text content item tool. [Feature]</li>
            <li>Added a blog post content item [Feature]</li>
            <li>Original text content item renamed to 'plain text'.</li>
            <li>Added PHP Quill HTML renderer, used by the tools which have rich content areas.</li>
            <li>Minor fixes and improvements.</li>
        </ul>

        <h3><span class="label label-default">v1.14</span> Composite content items soon <small class="text-muted">(23rd February 2017)</small></h3>

	    <h3><span class="label label-default">v1.13</span> Bugs & Date <small class="text-muted">(18th February 2017)</small></h3>

        <h3><span class="label label-default">v1.12</span> Mixed bag <small class="text-muted">(14th February 2017)</small></h3>

        <h3><span class="label label-default">v1.11</span> Form Builder part 5 <small class="text-muted">(10th February 2017)</small></h3>

        <h3>And the older releases</h3>

        <p>The full <a href="http://www.dlayer.com/releases.html">release history</a> is available at Dlayer.com and
            on <a href="https://github.com/Dlayer/dlayer/releases">GitHub</a>.</p>
    </div>
</div>
