<?php /** @var $this Dlayer_View_Codehinting */?>

<div class="row">
	<div class="col-md-6 col-sm-6 col-xs-12">
		<?php echo $this->form; ?>

        <?php if ($this->test_credentials !== false) { ?>
		
		<h3>Test credentials.</h3>
		
		<p>Please use one of the free combinations below to sign in to the demo.</p>
			
		<ul>
			<?php foreach($this->test_credentials as $identity) { ?>
				<li>
				<strong>Username:</strong> <?php echo $this->escape($identity['identity']); ?><br />
				<strong>Password:</strong> password-<?php echo $this->escape($identity['id']); ?> 
				<?php if($identity['logged_in'] == 1) { ?> 
				<span class="label label-danger">Account signed in</span>
				<?php } else { ?>
				<span class="label label-success">Account free</span>
				<?php } ?>
				</li>
			<?php } ?>
		</ul>

        <?php } else { ?>
        <h3>No account?</h3>
        <p>Please ask your site administrator to create an account if you don't have one.</p>
        <?php } ?>
	</div>

    <div class="col-md-6 col-sm-6 col-xs-12">
        <h3><span class="label label-success">v1.17</span> Quill and refactoring <small class="text-muted">(12th September 2017)</small></h3>

        <ul>
            <li>New styling table for content items, stores all defined styles, no need for a table per styling group. [Refactoring]</li>
            <li>Cleaned up tools, removed redundant model classes and moved around shared classes, now more apparent if they relate to content or not. [Refactoring]</li>
            <li>Now using Quill PHP renderer v1.01.1, enables support for lists in text areas.</li>
        </ul>

        <h3><span class="label label-default">v1.16</span> Horizontal rule & styling <small class="text-muted">(12th March 2017)</small></h3>

        <h3><span class="label label-default">v1.15</span> Blog/Rich text content items <small class="text-muted">(3rd March 2017)</small></h3>

        <h3><span class="label label-default">v1.14</span> Composite content items soon <small class="text-muted">(23rd February 2017)</small></h3>

	    <h3><span class="label label-default">v1.13</span> Bugs & Date <small class="text-muted">(18th February 2017)</small></h3>

        <hr />

        <h3>And the older releases</h3>

        <p>The full <a href="http://www.dlayer.com/releases.html">release history</a> is available at Dlayer.com and
            on <a href="https://github.com/Dlayer/dlayer/releases">GitHub</a>.</p>
    </div>
</div>
