<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div class="row">
	<div class="col-md-12 col-xs-12">
		<h1>Dlayer.com <small>Web development simplified</small></h1>
	</div>
	
	<div class="col-md-12 col-xs-12">
		<p>A development project I have been working on for a number of 
			years, far too many according to my wife.</p>
	</div>
	
	<div class="col-md-12 col-xs-12">
		<h2>Project goal <small>Still a way off being achieved</small></h2>
		
		<p>I have long term goals for 
			<a href="https://www.dlayer.com/">Dlayer.com</a> which far exceed 
			the published specification. After many years I have realised that 
			it will be better for my sanity to finish a preview / concept 
			version of <a href="https://www.dlayer.com/">Dlayer.com</a> rather 
			than attempt to develop the entire project single handled.</p>
		
		<p>As stated above this project is being developed as a proof of 
			concept, however, I am trying to write as much production level 
			code as possible. Some areas of the app will be deliberately flaky 
			when I know they are going to evolve fairly rapidly.</p>
		
		<p>The intention is that this preview will allow me to get external 
			parties interested in either investing or joining, ideally, I'd 
			like to build a team and realise the app that I imagine in 
			2008.</p>
		
		<p>As I am trying to showcase the concept I'm trying to use the best 
			technology that I can, this includes 
			<a href="http://www.w3.org/TR/html5/forms.html">HTML5</a>, 
			specifically some of the new input types. At the time of writing 
			<a href="https://www.google.com/intl/en/chrome/browser/">Chrome</a> 
			supports more of the new input types than any other browser.</p>

		<p class="bg-info dev-note">If you would like to get in contact with 
			me about Dlayer please contact me at dean (at) g3d-development 
			(dot) com or via my <a class="btn btn-primary btn-xs" href="http://www.g3d-development.com" role="button">Development blog</a>.</p>

		<h4><strong>Dean Blackborough</strong> - 
		<a href="http://www.g3d-development.com">G3D Development Limited</a></h4>
	</div>
</div>

<div class="row">
	<div class="col-md-6 col-xs-12">
		<?php echo $this->form; ?>
	</div>
	
	<div class="col-md-6 col-xs-12">
		<h4>Test credentials <small>use one the combinations below to sign in 
			and test Dlayer</small></h4>
		
		<ul>
		<?php foreach($this->test_identities as $identity) { ?>
			<li>
			<?php echo $this->escape($identity['identity']); ?> / 
			password-<?php echo $this->escape($identity['id']); ?> 
			<?php if($identity['logged_in'] == 1) { ?> 
			<span class="label label-danger">Account signed in</span>
			<?php } else { ?>
			<span class="label label-success">Account free</span>
			<?php } ?>
			</li>
		<?php } ?>
		</ul>
	</div>
</div>