<?php /** @var $this Dlayer_View_Codehinting */?>

<div class="row">
	<div class="col-md-12 col-xs-12">
		<h1>Web site manager <small>Web site management</small></h1>

		<h2><span class="label label-default">Web site: <?php echo $this->escape($this->site['name']); ?></span></h2>

		<h3>Quick introduction</h3>

		<p>Use the form below to create a new web site, you need to provide 
			a unique name for the web site.</p>
			
		<p>There are tickets on GitHub to exapnd the new web site process, 
			initially the colour pallette to start which and layout of this 
			initial template, two columns, three columns.</p>		
	</div>
</div>

<div class="row">
	<div class="admin-form col-md-6 col-sm-8 col-xs-12">
		<?php echo $this->form; ?>
	</div>
	<div class="col-md-12 col-xs-12 further-reading">
        <?php echo $this->furtherReading(null, true); ?>
	</div>
</div>
