<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div class="row">
	<div class="col-md-12">
		<h1>Web site management <small>Create a new blank web site</small></h1>

		<p>You can create a new site using the form below.</p>
		
		<p class="bg-info dev-note">At the moment whilst Dlayer is in early 
		development all that needs to be defined for a site is the name, 
		as the system evolves additional data will need to be defined.</p>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		<h2>New web site</h2>
	</div>
</div>

<div class="row">
	<div class="col-md-6">
		<?php echo $this->form; ?>
	</div>
</div>