<?php /** @var Dlayer_View_Codehinting */ $this ?>

<div class="row">
	<div class="col-md-12 col-xs-12">
		<h1>Web site manager <small>Web site management</small></h1>

		<p>Use the form below to create a new web site, you need to provide 
			a unique name for your new web site.</p>
			
		<p>There are tickets on GitHub to exapnd the new web site process, 
			initially the colour pallette to start which and layout of this 
			initial template, two columns, three columns.</p>		
	</div>
</div>

<div class="row">
	<div class="col-md-6 col-xs-12">
		<?php echo $this->form; ?>
	</div>
	<div class="col-md-12 col-xs-12">
		<?php echo $this->furtherReading(); ?>
	</div>
</div>
