<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div class="row">
	<div class="col-md-12 col-xs-12">
		<h1>Dlayer <small>Why would I use it?</small></h1>
		
		<h2>What is it for? <small>What can Dlayer do for me?</small></h2>
		
		<p>You can use Dlayer anyway that you would like, you can use just one 
			feature or you can use everything, I foresee three core groups 
			that users will fit into.</p>
			
		<h3>All in <small>Give me everything</small></h3>
		
		<p>You will use Dlayer to create your entire web site, you will 
			probably use everything designer and either host directly with us 
			or export the site to host on your own servers</p>
		
		<h3>Al a carte <small>I only want to use one thing</small></h3>
		
		<p>Your interest in Dlayer gravitates around a single feature or 
			designer, you'll generate a form, site or page widget, data form, 
			poll or any other number of items and display them directly on 
			your own website. You will be able to make a request to the Dlayer 
			web service and the generated HTML, CSS and JavaScript will 
			either be returned directly for inclusion on your website or 
			eventually you can use the plug-ins for the popular content 
			management systems once they are development, for example 
			WordPress.</p>
		
		<h3>Tasting <small>Just nibbling</small></h3>
		
		<p>You will use Dlayer for some other function that I haven't 
			foreseen, this could be testing, scaffolding, or data management, 
			if you fit into this group once the system matures a little 
			please let me know, I will be very interested in hearing how 
			you use Dlayer and hearing what you would like to see.</p>
	</div>
</div>