<?php /** @var Dlayer_View_Codehinting */ $this ?>

<div id="content">
    <h1>Library development</h1>
    
    <h2>Image cropper - process</h2>
    
    <p>This action will have attempted to crop the requested image, below will 
    either be a success message or the generated errors.</p>
    
    <p>Return to the <a href="/dev/crop/index">image cropper</a> to 
    see and delete the generated image.</p>
    
    <p><strong>Errors:</strong> <?php echo $this->escape($this->error); ?></p>
</div>