<?php /** @var Dlayer_View_Codehinting */ $this ?>

<div class="row">
	<div class="col-md-12 col-xs-12">
		<h1>Form builder <small>Form management <span class="label label-default">Site: <?php echo $this->escape($this->site['name']); ?></span></small></h1>

		<p>Use the form below to edit the details for the selected form, to alter the title and sub title use the
			form layout tool in the Form builder.</p>
	</div>
</div>

<div class="row">
	<div class="col-md-6 col-xs-12">
		<?php echo $this->form; ?>
	</div>
</div>

<div class="row">
	<div class="col-md-12 col-xs-12 further-reading">
		<?php echo $this->furtherReading('/#form-builder', TRUE); ?>
	</div>
</div>
