<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div class="row">
	<div class="col-md-12 col-xs-12">
		<h1>Form management <small>Edit the selected form</small></h1>

		<p>Edit the details for the selected form using the form below.</p>
			
		<p class="dev-note bg-info">At the moment whilst Dlayer is in early 
			development all that needs to be defined for a form is the name, 
			as the system evolves additional data will need to be defined.</p>
	</div>
</div>

<div class="row">
	<div class="col-md-6 col-xs-12">
		<?php echo $this->form; ?>
	</div>
</div>