<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div class="row">
	<div class="col-md-12 col-xs-12">
		<h1>Form builder <small>Form management</small></h1>
	</div>

	<div class="col-md-12 col-xs-12">
		<h2>Web site 
		<small><?php echo $this->escape($this->site['name']); ?></small></h2>
	</div>

	<div class="col-md-12 col-xs-12">
		<p>Using the form builder you create forms which you can add to 
			templates, widgets or directly to content pages. The core use of 
			forms is for gathering information from your visitors but as 
			both the Form builder and Widget designer increase in 
			functionality the forms will be able to be used for other 
			purposes.</p>
			
		<p>There is no enforced limit to the number of forms you can create 
			for a single web site. In addition, it doesn't matter how you 
			modify a form once it has gone live on your site, submitted form 
			data is never lost and will always be accessible in its 
			original format.</p>
			
		<p>Select a form from the list below, once a form has been activated 
			you work on it in the Form builder, edit the base details or 
			copy the structure to create a new form.</p>
			
		<h2>Forms <small>Forms for this web site</small></h2>
		
    	<?php foreach($this->forms as $form) { ?>
    		<?php if($form['id'] == $this->form_id) { ?>
    			<p>
    				<button type="button" class="btn btn-default btn-xs">
    					<?php echo $this->escape($form['name']); ?> 
    				</button>
    				<a href="/form/design/" class="btn btn-default btn-xs">Manage</a> 
    				<a href="/form/index/edit-form" class="btn btn-default btn-xs">Edit</a> 
    				<a href="#" class="btn btn-default btn-xs disabled">Copy structure</a> 
    				<span class="label label-success">Selected</span>
    			</p>
    		<?php } else { ?>
    			<p>
    				<a href="/form/index/activate/form-id/<?php echo $this->escape($form['id']); ?>" 
    				class="btn btn-default btn-xs">
    				<?php echo $this->escape($form['name']); ?></a>
    			</p>
    		<?php } ?>
    	<?php } ?>
	    <p><a href="/form/index/new-form" class="btn btn-primary">New form</a></p>
	</div>
</div>