<?php /** @var Dlayer_View_Codehinting */ $this ?>

<div class="row">
	<div class="col-md-12 col-xs-12">
		<h1>Form builder <small>Form management <span class="label label-default">Site: <?php echo $this->escape($this->site['name']); ?></span></small></h1>

		<p>Use the form below to create a new form, you need to provide 
			a unique name for the form, a title which appears above the form 
			and an email address that any submissions will be sent to.</p>
	</div>
</div>

<div class="row">
	<div class="col-md-6 col-xs-12">
		<?php echo $this->form; ?>
	</div>
	<div class="col-md-12 col-xs-12 further-reading">
		<?php echo $this->furtherReading('/#form-builder', TRUE); ?>
	</div>
</div>
