<?php /** @var $this Dlayer_View_Codehinting */ ?>

<h2>Email field</h2>

<p>This tool allows you to quickly add an email field to your form, the email 
field is just a single line field with the values preset, in addition to 
setting the initial values this tool also sets validation settings.</p>

<p>To add the email field to your form simply click save, if required you can 
change the preset values.</p>

<p>The email field can be edited as per a standard single line text field.</p>