<?php /** @var Dlayer_View_Codehinting */ $this ?>

<div class="col-xs-12">
	<h3>Help <small>Add comment field</small></h3>

	<p>This tool allows you to quickly add a comment field to your form, a 
		comment field is simply a text area field where the options are already 
		set.</p>
		
	<p>Once the comment field has been added to your form you can edit it as you 
		would any text area field, all the options are configurable.</p>
</div>

<div class="col-xs-12 further-reading">
	<?php echo $this->furtherReading('/#form-builder'); ?>
</div>