<?php /** @var Dlayer_View_Codehinting */ $this ?>

<style>
	#ribbon form legend {
		display: none;
	}
	#ribbon form .form-group {
		display: none;
	}
	#ribbon form .form-group-submit {
		display: block;
	}
</style>

<div class="col-xs-12">
	<h3>Add <small>Add a comment field to your form</small></h3>

	<p>Click <mark>add</mark> to quickly add a comment field to your form, all 
		the options and values have been preset for you.</p>
</div>

<div class="col-xs-12 small">
	<?php 
	if($this->data != FALSE) {
		echo $this->data['form'];
	}
	?>
</div>