<?php /** @var $this Dlayer_View_Codehinting */ ?>

<h2>Resize block</h2>

<p>This tool allows you to resize the selected template block, you can resize 
the block by pushing the edges out, pulling them in, adjusting the height or 
by setting a custom size which works everything out for you.</p>

<p>The push and pull options steal from the surrounding page blocks, if you 
push an edge down the blocks below will reduce in size.</p>

<p>If you adjust the height of a template block other template blocks will 
only move to compensate, they will not change in size.</p>

<p>If an option isn't shown for a page block it is because it is impossible 
to move the edge in the requested direction.</p>

<p>If required the modifier system will be called after the tool has processed 
to update the size of an content items that may have been affected by the 
change.</p>