<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div id="content">
    <h1>Library development</h1>
    
    <p>Module for library development, module exists so that I can test new 
    classes without having to modify any of the existing working code.</p>
    
    <h2>Classes/Tools</h2>
    
    <ul>
        <li><a href="/dev/thumbnail/index">Thumbnail generator</a> - Generate 
        thumbnails for images, initially no options, maintain aspect ratio 
        and adds relevant white padding.</li>
        <li><a href="/dev/thumbnail-advanced/index">Advanced thumbnail generator</a> 
        - Fully configurable version of the above.</li>
        <li><a href="/dev/crop/index">Crop</a> - Cropped the selected image 
        creating a new image based on the crop selection rectangle and the 
        rectangle position.</li>
        <li><a href="/dev/resizer/index">Library resizer</a> - Extension to 
        advanced resizer, added ability to define destination path and file and 
        also resize smaller image by placing them in the middle of the 
        destination canvas.</li>
    </ul>
</div>