<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div id="content">
    <h1>Form builder</h1>
    
    <h2>Web site: <?php echo $this->escape($this->site['name']); ?></h2>
    
    <p>Edit the details for the selected page using the form below.</p>
    
    <p class="dev">At the moment whilst Dlayer is in early development all 
    that needs to be defined for a page is the name, template to use and 
    title, as the system evolves additional data will need to be defined.</p>
    
    <?php echo $this->form; ?>
</div>