<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div class="row">
	<div class="col-md-12">
		<h1>Content management <small>Edit the selected content page</small></h1>

		<p>Edit the details for the selected content page using the form 
			below.</p>
			
		<p class="dev-note bg-info">At the moment whilst Dlayer is in early 
			development all that needs to be defined for a page is the name 
			and the template to use, as the system evolves additional data 
			will need to be defined.</p>
	</div>
</div>

<div class="row">
	<div class="col-md-6">
		<?php echo $this->form; ?>
	</div>
</div>