<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div class="row">
	<div class="col-md-12">
		<h1>Content manager <small>Web site content management</small></h1>
	</div>

	<div class="col-md-12">
		<h2>Web site 
		<small><?php echo $this->escape($this->site['name']); ?></small></h2>
	</div>

	<div class="col-md-12">
		<p>Using the content manager you can either create new pages for your 
			web site or manage the existing content, content is classed as 
			anything from text and images all the way up to forms 
			and widgets.</p>
			
		<p>You can create a content page by either creating a new one using 
			one of the web site templates or copying and existing 
			content page.</p>
			
		<p>You don't manage the relationship between pages here, that is 
			done using the Web site manager, the Content manager is purely for 
			adding content and editing existing content.</p>
			
		<p>Select a page from the list below, once a page has been activated 
			you can open it in the designer, edit the base detials or 
			create a new page by copying it.</p>
			
		<p class="dev-note bg-info">The Content manager tools are not as per my 
			final design, as it stands today when adding or editing content 
			everything needs to be defined in the side panel. As development 
			continues I will update all the Content manager tools, the side 
			panel will only be for controlling data that cannot easily be 
			managed directly in the designer view.</p>
			
		<h2>Pages <small>Pages for this web site</small></h2>
		
    	<?php foreach($this->pages as $page) { ?>
    		<?php if($page['id'] == $this->page_id) { ?>
    			<p>
    				<button type="button" class="btn btn-default btn-xs">
    					<?php echo $this->escape($page['name']); ?>
    				</button>
    				<span class="label label-info"><?php echo $this->escape($page['template']); ?></span>
    				<a href="/content/design/" class="btn btn-default btn-xs">Design</a> 
    				<a href="/content/index/edit-page" class="btn btn-default btn-xs">Edit</a> 
    				<a href="#" class="btn btn-default btn-xs disabled">Copy</a> 
    				<span class="label label-success">Selected</span>
    			</p>
    		<?php } else { ?>
    			<p>
    				<a href="/content/index/activate/page-id/<?php echo $this->escape($page['id']); ?>" 
    				class="btn btn-default btn-xs">
    				<?php echo $this->escape($page['name']); ?> (<?php echo $this->escape($page['template']); ?>)</a>
    			</p>    			
    		<?php } ?>
    	<?php } ?>
	    <p><a href="/content/index/new-page" class="btn btn-primary">New page</a></p>
	</div>
</div>