<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div id="content">
    <h1>Content manager</h1>
    
    <h2>Web site: <?php echo $this->escape($this->site['name']); ?></h2>
    
    <p>Use the form below to add a new page to your webs ite. Once you have 
    added the new page you can immediately start working on it.</p>
    
    <p><em>At the moment whilst Dlayer is in early development all that needs 
    to be defined for a page is the name and the template to use, as the 
    system evolves additional data will need to be defined.</em></p>
    
    <?php echo $this->form; ?>
</div>