<div class="row">
	<div class="col-md-12 col-sm-12 col-xs-12">

		<h1>Dlayer <small>Open Source responsive web development tool</small></h1>

		<p class="lead">The installation process is a work in progress; Dlayer is rapidly improving, I wanted an
			installation process, but I wanted it to be simple enough so as not to slow me down as I add new
			features to Dlayer.</p>

		<p>I want to improve and simplify this installation process, it is not user-friendly, as soon as Dlayer is
			more mature I will revisit the system. Please keep an eye on the Dlayer development
			<a href="http://blog.dlayer.com/">blog</a> and of course if you are interested in improving the
			installation process please <a href="http://dlayer.com/coding-standards.html">get in touch</a> with me.</p>

		<h2>Import demo database</h2>

		<p>Please select the button below to import the demo database for Dlayer, if there are any tables in the
            database the script will not run, this process should only be executed ion an empty database.</p>

        <p><a class="btn btn-danger" href="#">Import demo database</a></p>
	</div>
</div>
