<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div id="tab_content_1" class="content open">
    <h2>Welcome to the Dlayer Form builder.</h2>
    
    <p>Create your form by adding the required form inputs using the tool bar 
    on the right side. If you need to edit a field move the mouse over the 
    field and click to select it, this only works when you don't have a tool 
    already selected.</p>
</div>