<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div class="row">
	<div class="col-xs-12">
		<h2>Welcome to the Form builder</h2>
		
		<h4><span class="glyphicon glyphicon-play" aria-hidden="true"></span> 
		Add a new field to the form</h4>
		<h4><span class="glyphicon glyphicon-play" aria-hidden="true"></span> 
		Edit an existing field</h4>
		<h4><span class="glyphicon glyphicon-play" aria-hidden="true"></span> 
		Modify the form settings</h4>
		
		<p>To add a new field to the form select the tool that matches the 
			field you want to add, you can either add a preset field using 
			the preset field tools or create the field manually using the 
			standard field tools</p>
		
		<p>To edit a field select it by simply hovering the mouse over it 
			and clicking the left mouse button.</p>
		
		<p>To modify the settings for the form select the relevant tool 
			from the settings section.</p>
	</div>
</div>