<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div id="tab_content_1" class="content open">
    <h2>Welcome to the Dlayer Form builder.</h2>
    
    <p>Create your form by using the tools above to set the options for the 
    form and add the required inputs.</p>
    
    <p>If you need to edit a field hover over it when the mouse and click 
    to select, this will only work when there are no other tools selected.</p>
</div>