<script type="text/javascript">
$(document).ready(function() 
{
    dlayer.ribbon.tabs.clicks('<?php echo $this->escape($this->module); ?>', 
    '<?php echo $this->escape($this->tool); ?>');
    dlayer.ribbon.tabs.content('<?php echo $this->escape($this->tab); ?>', 
    '<?php echo $this->escape($this->tool); ?>', 
    '<?php echo $this->escape($this->module); ?>');
});
</script>

<nav class="tabs">
<?php foreach($this->tabs as $tab) { ?>
    <?php if($tab['tab'] == $this->tab) { $class = ' selected'; } else { $class = NULL; } ?>
    <div id="tab_<?php echo $this->escape($tab['tab']); ?>" class="tab<?php echo $class; ?>"><?php echo $this->escape($tab['tab_name']); ?></div>
<?php } ?>
</nav>

<?php foreach($this->tabs as $tab) { ?>
    <?php if($tab['tab'] == $this->tab) { $class = ' open'; } else { $class = NULL; } ?>
    <div id="tab_content_<?php echo $this->escape($tab['tab']); ?>" class="row content<?php echo $class; ?>"></div>
<?php } ?>