<?php /** @var Dlayer_View_Codehinting */ $this ?>

<div class="row">
    <div class="col-md-12 col-xs-12">
        <h1>Logs</h1>

        <h2>Error log</h2>

        <?php if(count($this->file) > 0) { ?>
		    <ul>
        <?php foreach($this->file as $line) { ?>
	        <li><?php echo $this->escape($line); ?></li>
        <?php } ?>
        </ul>
        <?php } else { ?>
		    <h3>No log data</h3>
        <?php } ?>
    </div>
</div>
