<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div id="content">
    <h1>Template designer</h1>
    
    <h2>Web site: <?php echo $this->escape($this->site['name']); ?></h2>
    
    <p>Edit the details for the selected template using the form below.</p>
    
    <p><em>At the moment whilst Dlayer is in early development all that needs 
    to be defined for a template is the name, as the system evolves 
    additional data will need to be defined.</em></p>
    
    <?php echo $this->form; ?>
</div>