<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div class="row">
	<div class="col-md-12 col-xs-12">
		<h1>Template designer <small>Content page template management</small></h1>
		
		<h3>Welcome to the Template designer</h3>
		
		<p>A template defines the basic structure of a content page, all 
			content pages are built upon a template. </p>
		
		<p>Templates are typically simply although there is nothing limiting 
			the creation of complex templates, think of them as a way of 
			blocking out content areas, the obvious examples being where the 
			header, footer and main content areas are on a content page.</p>
		
		<p>There are no artificial limits to the number of templates you can 
			design for a web site, the number of content pages based upon a 
			single template or how many items can be added to them. Forms 
			and widgets can be added to templates but typically most of the 
			content and flourish that makes up a content page will be added 
			in the Content manager.</p>
			
		<p class="dev-note bg-warning">The Template designer has been stripped 
			right back to the basics, before the Bootstrap update v0.50 there 
			were five tools to use each with multiple tabs, the missing tools 
			will be added once the rest of the app has undergone more 
			development.</p>
			
		<h2>Templates <small>All your templates</small></h2>
		
		<p>Select a template from the list below, once selected you can start 
			or continue designing it, edit the base details or copy it to 
			create a brand new template.</p>
		
		<?php foreach($this->templates as $template) { ?>    	
			<?php if($template['id'] == $this->template_id) { ?>
				<p>
					<button type="button" class="btn btn-default btn-xs">
					<?php echo $this->escape($template['name']); ?></button>  
					<a href="/template/design/" class="btn btn-default btn-xs">Design</a>  
					<a href="/template/index/edit-template" class="btn btn-default btn-xs">Edit</a>  					<a href="#" class="btn btn-default btn-xs disabled">Copy</a>  
					<span class="label label-success">Selected</span>
				</p>
				<?php } else { ?>
				<p>
					<a href="/template/index/activate/template-id/<?php echo $this->escape($template['id']); ?>" 
					class="btn btn-default btn-xs">
					<?php echo $this->escape($template['name']); ?></a>
				</p>
				<?php } ?>
			<?php } ?>
		<p>
			<a href="/template/index/new-template" 
			class="btn btn-primary">New template</a>
		</p>
		
		<?php echo $this->furtherReading('the-designers/template-designer/'); ?>
	</div>
</div>