<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div class="row">
	<div class="col-md-12">
		<h1>Template designer <small>Web site template management</small></h1>
	</div>

	<div class="col-md-12">
		<h2>Web site 
		<small><?php echo $this->escape($this->site['name']); ?></small></h2>
	</div>

	<div class="col-md-12">
		<p>Using the template designer you create the templates for your 
			content pages, these define the basic structure of a page, as in 
			where the menu, header and footer are placed and any items that 
			you want to appear on multiple pages, for example a small contact 
			form or the main menu.</p>

		<p>Templates are typically very simple, they are just for boxing out 
			the design, you add the flourish to your pages using widgets and 
			forms and then once a page has been created you create a page from 
			it in the Content manager.</p>

		<p>There is no artificial limits to the number of templates you can 
			create for a web site. Templates can have widgets and forms 
			attached to them, you create the forms and widgets in the Form 
			builder and Widget designer.</p>

		<p>Select a template from the list below, once a template has been 
			activated you can continue working on the design, edit it or 
			copy it to create a new template.</p>
			
		<h2>Templates <small>Templates for this web site</small></h2>
		
		<?php foreach($this->templates as $template) { ?>    	
			<?php if($template['id'] == $this->template_id) { ?>
				<p>
					<button type="button" class="btn btn-default btn-xs">
					<?php echo $this->escape($template['name']); ?></button>  
					<a href="/template/design/" class="btn btn-default btn-xs">Design</a>  
					<a href="/template/index/edit-template" class="btn btn-default btn-xs">Edit</a>  					<a href="#" class="btn btn-default btn-xs disabled">Copy</a>  
					<span class="label label-success">Selected</span>
				</p>
				<?php } else { ?>
				<p>
					<a href="/template/index/activate/template-id/<?php echo $this->escape($template['id']); ?>" 
					class="btn btn-default btn-xs">
					<?php echo $this->escape($template['name']); ?></a>
				</p>
				<?php } ?>
			<?php } ?>
		<p>
			<a href="/template/index/new-template" 
			class="btn btn-primary">New template</a>
		</p>
	</div>
</div>