<?php /** @var Dlayer_View_Codehinting */ $this ?>

<div class="row">
	<div class="col-md-12 col-xs-12">
		<h1>Template designer <small>Template management <span class="label label-default">Site: <?php echo $this->escape($this->site['name']); ?></span></small></h1>

		<p>Use the form below to create a new page template, template names 
			are unique.</p>
	</div>
</div>

<div class="row">
	<div class="col-md-6 col-xs-12">
		<?php echo $this->form; ?>
	</div>
	<div class="col-md-12 col-xs-12 further-reading">
		<?php echo $this->furtherReading('/#template-designer', TRUE); ?>
	</div>
</div>
