<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div class="col-xs-12">
	<p class="dev-note bg-danger unsaved">Data has been modified!</p>
</div>

<div class="col-xs-12 small">
	<?php 
	if($this->data != FALSE) {
		echo $this->data['form'];
	}
	?>
	
	<p class="text-warning">There is no live preview when changing any of the 
		values below, live preview for layout changes is on the task list and 
		will hopefully be completed soon(tm).</p>
</div>

