<?php /** @var $this Dlayer_View_Codehinting */ ?>

<script>
dlayer.ribbon.form.fn.toggleAdditionalFields();
</script>

<div class="col-xs-12">
	<p class="dev-note bg-danger unsaved">Data has been modified!</p>
</div>

<div class="col-xs-12 small">
	<?php 
	if($this->data != FALSE) {
		echo $this->data['form'];
	}
	?>
</div>

<div class="col-xs-12">
	<p class="dev-note bg-info">There is no live preview when changing any of the 
		values below, live preview for layout changes is on the task list and 
		will hopefully be completed soon(tm).</p>
</div>

