<?php /** @var $this Dlayer_View_Codehinting */ ?>

<div class="col-xs-12">
	<h3>Help <small>Set the layout options for your form</small></h3>
	
	<p>The title appears above your form, the sub title is optional, it 
		appears in a smaller lighter font to the right of the title, leave 
		it blank if you don't need one.</p>
	
	<p>You can define the label for the submit button, if you would like a 
		reset button enter a label in the field, if left blank the reset 
		button will not be added to your form.</p>
		
	<h4>Layout options</h4>
	
	<p><strong>Standard:</strong> Label appears above the field, both are the 
		full width of the container.<br />
		<strong>Horizontal:</strong> Label and field appear on the same row 
		according to the define widths.<br />
		<strong>Inline:</strong> Labels and fields site inline flowing left 
		to right.
</div>