<?php /** @var $this Dlayer_View_Codehinting */ ?>

<script type="text/javascript">
	$(document).ready(function() 
		{
			<?php if($this->div_id == NULL && $this->tool == NULL) { ?>
				dlayer.selectors.template();
			<?php } ?>
			<?php if($this->div_id != NULL && $this->tool != NULL) { ?>
				dlayer.designers.metrics.pageContainer();
			<?php } ?>
	});
</script>

<div id="designer">
	<div id="design">
		<?php echo $this->dlayer_template; ?>
	</div>
	<?php if(strlen($this->dlayer_toolbar) > 1) { ?>
	<div id="tools">
		<?php echo $this->dlayer_toolbar; ?>
	</div>
	<?php } ?>
	<?php if($this->div_id != NULL && $this->tool != NULL) { ?>
		<div id="content-block-metrics">
			<div class="row">
				<div class="col-xs-12 metrics-title">
					<h3 class="title">Metrics <small>Click to show content block sizes</small></h3>
				</div>
				<div class="col-xs-12 metrics">
				
				</div>			
			</div>
		</div>
		<?php } ?>
	<div id="ribbon">
		<?php echo $this->dlayer_ribbon; ?>
	</div>
</div>