<?php /** @var $this Dlayer_View_Codehinting */ ?>

<?php 

foreach($this->tools as $group) {
	
    $html = '';
    
    foreach($group as $group_tool) {
        
        $show = FALSE;
        $selected = FALSE;
        
        if($this->div_id !== NULL) {
        
            // Base div selected, base tool            
            if($this->div_id == 0 && $group_tool['base'] == 1) {
                $show = TRUE;
            }
            
            // Any div other than base div
            if($this->div_id != 0) {
                $show = TRUE;
            }
            
            // Check to see if selected tool
            if($this->tool['tool'] == $group_tool['tool']) {
                $selected = TRUE;
            }
        }
        
        if($show == TRUE) {
            if($selected == FALSE) {
                $html .= '<div class="tool">';
            } else {
                $html .= '<div class="tool selected">';
            }
            
            if($this->has_content == FALSE) {            	
                $html .= '<a href="/template/design/set-tool/tool/' . 
                $this->escape($group_tool['tool']) . '">' . 
                $this->escape($group_tool['name']) . '</a>';
			} else {
				if($group_tool['destructive'] == 0) {
					$html .= '<a href="/template/design/set-tool/tool/' . 
                    $this->escape($group_tool['tool']) . '">' . 
                    $this->escape($group_tool['name']) . '</a>';
				} else {
					$html .= '<span class="destructive">' . 
                    $this->escape($group_tool['name']) . '</span>';
				}
			}
            
	        $html .= '</div>' . PHP_EOL;
        }
    }
    
    if(strlen($html) > 0) {
    	echo '<div class="group">' . PHP_EOL;
    	echo $html;
    	echo '</div>' . PHP_EOL;
	}
} 
?>